### ISSUE TITLE
Error with pirated users

### ISSUE THREAD

**Issue by jefflima1** [games647/FastLogin#1000]
### What happened?

[10:05:09] [Craft Scheduler Thread - 49 - FastLogin/ERROR]: [FastLogin] Failed to check premium state of luciusbsd
java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/luciusbsd
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at com.github.games647.craftapi.resolver.MojangResolver.findProfile(MojangResolver.java:196) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:93) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:74) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.process(AsyncScheduler.java:70) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.lambda$runAsync$0(AsyncScheduler.java:61) ~[FastLoginBukkit.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-460]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-460]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/luciusbsd
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
	at com.github.games647.craftapi.resolver.MojangResolver.findProfile(MojangResolver.java:181) ~[FastLoginBukkit.jar:?]
	... 11 more
[10:05:11] [User Authenticator #2/INFO]: UUID of player luciusbsd is c8b2829e-c808-3df0-9dfd-6bd15b127ab3
[10:05:12] [Server thread/INFO]: luciusbsd joined the game

### What did you expect?

That it does not generate this error in the console every time a pirate user enters

### Steps to reproduce

Log in with a non-genuine user

### Plugin list

[10:14:20 INFO]: Server Plugins (53): [10:14:20 INFO]: Bukkit Plugins: [10:14:20 INFO]:  - AuthMe, BloodMoon, Bump, ChestSort, ClansLite, ClearLag, CyberWorldReset, DamageIndicator, DyedBackpacks, DynaTech [10:14:20 INFO]:  EcoPower, Essentials, EssentialsChat, EssentialsSpawn, ExtraGear, ExtraTools, FastLogin, FireworkDeath, floodgate, FluffyMachines [10:14:20 INFO]:  Geyser-Spigot, HotbarPets, InvSeePlusPlus, InvSeePlusPlus_Give, KeepDeathDrop, LuckPerms, M0-AntiAnvilRename, MobCapturer, Networks, PlaceholderAPI [10:14:20 INFO]:  PrivateStorage, ProtocolLib, RedProtect, RePlant, SimpleUtils, SkinsRestorer, sleep-most, Slimefun, SlimefunLuckyBlocks, SlimeHUD [10:14:20 INFO]:  SlimyTreeTaps, SoulJars, StreamingDrops, Themis, TradeSystem, *UnbreakableAnvils, UTitleAuth, ViaBackwards, ViaVersion, VillagerUtil [10:14:20 INFO]:  voicechat, WorldEdit, WorldGuard

### Server log

https://hastebin.com/share/wacivugazi.makefile

### Plugin version

FastLogin version 1.12-SNAPSHOT-971b0e1

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Duplicate of #998
