### ISSUE TITLE
java.lang.NoClassDefFoundError: org/sqlite/SQLiteConfig

### ISSUE THREAD

**Issue by DiffuseHyperion** [games647/FastLogin#1001]
### What happened?

When loading FastLoginVelocity on a velocity server, the following error is printed into the console:
```
[10:43:44 ERROR]: Couldn't pass ProxyInitializeEvent to fastlogin
java.lang.NoClassDefFoundError: org/sqlite/SQLiteConfig
        at com.github.games647.fastlogin.core.storage.SQLiteStorage.setParams(SQLiteStorage.java:64) ~[?:?]
        at com.github.games647.fastlogin.core.storage.SQLiteStorage.<init>(SQLiteStorage.java:49) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:234) ~[?:?]
        at com.github.games647.fastlogin.velocity.FastLoginVelocity.onProxyInitialization(FastLoginVelocity.java:96) ~[?:?]
        at com.github.games647.fastlogin.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.sqlite.SQLiteConfig
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
```

### What did you expect?

No errors to be printed, and the sqlite driver to be shaded into the plugin already.

### Steps to reproduce

1. Setup a velocity server
2. Install FastLoginVelocity into the plugins folder
3. Run the server

### Plugin list

fastlogin, authmevelocity, maintenance, skinsrestorer, vpacketevents, unsignedvelocity

### Configuration file

https://hastebin.com/share/cixasicofo.yaml

### Server log

https://hastebin.com/share/ariveqatak.markdown

### Plugin version

Build #1195

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
As mentioned in the setup guide. BungeeCord only includes a driver for MySQL/MariaDB. So you are required to use that database system.

**Comment by DiffuseHyperion** [comment]
Does the same apply to velocity? Plus, is there really no way to have sqlite working? I would definitely rather a file based storage system compared to having to host another database, adding to overhead. Even yaml works for me I guess

**Comment by games647** [comment]
I think that would be a bad idea, because mainly it makes harder to upgrade the server software. Besides, MySQL/MariaDB is usually performs better if you have more users which could be the case if you are managing a multi server network.
