### ISSUE TITLE
ProtocolLibListener tried to access private method 'boolean'

### ISSUE THREAD

**Issue by ApliNi** [games647/FastLogin#1008]
### What happened?

An error occurred when the player joined, no automatic login, no genuine UUID

### Steps to reproduce

1. Install `ProtocolLib version 5.0.0-SNAPSHOT-b625` in version 1.19.4
2. Install `AuthMe, FastLogin`
3. players join

### Plugin list

AuthMe, FastLogin, ProtocolLib

### Configuration file

I also tested the default configuration, the problem still persists

### Server log

Starting org.bukkit.craftbukkit.Main
System Info: Java 19 (OpenJDK 64-Bit Server VM 19.0.1+10) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[17:13:27 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:13:28 INFO]: Loaded 7 recipes
[17:13:29 INFO]: Starting minecraft server version 1.19.4
[17:13:29 INFO]: Loading properties
[17:13:29 INFO]: This server is running Purpur version git-Purpur-1949 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f5a789d on HEAD)
[17:13:29 INFO]: Server Ping Player Sample Count: 12
[17:13:29 INFO]: Using 4 threads for Netty based IO
[17:13:29 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[17:13:30 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[17:13:30 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[17:13:30 INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[17:13:30 INFO]: Default game type: SURVIVAL
[17:13:30 INFO]: Generating keypair
[17:13:30 INFO]: Starting Minecraft server on *:25565
[17:13:30 INFO]: Using default channel type
[17:13:30 INFO]: Paper: Using Java compression from Velocity.
[17:13:30 INFO]: Paper: Using Java cipher from Velocity.
[17:13:30 INFO]: [FastLogin] Initialize logging service
[17:13:30 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.0.0-SNAPSHOT-b625
[17:13:31 INFO]: [AuthMe] Loading server plugin AuthMe v5.6.0-beta2-b2453
[17:13:31 INFO]: [FastLogin] Loading server plugin FastLogin v1.12-SNAPSHOT-a50f8b7
[17:13:31 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:13:31 INFO]: [ProtocolLib] Enabling ProtocolLib v5.0.0-SNAPSHOT-b625
[17:13:31 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[17:13:31 WARN]: The server will make no attempt to authenticate usernames. Beware.
[17:13:31 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[17:13:31 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[17:13:31 INFO]: Preparing level "world"
[17:13:32 INFO]: Preparing start region for dimension minecraft:overworld
[17:13:32 INFO]: Time elapsed: 102 ms
[17:13:32 INFO]: Preparing start region for dimension minecraft:the_nether
[17:13:32 INFO]: Time elapsed: 35 ms
[17:13:32 INFO]: Preparing start region for dimension minecraft:the_end
[17:13:32 INFO]: Time elapsed: 30 ms
[17:13:32 INFO]: [AuthMe] Enabling AuthMe v5.6.0-beta2-b2453
[17:13:32 INFO]: [AuthMe] SQLite Setup finished
[17:13:32 INFO]: [AuthMe] No supported permissions system found! Permissions are disabled!
[17:13:33 INFO]: [AuthMe] AuthMe 5.6.0-beta2 build n.2453 successfully enabled!
[17:13:33 INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-a50f8b7
[17:13:33 WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.
[17:13:33 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Starting...
[17:13:33 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Start completed.
[17:13:33 INFO]: Running delayed init tasks
[17:13:33 INFO]: [AuthMe] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[17:13:33 INFO]: Done (4.320s)! For help, type "help"
[17:13:33 WARN]: [AuthMe] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[17:13:33 INFO]: [AuthMe] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[17:13:33 WARN]: [AuthMe] Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
[17:13:33 INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook
[17:13:49 INFO]: [FastLogin] New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@2ee7849e
[17:13:49 ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
java.lang.IllegalAccessError: class com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener tried to access private method 'boolean com.comphenix.protocol.utility.MinecraftVersion.atOrAbove(com.comphenix.protocol.utility.MinecraftVersion)' (com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener is in unnamed module of loader 'FastLoginBukkit.jar' @6ee2fecc; com.comphenix.protocol.utility.MinecraftVersion is in unnamed module of loader 'ProtocolLib.jar' @726f278a)
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onLoginStart(ProtocolLibListener.java:227) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:149) ~[FastLoginBukkit.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:625) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:579) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:48) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:223) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:292) ~[ProtocolLib.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1949]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1949]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[17:13:49 INFO]: UUID of player ApliNi is a1d1c2cd-42e5-394d-961a-8ee6680df4f8
[17:13:49 INFO]: ApliNi joined the game
[17:13:49 INFO]: ApliNi[/127.0.0.1:4884] logged in with entity id 156 at ([world]-5.699999988079071, 0.0, -674.3000000119209)
[17:13:50 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=ApliNi} with ID 127.0.0.1:4884.
[17:13:50 INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received
>

### Plugin version

1.12-SNAPSHOT-a50f8b7

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Looks like ProtocolLib made another breaking change. I'll fix it.
