### ISSUE TITLE
Unknown initial character set index '255' received from server.

### ISSUE THREAD

**Issue by akillamrck** [games647/FastLogin#1009]
### What happened?

java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.configureClientCharacterSet(ConnectionImpl.java:1794) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3523) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2386) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at fastlogin.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) [FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) [FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:115) [FastLoginBukkit.jar:?]
	at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81) [FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:83) [FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:35) [FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:238) [FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:111) [FastLoginBukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[05:33:24] [Server thread/ERROR]: Error occurred while enabling FastLogin v1.11-a9e4c90 (Is it up to date?)
fastlogin.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
	at fastlogin.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:83) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:35) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:238) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:111) ~[FastLoginBukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.configureClientCharacterSet(ConnectionImpl.java:1794) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3523) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2386) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at fastlogin.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[FastLoginBukkit.jar:?]
	... 17 more

### Configuration file

https://gist.github.com/akillamrck/df75f200f80212eedd426f4a3195c6f9

### Server log

https://gist.github.com/akillamrck/69f1691f849988db443b531b3ebcc49d

### Plugin version

FastLogin v1.11-a9e4c90

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
This could be related to an outdated driver in your server version in combination with your database server. Please check the database version.

**Comment by akillamrck** [comment]
version                  | 8.0.32-0ubuntu0.22.04.2

**Comment by akillamrck** [comment]
hi?

**Comment by games647** [comment]
Could you try to downgrade the MySQL instance for a test?

**Comment by akillamrck** [comment]
It's that fastlogin works fine for me in java 8. What happens is that I'm using java 11 on that server

**Comment by games647** [comment]
AFAIK Java changed the default character encoding so yes that could be related. Please test the different MySQL/MariaDB version. Another solution is to upgrade the MySQL driver embedded into Spigot. However, this is part of Spigot.

**Comment by games647** [comment]
It's normally not intended to do it manually, so I recommended the downgrade. Furthermore, it is very complex.

1. Download the connector from MySQL: https://dev.mysql.com/downloads/connector/j/
2. Open spigot with an archiver program
3. Remove com/mysql
4. Copy the contents from the jar file in the connector archive inside spigot
