### ISSUE TITLE
Unhandled exception occurred in onAsyncPacket() for FastLogin

### ISSUE THREAD

**Issue by Hanmingxuan** [games647/FastLogin#1013]
### What happened?

can't auto login

### Plugin list

, AuthMe, Chunky, CMI, CMILib, CoreProtect, PlaceholderAPI,  ProtocolLib,  Residence,  Vault ViaBackwards, ViaVersion, WorldBorder, WorldEdit, WorldEdit, WorldEditSUI, WorldGuard

### Configuration file

https://lanxing.vip:1443/purpur/plugins/FastLogin/config.yml

### Server log

16:11:32] [Protocol Worker #1 - FastLogin - [recv: ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], send: ]/INFO]: [FastLogin] New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@366ca3f1
[16:11:32] [Protocol Worker #1 - FastLogin - [recv: ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], send: ]/ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
java.lang.IllegalAccessError: class com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener tried to access private method 'boolean com.comphenix.protocol.utility.MinecraftVersion.atOrAbove(com.comphenix.protocol.utility.MinecraftVersion)' (com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener is in unnamed module of loader 'FastLoginBukkit.jar' @2940b11f; com.comphenix.protocol.utility.MinecraftVersion is in unnamed module of loader 'ProtocolLib#627.jar' @36e1379b)
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onLoginStart(ProtocolLibListener.java:227) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:149) ~[FastLoginBukkit.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:625) ~[ProtocolLib#627.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:579) ~[ProtocolLib#627.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:48) ~[ProtocolLib#627.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:223) ~[ProtocolLib#627.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:292) ~[ProtocolLib#627.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-484]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-484]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:11:32] [User Authenticator #3/INFO]: UUID of player MC_Mingxuan is 449a25f0-0a08-3e9a-8c46-f4fcd6c071c7
[16:11:32] [Server thread/INFO]: MC_Mingxuan joined the game
[16:11:32] [Server thread/INFO]: MC_Mingxuan[/223.97.48.147:8130] logged in with entity id 446 at ([world]100.5, 62.9375, 28.5)
[16:11:32] [Server thread/INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=MC_Mingxuan} with ID 223.97.48.147:8130. 
[16:11:32] [Server thread/INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received
[16:11:37] [Server thread/INFO]: MC_Mingxuan lost connection: Disconnected
[16:11:37] [Server thread/INFO]: MC_Mingxuan left the game

### Plugin version

1.12-SNAPSHOT-42911e9

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Hanmingxuan** [comment]
OK！

**Comment by spiceminecraft** [comment]
I'm having this issue too!
