### ISSUE TITLE
Help me with this error

### ISSUE THREAD

**Issue by VentureStudios** [games647/FastLogin#1027]
### What happened?

Hi, I saw a youtube video on how to set up this plugin, but it gave me an error

### Steps to reproduce

[20:53:53 ERROR]: [FastLogin] Failed to retrieve proxy Id. Disabling BungeeCord support
java.lang.IllegalArgumentException: UUID string too large
        at java.util.UUID.fromString1(UUID.java:264) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.nio.file.FileChannelLinesSpliterator.forEachRemaining(FileChannelLinesSpliterator.java:133) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.github.games647.fastlogin.bukkit.BungeeManager.loadBungeeCordIds(BungeeManager.java:186) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.BungeeManager.initialize(BungeeManager.java:96) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:106) ~[FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

This is problem on spigot backend

### Plugin list

Bungeeutilisalsx, botsentry, bungeereourcepacks, bungeeonlinetime, safenet, vulcanbungee, csf-bungee, skinrestorer, luckperms, maintenance

### Configuration file

https://hastebin.skyra.pw/vizudemeho.yaml

### Server log

https://hastebin.skyra.pw/jobawugibe.prolog

### Plugin version

Build #1241 (Sat Apr 15 23:32:10 UTC 2023)

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
The id you entered in the proxy list is too large. Please verify that this valid UUID number.
