### ISSUE TITLE
KCauldron 1.7 Error on load

### ISSUE THREAD

**Issue by TheProKiller756** [games647/FastLogin#104]
Hi, I recently downloaded your plugin and i was trying to load it and i had this error: 
`[22:33:54] [Server thread/ERROR]: Could not load 'plugins/FastLogin.jar' in folder 'plugins'

org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/github/games647/fastlogin/bukkit/EncryptionUtil

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]

	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]

	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]

	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]

	at net.minecraft.world.WorldServer.<init>(WorldServer.java:160) [mt.class:?]

	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]

	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Caused by: java.lang.NoClassDefFoundError: com/github/games647/fastlogin/bukkit/EncryptionUtil

	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.<init>(FastLoginBukkit.java:38) ~[?:?]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_72]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_72]

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_72]

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_72]

	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_72]

	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]

	... 11 more

Caused by: java.lang.ClassNotFoundException: Failed to remap class com.github.games647.fastlogin.bukkit.EncryptionUtil

	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]

	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.<init>(FastLoginBukkit.java:38) ~[?:?]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_72]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_72]

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_72]

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_72]

	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_72]

	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]

	... 11 more

Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5

	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]

	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]

	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]

	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]

	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]

	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]

	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]

	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:453) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]

	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.<init>(FastLoginBukkit.java:38) ~[?:?]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_72]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_72]

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_72]

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_72]

	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_72]

	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]

	... 11 more`

I'm usin KCauldron for the 1.7 Version (1647.201 ) With Authme Thanks

**Comment by Eufranio** [comment]
The **SpecialSource** library included with Thermos uses ASM4.
Updating it to the latest version will fix the issue.

Instructions for updating to ASM5:
1. Navigate to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder of the server
2. Delete the SpecialSource-1.7-SNAPSHOT.jar jar file
3. Download SpecialSource v1.7.4 from http://central.maven.org/maven2/net/md-5/SpecialSource/1.7.4/SpecialSource-1.7.4.jar
4. Copy the jar file to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder
5. Rename the jar file you just copied to SpecialSource-1.7-SNAPSHOT.jar

**Comment by TheProKiller756** [comment]
Thanks you so much, this worked :D

**Comment by games647** [comment]
Related to #84 and CyberdyneCC/Thermos#498
