### ISSUE TITLE
welp

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#105]
This morning, my Bungee started throwing errors at the FastLogin startup, and now all my players are getting a offline uuid 😢 

```
01:31:04 [FINE] [FastLogin] Error dropping unique uuid index
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Can't DROP 'UUID'; check that column/key exists
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at com.github.games647.fastlogin.core.AuthStorage.createTables(AuthStorage.java:95)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:118)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:44)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
01:31:04 [FINE] [FastLogin] Error creating uuid index
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate key name 'uuid_idx'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at com.github.games647.fastlogin.core.AuthStorage.createTables(AuthStorage.java:102)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:118)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:44)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)```

**Comment by games647** [comment]
Do you renamed a column?

**Comment by Eufranio** [comment]
Nope

**Comment by games647** [comment]
It's fine. So it's just debug code

**Comment by Eufranio** [comment]
That's how the table is:

![mysql](http://image.prntscr.com/image/afc5f00e0a0843159ba7512b541fa11c.png)

**Comment by games647** [comment]
You can ignore it. There is no platform independent way for checking for indexes, so it creates errors.

**Comment by games647** [comment]
And check if it's the correct error and for debug reasons it prints it.

For premium UUID you should activate debug logging in Spigot and login with a premium account

**Comment by Eufranio** [comment]
FastLogin isn't working and that's the only error that appears to be in the console. Whenever I try to use the /premium or /cracked command, it says 'An request was sent to bungeecord, waiting...' and nothing more happens...

**Comment by games647** [comment]
That means the bungee module doesn't respond. You have to connect through BungeeCord and then invoke the command.

**Comment by Eufranio** [comment]
Looks like it cant send the request to bungee, I dont know why... My players and other plugins seems to be able, only FastLogin isn't working

**Comment by games647** [comment]
Please post your log of both servers and the output of the command as a picture.

**Comment by Eufranio** [comment]
```
01:43:42 [WARNING] Exception encountered when loading plugin: FastLogin
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Access denied for user 'root'@'127.0.0.1' (using password: YES)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
	at com.github.games647.fastlogin.core.AuthStorage.<init>(AuthStorage.java:48)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:116)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:44)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.sql.SQLException: Access denied for user 'root'@'127.0.0.1' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
	... 9 more
```

**Comment by Eufranio** [comment]
This error is fro bungee, but other plugins sees to be able to connect to the MySQL server...

**Comment by Eufranio** [comment]
Okay the problem was that by some reason my server stopped connecting with my MySQL server trough `localhost`, and the problem wasn't FastLogin, thanks for your help
