### ISSUE TITLE
Fastlogin db working on hub but not proxy

### ISSUE THREAD

**Issue by akuachi** [games647/FastLogin#1058]
### What happened?

09:58:59 INFO] [FastLogin]: Initialize logging service
[09:58:59 ERROR] [fastlogin.hikari.HikariConfig]: Failed to load driver class fastlogin.mariadb.jdbc.Driver from HikariConfig class classloader PluginClassloader(desc=PluginDescription(name=FastLogin, main=com.github.games647.fastlogin.bungee.FastLoginBungee, version=1.12-SNAPSHOT-5cd10fd, author=games647, https://github.com/games647/FastLogin/graphs/contributors, depends=[], softDepends=[BungeeAuth, BungeeCordAuthenticatorBungee, SodionAuth, Geyser-BungeeCord, floodgate], file=plugins/FastLoginBungee.jar, description=Automatically login premium (paid accounts) player on an offline mode server
, libraries=[]))
[09:58:59 WARN]: Exception encountered when loading plugin: FastLogin
java.lang.RuntimeException: Failed to load driver class fastlogin.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at fastlogin.hikari.HikariConfig.setDriverClassName(HikariConfig.java:491) ~[?:?]
        at com.github.games647.fastlogin.core.storage.MySQLStorage.setParams(MySQLStorage.java:51) ~[?:?]
        at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:40) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:250) ~[?:?]
        at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:86) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:357) ~[Mangocord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:44191af:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:311) ~[Mangocord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:44191af:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52) ~[Mangocord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:44191af:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Mangocord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:44191af:unknown]

### What did you expect?

I expected the database to work because on the Hub server there's no error and the config is litteraly the same, only with the proxy id

### Steps to reproduce

I just setted the plugin for the first time so there notthing to reproduce

### Plugin list

TCPShield-2.6.1.jar Social-1.2.3.jar SkinsRestorer.jar Maintenance-4.1.0.jar LuckPerms-Bungee-5.4.98.jar HubMagic-LATEST-[0.2.6].jar FastLoginBungee.jar BungeeGuard-LATEST-[1.3.3].jar BungeecordPartyAndFriends-1.0.91.jar AuthMeBungee-2.2.0-SNAPSHOT.jar "AdvancedNMotd-9.2.0 (1).jar"

### Configuration file

https://hastebin.com/share/ehizetehuw.yaml

### Server log

https://hastebin.com/share/afujoyalut.makefile

### Plugin version

All the final snapshot 

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by siBalda** [comment]
I have a similar error, but you have been waiting 5 days.. let's see if someone helps us

**Comment by games647** [comment]
Your driver name is incorrect. The class name you entered doesn't exist in either FastLogin or BungeeCord. Please use 'mysql' an alias for 'com.mysql.cj.jdbc.Driver'. This driver is available by BungeeCord.
