### ISSUE TITLE
NoClassDefFoundError: me/clip/placeholderapi/PlaceholderHook

### ISSUE THREAD

**Issue by DanielRamosAcosta** [games647/FastLogin#108]
When a premium user joins, I'm getting a strange issue, and it doesn't auto-logins them or use their skin:

```
[16:59:37 ERROR]: [FastLogin] Failed to query profile
java.sql.SQLException: Error parsing time stamp
        at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:565) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProxyResultSet.java) ~[FastLogin.jar:?]
        at com.github.games647.fastlogin.core.AuthStorage.loadProfile(AuthStorage.java:129) [FastLogin.jar:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:21) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:38) [FastLogin.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-7d78b81-7e19325]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.text.ParseException: Unparseable date: "2017-01-07 16:58:54" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\
Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
        at org.sqlite.date.FastDateParser.parse(FastDateParser.java:299) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.sqlite.date.FastDateFormat.parse(FastDateFormat.java:490) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:562) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        ... 9 more
```

**Comment by Eufranio** [comment]
What's the version of your FastLogin (or at lease where did you download it)?

**Comment by DanielRamosAcosta** [comment]
I downloaded from [here](https://www.spigotmc.org/resources/fastlogin.14153/),

**Comment by Eufranio** [comment]
Download the latest dev build from the [FastLogin Jenkins](http://ci.xephi.fr/job/FastLogin/) and your issue should be fixed.

**Comment by DanielRamosAcosta** [comment]
Thanks for your fast reponse! 😄 , but now I'm getting this error when the plugin starts loading:

```
[17:29:56 ERROR]: Could not load 'plugins\FastLogin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderHook
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot.jar:git-Spigot-7d78b81-7e19325]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-7d78b81-7e19325]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot.jar:git-Spigot-7d78b81-7e19325]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderHook
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.PlaceholderHook
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-7d78b81-7e19325]
        ... 6 more
```

**Comment by Eufranio** [comment]
Try downloading PlaceholderAPI from [here](https://www.spigotmc.org/resources/placeholderapi.6245/) and see if FastLogin will start. It shouldn't be stopped by PlaceholderAPI tho...

**Comment by DanielRamosAcosta** [comment]
Yep, it was that, now works like a charm. Thanks a lot!!
