### ISSUE TITLE
Error about mysql driver

### ISSUE THREAD

**Issue by youguo** [games647/FastLogin#1093]
### What happened?

I runned a server as usual but encountered this problem......
I have not changed anything about this plugin. Could you help me, please?

[16:13:04 ERROR]: Failed to load driver class com.mysql.cj.jdbc.Driver from HikariConfig class classloader org.bukkit.plugin.java.PluginClassLoader@4bc33850
[16:13:04 ERROR]: Error occurred while enabling FastLogin v1.12-SNAPSHOT-d76690d (Is it up to date?)
java.lang.RuntimeException: Failed to load driver class com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at fastlogin.hikari.HikariConfig.setDriverClassName(HikariConfig.java:491) ~[?:?]
        at com.github.games647.fastlogin.core.storage.MySQLStorage.setParams(MySQLStorage.java:47) ~[?:?]
        at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:40) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:250) ~[?:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:109) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131] 

### Plugin version

lastest

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Could you please try `com.mysql.jdbc.Driver` in the driver setting?

**Comment by youguo** [comment]
> Could you please try `com.mysql.jdbc.Driver` in the driver setting?

should I modify the source code and rebuild a jar?

**Comment by youguo** [comment]
Actually I know the problem but I don't know what cause it. 

Where should I change the driver setting, source code or other places?

**Comment by games647** [comment]
No inside the configuration file.

**Comment by youguo** [comment]
I just changed com.github.games647.fastlogin.core.storage.MySQLStorage.java:

private static final String MYSQL_DRIVER = "com.mysql.cj.jdbc.Driver";
to
private static final String MYSQL_DRIVER = "com.mysql.jdbc.Driver";

The problem is solved. Thank you!
