### ISSUE TITLE
An error occurred while starting fastlogin with Velocity

### ISSUE THREAD

**Issue by Morax-Lizho** [games647/FastLogin#1104]
### What happened?

An error occurs:
[19:33:13 INFO] [fastlogin.hikari.HikariDataSource]: fastlogin - Starting...
[19:33:13 INFO] [fastlogin.hikari.HikariDataSource]: fastlogin - Start completed.
[19:33:13 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[19:33:13 ERROR]: #1:

java.lang.NoClassDefFoundError: com/velocitypowered/api/event/Continuation
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter.findSubscribers(SimpleMethodSubscriptionAdapter.java:73) ~[velocity-1.1.9.jar:1.1.9]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter.register(SimpleMethodSubscriptionAdapter.java:63) ~[velocity-1.1.9.jar:1.1.9]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.register(VelocityEventManager.java:109) ~[velocity-1.1.9.jar:1.1.9]
        at com.github.games647.fastlogin.velocity.FastLoginVelocity.onProxyInitialization(FastLoginVelocity.java:99) ~[?:?]
        at net.kyori.event.asm.generated.dd85713f6d.FastLoginVelocity-onProxyInitialization-ProxyInitializeEvent-3.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity-1.1.9.jar:1.1.9]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity-1.1.9.jar:1.1.9]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154) ~[velocity-1.1.9.jar:1.1.9]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136) ~[velocity-1.1.9.jar:1.1.9]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.api.event.Continuation
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83) ~[velocity-1.1.9.jar:1.1.9]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60) ~[velocity-1.1.9.jar:1.1.9]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 16 more

### What did you expect?

Resolve the error and fix the bug

### Steps to reproduce

1.Install fastlogin version 1.1 on Velocity and modify the configuration file
2.Start Velocity.

### Plugin list

fastloginVelocity, authmeVelocity

### Configuration file

https://hastebin.com/share/fovoxemeki.yaml

### Server log

https://hastebin.com/share/dozunenobu.markdown

### Plugin version

v1.1

### Platform

Velocity

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by galacticwarrior9** [comment]
Why are you using Velocity 1.1.9? 

FastLogin is only compatible with Velocity 3.x.

**Comment by Morax-Lizho** [comment]
Thank you, I did fix this issue after changing to version 3.2.
