### ISSUE TITLE
Authenticated, but UserLogin keeps telling me to Log In.

### ISSUE THREAD

**Issue by Tomasekg15** [games647/FastLogin#1135]
### What happened?

I run an Arclight 1.20.1 server (mods and plugins) with the latest version of UserLogin and FastLogin. I add myself onto the premium list, reconnect and while in the loading screen I see "Encrypting..." and see the player head icons in tablist... however I am not logged in and still need to manually log in with my password.
![image](https://github.com/games647/FastLogin/assets/62138046/ffe753ba-f9ac-4a51-8394-d222a44e7537)

### Steps to reproduce

Start a server with the latest version of Arclight for 1.20.1 with FastLogin and UserLogin
Try to use FastLogin as intended.

### Plugin list

MiniMOTD, CoreProtect, LuckPerms, BlueMap, ColoredSigns, OpenInv, PlaceholderAPI, WhitelistByTime, NametagEdit, CoreProtectTNT, HostifyMonitor, ProtocolLib, SkinsRestorer, Maintenance, CoordinatesHud, Orebfuscator, StopNetherTrap, GSit, NBTAPI, Vault, ColoredAnvils, MyCommand, LogFilter, AureliumSkills, FastLogin, ChatColor2, VaultChatFormatter, VeinMiner, Simple-Drugs, PiggyBank, UserLogin, Brewery, EzChestShop, TabList

### Configuration file

https://gist.github.com/Tomasekg15/47a8a3af79fa8be5dc6d3a907f821b3a

### Plugin version

1.12-SNAPSHOT-cd67797

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Please post the server log from that timestamp.

**Comment by Tomasekg15** [comment]
Is it okay if I just send a part when the player is joining? I do not want to send the log with the IPs, and it is quite long...

`[03led2024 15:46:35.582] [Protocol Worker #1 - FastLogin - [recv: START[class=PacketLoginInStart, id=0], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], send: ]/INFO] [FastLogin/]: New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@22192a97
[03led2024 15:46:35.646] [Craft Scheduler Thread - 3/INFO] [FastLogin/]: Handling player Tomasekg
[03led2024 15:46:35.664] [Craft Scheduler Thread - 3/INFO] [FastLogin/]: Requesting premium login for registered player: Tomasekg
[03led2024 15:46:36.313] [Protocol Worker #1 - FastLogin - [recv: START[class=PacketLoginInStart, id=0], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], send: ]/INFO] [FastLogin/]: New packet ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@22192a97
[03led2024 15:46:36.344] [Craft Scheduler Thread - 3/INFO] [FastLogin/]: Enabling onlinemode encryption for /IP
[03led2024 15:46:36.540] [Craft Scheduler Thread - 3/INFO] [FastLogin/]: Profile Tomasekg has a verified premium account
[03led2024 15:46:36.567] [User Authenticator #1/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: UUID of player Tomasekg is 2d0afe5e-b9c2-3ca7-b5e1-3991f770a16d
[03led2024 15:46:42.142] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: Tomasekg[/IP] logged in with entity id 51 at (-28.30000001192093, 85.0, -210.30000001192093)
[03led2024 15:46:42.275] [ForkJoinPool.commonPool-worker-2/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent org/bukkit/metadata/MetadataValueAdapter for class org/bukkit/metadata/LazyMetadataValue in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902 on thread Thread[ForkJoinPool.commonPool-worker-2,5,SERVER]
[03led2024 15:46:42.275] [ForkJoinPool.commonPool-worker-2/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: org.bukkit.metadata.MetadataValueAdapter
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin}
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar%2386!/:6.0.5+6.0.5+master.eb8e549b] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2389!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2389!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2389!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin}
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:104) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin}
	at wtf.choco.veinminer.listener.PlayerDataListener.lambda$onPlayerJoin$2(PlayerDataListener.java:40) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
[03led2024 15:46:42.290] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Tomasekg joined the game`

**Comment by games647** [comment]
Yes, we only need that part. However, a little more is needed after that. FastLogin sends the force login delayed after the player fully joined in / is initialized.

**Comment by Tomasekg15** [comment]
Okay, I grabbed this bit from another log, since that one ended right there (the server was shut offline)...
So here is another bit of a server log with a bit more as you asked
[fast login log 2.txt](https://github.com/games647/FastLogin/files/14114075/fast.login.log.2.txt)

**Comment by games647** [comment]
Mhm, the messages during play state (minecraft term for finished login process) are still missing. Could you check for any log messages like: `Logging player ... in`, `No valid session found for` or `Player {} disconnected`.
