### ISSUE TITLE
Error with enabling plugin

### ISSUE THREAD

**Issue by MrDrag0nXYT** [games647/FastLogin#1137]
### What happened?

While plugin starts, it generates exception:
```java.lang.NoSuchMethodError: 'org.geysermc.geyser.session.auth.AuthType org.geysermc.geyser.configuration.GeyserConfiguration$IRemoteConfiguration.getAuthType()'```

Config files wasn't edited

### Versions:
- FastLogin: 1.11-a9e4c90
- Server: Purpur 1.18.2 (git-Purpur-1632 (MC: 1.18.2))
- AuthMeReloaded: 5.6.0-beta2-b2453
- Geyser: 2.2.0-SNAPSHOT (git-master-cdb8ab3)
- floodgate: 2.2.2-SNAPSHOT (b85-71acc6c)

### What did you expect?

That plugin will run

### Steps to reproduce

Start server with Purpur 1.18.2 (git-Purpur-1632), AuthMeReloaded (5.6.0-beta2-b2453), Geyser (git-master-cdb8ab3) and floodgate (b85-71acc6c)

### Plugin list

AdvancedPortals, AfkPool, ajLeaderboards, AuthMe, BAirDrop, BetterRTP, BKCommonLib, BlueSlimeCore, Coins, CombatLogX, DecentHolograms, DeluxeMenus, DonateCase, Essentials, EssentialsSpawn, ExcellentEnchants, FastLogin, FlectoneChat, floodgate, Geyser-Spigot, ItemEdit, ItemJoin, LuckPerms, MiniMOTD, My_Worlds, MyCommand, NexEngine, NotBounties, Oraxen, PlaceholderAPI, PlayerAuctions, PlayerParticles, PlayerPoints, PlugManX (PlugMan), ProtectAddon, ProtectionStones, ProtocolLib, SkinsRestorer, Skript, TAB, TigerReports, TradeSystem, Vault, ViaVersion, VoidSpawn, WorldEdit, WorldGuard, ZNPCsPlus

### Configuration file

(default)

### Server log

```[09:13:09 ERROR]: Error occurred while enabling FastLogin v1.11-a9e4c90 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.geysermc.geyser.session.auth.AuthType org.geysermc.geyser.configuration.GeyserConfiguration$IRemoteConfiguration.getAuthType()'
        at com.github.games647.fastlogin.core.hooks.bedrock.GeyserService.<init>(GeyserService.java:47) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.initializeFloodgate(FastLoginBukkit.java:171) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:100) ~[FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:428) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:385) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.reload(BukkitPluginUtil.java:500) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:125) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[09:13:09 INFO]: [FastLogin] Disabling FastLogin v1.11-a9e4c90```

### Plugin version

1.11-a9e4c90

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by omerien** [comment]
did you close this on purpose?
