### ISSUE TITLE
java.lang.IllegalArgumentException: Channel must contain : separator

### ISSUE THREAD

**Issue by LiuBryson** [games647/FastLogin#1154]
### What happened?

```
[00:41:14 INFO]: [FastLogin] Enabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432*
[00:41:14 ERROR]: Error occurred while enabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use FastLogin)
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:216) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:72) ~[FastLogin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[00:41:14 INFO]: [FastLogin] Disabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432
```

### What did you expect?

Enable this plugin on pupur

### Steps to reproduce

1.17.1
ProxyMode(Waterfall)

### Plugin list

AuthMe, BlockLocker, CMI, CMILib, CoreProtect, dynmap, FastLogin*, HuskHomes, HuskHomesGUI, LuckPerms, PlayerTitle, PlugManX (PlugMan), ProtocolLib, SimpleTpa, SkinsRestorer, ViaBackwards, ViaVersion

### Plugin version

v1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version. Please read the checklist for a link to the latest build.
