### ISSUE TITLE
NoSuchMethodError with arclight server

### ISSUE THREAD

**Issue by VTSTG233** [games647/FastLogin#1159]
### What happened?

Problem Description:
  When attempting to auto-login premium players using FastLogin with AuthMe integration, the process fails despite FastLogin successfully identifying the player as premium. The server logs indicate a `NoSuchMethodError` exception related to online mode encryption.

### What did you expect?

Expected Behavior:
  Premium players should be automatically logged in without issues.

### Steps to reproduce

Steps to Reproduce:
  1. Configure FastLogin and AuthMe on the server.
  2. Enable auto-login for premium players in FastLogin configuration.
  3. Premium player attempts to login.
  4. Observe the server log for errors.
Server and Plugin Versions:
  - Minecraft Server version: (e.g., arclight-1.20.1-1.0.4-fd335c1)
  - FastLogin version: (e.g., v1.12-SNAPSHOT-a65a5f39)
  - AuthMe version: (e.g., 5.6.0-SNAPSHOT-b2434)

### Plugin list

AuthMe-5.6.0-SNAPSHOT / FastLoginBukkit v1.12-SNAPSHOT-a65a5f3 / ProtocolLib5.1.0

### Configuration file

https://gist.github.com/VTSTG233/c4d1c2855b7139d6291fc129a57708aa.js

### Server log

[03:06:14 INFO]: Done (7.107s)! For help, type "help"
[03:06:14 INFO]: Successfully initialized permission handler forge:default_handler
[03:06:14 INFO] [Arclight]: Forwarding forge permission[forge:default_handler] to bukkit
[03:06:14 INFO] [AuthMe]: Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[03:06:14 WARN] [AuthMe]: No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[03:06:14 INFO] [AuthMe]: There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[03:06:14 WARN] [AuthMe]: Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
[03:06:15 INFO] [FastLogin]: Hooking into auth plugin: AuthMeHook
[03:06:19 INFO] [FastLogin]: New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@3ffc5a76
[03:06:19 INFO] [FastLogin]: Handling player VTSTG233
[03:06:19 INFO] [FastLogin]: Player VTSTG233 will be migrated to the v2 database schema as a JAVA user
[03:06:19 INFO] [FastLogin]: Requesting premium login for registered player: VTSTG233
[03:06:20 INFO] [FastLogin]: New packet ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@3ffc5a76
[03:06:20 INFO] [FastLogin]: Enabling onlinemode encryption for /127.0.0.1:49856
[03:06:21 INFO] [FastLogin]: Profile VTSTG233 has a verified premium account
[03:06:21 INFO]: UUID of player VTSTG233 is 76257863-44f2-31a8-aad1-8cccaa803bd3
[03:06:21 INFO]: VTSTG233[/127.0.0.1:49856] logged in with entity id 214 at (-5.666421976308313, 78.0, 104.56231604645508)
[03:06:21 INFO]: VTSTG233 joined the game
[03:06:21 WARN] [FastLogin]: Task #12 for FastLogin v1.12-SNAPSHOT-a65a5f3 generated an exception
java.lang.NoSuchMethodError: 'java.net.SocketAddress net.minecraft.server.network.ServerGamePacketListenerImpl.getRawAddress()'
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$1.getRawAddress(CraftPlayer.java:2159) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23163!/:arclight-1.20.1-1.0.4-fd335c1]
        at com.github.games647.fastlogin.bukkit.listener.ConnectionListener.delayForceLogin(ConnectionListener.java:82) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.ConnectionListener.lambda$onPlayerJoin$0(ConnectionListener.java:72) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23163!/:arclight-1.20.1-1.0.4-fd335c1]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23163!/:arclight-1.20.1-1.0.4-fd335c1]
        at net.minecraft.server.MinecraftServer.handler$zbb000$arclight$runScheduler(MinecraftServerMixin.java:2309) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Plugin version

v1.12-SNAPSHOT-a65a5f3

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [ ] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
It's a bug in your server software about a missing functionality.
