### ISSUE TITLE
NullPointerException on load

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#118]
When the plugin loads, it throws this NPE and disables:
```
java.lang.NullPointerException
	at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:127) ~[?:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:57) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92-internal]
```

**Comment by Eufranio** [comment]
Nevermind, ProtocolLib didn't start correctly.

**Comment by Eufranio** [comment]
Nope, now it works and FastLogin still now working :|

**Comment by games647** [comment]
Which build are you using?

**Comment by Eufranio** [comment]
Latest from Jenkins (downloaded in the moment that I posted this issue), can't find the version.

**Comment by games647** [comment]
Then there must be another error message before this one.

**Comment by Eufranio** [comment]
There isn't, there are no errors at all, even when starting the server with debug enabled. This error appears when the plugin is starting

**Comment by games647** [comment]
Could you please post your config.

**Comment by Eufranio** [comment]
The config is empty O.o
It created the file, but it's empty.

**Comment by Eufranio** [comment]
Deleting the FastLogin folder will make it create the folder/config again, and again empty.

**Comment by Eufranio** [comment]
Deleting the FastLogin folder will make it create the folder/config again, and again empty.

**Comment by games647** [comment]
It's not empty for me. Do you have any errors in the console?

**Comment by Eufranio** [comment]
No errors at all, only that one.

**Comment by games647** [comment]
Do you have any kind softlinks on the plugins folder?

**Comment by Eufranio** [comment]
I use the Pterodactyl Panel as server manager, and it DOES have permission to write. Other plugins generated the files right, including the server files itself, so I guess nothing is blocking FastLogin from write the files

**Comment by games647** [comment]
Try out this: https://github.com/games647/FastLogin/releases/tag/nio-debug

**Comment by Eufranio** [comment]
What should be displayed? I uploaded my config (from another server) and it worked, let me try to generate a new config...

**Comment by Eufranio** [comment]
Fixed. Are the jenkins builds outdated?

**Comment by games647** [comment]
It builds on AuthMe changes.
