### ISSUE TITLE
mariadb driver not working

### ISSUE THREAD

**Issue by zahadneokurkycz** [games647/FastLogin#1181]
### What happened?

It just crashes with this error: Failed to load driver class fastlogin.mariadb.jdbc.Driver from HikariConfig class classloader org.bukkit.plugin.java.PluginClassLoader

### What did you expect?

I expect it to load

### Plugin list

AuthMe-5.4.0, ViaVersion-4.9.3, FastLoginBukkit

### Configuration file

https://gist.github.com/zahadneokurkycz/b100aa2e850d4c4972a5e15f04a2e528

### Server log

https://gist.github.com/zahadneokurkycz/b100aa2e850d4c4972a5e15f04a2e528

### Plugin version

FastLogin v1.12-SNAPSHOT-a65a5f3

### Platform

Velocity

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
The database in Spigot/Paper configuration shouldn't load with Minecraft proxies. It couldn't detect that you are using velocity:

>[16:09:21 WARN]: [FastLogin] Cannot check for Velocity support in Paper
java.lang.NoSuchFieldException: velocitySupport
	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_401]
	at com.github.games647.fastlogin.bukkit.BungeeManager.isProxySupported(BungeeManager.java:110) ~[?:?]
	at com.github.games647.fastlogin.bukkit.BungeeManager.isVelocityEnabled(BungeeManager.java:127) ~[?:?]
	at com.github.games647.fastlogin.bukkit.BungeeManager.detectProxy(BungeeManager.java:148) ~[?:?]
	at com.github.games647.fastlogin.bukkit.BungeeManager.initialize(BungeeManager.java:92) ~[?:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:103) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.jar:git-Paper-173]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.jar:git-Paper-173]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-173]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[patched_1.13.jar:git-Paper-173]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-173]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_401]
[16:09:21 WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.

I only have access to Paper 1.13.2 and that field exists there. Is there any reason for using and older 1.13 version?

**Comment by zahadneokurkycz** [comment]
Yeah there was an problem with one plugin I wanted to add that doesn't work on newer versions but now I found replacement. Fastlogin works nice, but now it is forcing cracked players to join in premium way just because some premium player who was never on the server took their username. Even if I turned off autoregister and turned on secondattemptcracked
