### ISSUE TITLE
Premium command won't work.

### ISSUE THREAD

**Issue by omnidotnet** [games647/FastLogin#1190]
### What happened?

After using the /premium command AND confirming, I still need to log in. Running it again confirms I indeed am on the premium list. I also see a console error when joining.

### What did you expect?

To be able to autologin.

### Steps to reproduce

1. Try to log in as a premium user
2. Activate premium
3. Log out
4. See you still need to log in

### Plugin list

[16:59:55 INFO]: Server Plugins (23): [16:59:55 INFO]: Paper Plugins: [16:59:55 INFO]:  - Minepacks [16:59:55 INFO]: Bukkit Plugins: [16:59:55 INFO]:  - AuthMe, BetterStructures, CraftBook, dynmap, Essentials, FastAsyncWorldEdit, FastChunkPregenerator, *FastLogin, Geyser-Spigot, GSit [16:59:55 INFO]:  LuckPerms, ProtocolLib, Shopkeepers, SimpleTpa, spark, Towny, TownyChat, UltimateHomes, Vault, ViaBackwards [16:59:55 INFO]:  ViaVersion, WorldGuard

### Configuration file

https://gist.github.com/omnidotnet/5b60ee78bcaa944fb1bed6cdc10b906b

### Server log

[17:02:41 ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:244) ~[ProtocolLib.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onLogin(ProtocolLibListener.java:76) ~[FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:52) ~[FastLogin.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:622) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:576) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:221) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:290) ~[ProtocolLib.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-464]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-464]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]

### Plugin version

1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Please try the latest build mentioned in the checklist.

**Comment by omnidotnet** [comment]
Done, works.
