### ISSUE TITLE
NoClassDefFoundError: PlayerInjectionHandler with ProtocolLib builds 721+

### ISSUE THREAD

**Issue by rursache** [games647/FastLogin#1210]
### What happened?

```
[23:21:30 INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-829c70a
[23:21:30 WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.
[23:21:30 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Starting...
[23:21:30 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Start completed.
[23:21:31 ERROR]: Error occurred while enabling FastLogin v1.12-SNAPSHOT-829c70a (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/player/PlayerInjectionHandler
	at FastLoginBukkit.jar/com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.getHandler(ProtocolLibListener.java:302) ~[FastLoginBukkit.jar:?]
	at FastLoginBukkit.jar/com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.<init>(ProtocolLibListener.java:97) ~[FastLoginBukkit.jar:?]
	at FastLoginBukkit.jar/com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.register(ProtocolLibListener.java:104) ~[FastLoginBukkit.jar:?]
	at FastLoginBukkit.jar/com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:123) ~[FastLoginBukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.player.PlayerInjectionHandler
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 16 more
[23:21:31 INFO]: [FastLogin] Disabling FastLogin v1.12-SNAPSHOT-829c70a
[23:21:31 INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
[23:21:31 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Shutdown initiated...
[23:21:31 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Shutdown completed.
```

### Steps to reproduce

The crash happens when the server starts up.
Then all users will get "Error: this user is not whitelisted!"

All plugins are updated to the latest build as of this post!

### Plugin list

Admin-GUI ,  AuthMe ,  dynmap ,  FastChunkPregenerator ,  FastLogin ,  Hibernate ,  Multiverse-Core ,  Multiverse-Inventories ,  Multiverse-NetherPortals ,  Multiverse-SignPortals,  PlaceholderAPI ,  playit-gg ,  ProtocolLib ,  ServerListPlus ,  SkinsRestorer ,  ViaBackwards ,  ViaRewind ,  ViaVersion 

### Configuration file

https://pastebin.com/raw/4kzQ2Qaw

### Server log

see above

### Plugin version

AuthMe  version  5.6.0-SNAPSHOT-b2623 
ProtocolLib  version  5.3.0-SNAPSHOT-721 
FastLogin  version  1.12-SNAPSHOT-829c70a 

### Platform
Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### Relevance
- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Which ProtocolLib version do you use?

**Comment by rursache** [comment]
> Which ProtocolLib version do you use?

as stated, `ProtocolLib version 5.3.0-SNAPSHOT-721`

**Comment by games647** [comment]
Yeah looks like they removed the class in the newest commit. Please downgrade to a version before https://github.com/dmulloy2/ProtocolLib/commit/47bcd53fd02041b77800910bcabd4382075bed06. So for example dev build 720. I cannot fix it atm, because I'm only available on mobile.

**Comment by rursache** [comment]
thanks, using the [719 ](https://ci.dmulloy2.net/job/ProtocolLib/719/) build fixed it!
should i leave this issue open? seems like a fix is required on FastLogin side to support newer ProtocolLib versions

**Comment by AmZuppa** [comment]
does 720 work? @rursache i found out that 719 build got a big error that makes the server crash. they say it's fixed in build 720

**Comment by AmZuppa** [comment]
> does 720 work? @rursache i found out that 719 build got a big error that makes the server crash. they say it's fixed in build 720

update: ProtocolLib build 720 does work, and it should fix the crashes.
