### ISSUE TITLE
[1.21] If FastLogin is installed with Geyser, an error will be reported and FastLogin doesn't work

### ISSUE THREAD

**Issue by At87668** [games647/FastLogin#1216]
### What happened?

[FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
java.lang.NoSuchMethodError: 'io.netty.channel.Channel com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.getWrappedChannel()'
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.getChannel(ProtocolLibListener.java:307) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.getFloodgatePlayer(ProtocolLibListener.java:298) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.processFloodgateTasks(ProtocolLibListener.java:320) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:121) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$processPacket$4(AsyncListenerHandler.java:604) ~[?:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:600) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:572) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:48) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:217) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:286) ~[?:?]
        at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]

### Steps to reproduce

1.Install Geyser and FastLogin to server.
2.A player in premium list join server.
3.An error report and FastLogin doesn't work

### Plugin list

RedstoneClockPreventer, ColoredSigns, PlaceholderAPI, GroupManager, AtLite, CMILib, PlugMan, spark, ConsoleSpamFix, LaggRemover, NoSpawnChunks, PlayerReport, LightAntiCheat, Vault, MiniMOTD, WorldEdit, WorldEditSUI, Essentials, Multiverse-Core, ProtocolLib, SkinsRestorer, LockettePro, PlayerTitle, Residence, DeluxeMenus, EssentialsChat, Orebfuscator, TAB, PvPManager, AuthMe, FastLogin, Geyser, Floodgate

### Configuration file

https://pastebin.com/6HpvtTiT

### Server log

https://gist.github.com/At87668/50f6322807e7c41007af713419663460

### Plugin version

1.12-SNAPSHOT-29100b5

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
This sounds like an outdated ProtocolLib version. Could you check that?

**Comment by At87668** [comment]
I'm using ProtocolLib 5.3.0-SNAPSHOT-723.

**Comment by At87668** [comment]
Sorry,I don't know you are fast.

**Comment by At87668** [comment]
Sorry, sorry, I was mistaken.
Actually if geyser is installed, the error will report.
