### ISSUE TITLE
Fast login and register not working

### ISSUE THREAD

**Issue by ProBoyGaming** [games647/FastLogin#1218]
### What happened?

So I can use the Auto login does not work I previously fix it by the help of [#719](https://github.com/games647/FastLogin/issues/1210)
by the server files were lost due to problems with host. Now I am running the backup file of the server where the problem was not fixed yet. I am sure this is a problem of the ProtocolLib or Fast login plugin version only I am using ProtocolLib
 version 5.3.0-SNAPSHOT-719 and AuthmeReloaded version 5.6.0-beta2-b2453 and Fastlogin 1.12-SNAPSHOT-07e19b5

### Steps to reproduce

 **ProtocolLib** version 5.3.0-SNAPSHOT-719
**AuthmeReloaded** version 5.6.0-beta2-b2453
**Fastlogin** 1.12-SNAPSHOT-07e19b5

### Plugin list

AuthMe, BlueSlimeCore, ClearLag, CombatLogX, DiscordSRV, Essentials, EssentialsChat, FastLogin, LPC, LuckPerms,PlaceholderAPI, ProtocolLib, SkinsRestorer, spark, TAB, Vault, ViaBackwards, ViaVersion

### Configuration file

https://gist.github.com/ProBoyGaming/0b9a7168f6c5be3cc5912e92f6e9a3d6

### Server log

openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
Starting org.bukkit.craftbukkit.Main
System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS) Host: Linux 5.4.0-182-generic (amd64)
Loading libraries, please wait...
[06:57:51 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[06:57:53 INFO]: Loaded 1290 recipes
[06:57:53 INFO]: Loaded 1399 advancements
[06:57:54 INFO]: Starting minecraft server version 1.21
[06:57:54 INFO]: Loading properties
[06:57:54 INFO]: This server is running Purpur version 1.21-2252-ver/1.21@d5c06b4 (2024-07-01T07:22:05Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
[06:57:55 INFO]: Server Ping Player Sample Count: 12
[06:57:55 INFO]: Using 4 threads for Netty based IO
[06:57:55 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and population gen parallelism of 1 threads
[06:57:56 INFO]: Default game type: SURVIVAL
[06:57:56 INFO]: Generating keypair
[06:57:56 INFO]: Starting Minecraft server on 0.0.0.0:25572
[06:57:56 INFO]: Using epoll channel type
[06:57:56 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[06:57:56 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[06:57:58 INFO]: [FastLogin] Initialize logging service
[06:57:58 INFO]: [FastLogin] Using optimized green threads with Java 21
[06:57:58 INFO]: [ViaVersion] Loading server plugin ViaVersion v5.0.1
[06:57:58 INFO]: [ViaVersion] ViaVersion 5.0.1 is now loaded. Registering protocol transformers and injecting...
[06:58:00 INFO]: [ViaVersion] Loading block connection mappings ...
[06:58:00 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[06:58:01 INFO]: [ViaBackwards] Loading translations...
[06:58:01 INFO]: [ViaBackwards] Registering protocols...
[06:58:02 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.131
[06:58:03 INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[06:58:03 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.3.0-SNAPSHOT-719
[06:58:03 WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[06:58:05 INFO]: [Essentials] Loading server plugin Essentials v2.21.0-dev+102-fcf6e64
[06:58:05 INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.6
[06:58:05 INFO]: [AuthMe] Loading server plugin AuthMe v5.6.0-beta2-b2453
[06:58:05 INFO]: [Blue Slime Core] Loading server plugin BlueSlimeCore v2.9.4.377
[06:58:05 INFO]: [ViaBackwards] Loading server plugin ViaBackwards v5.0.1
[06:58:05 INFO]: [spark] Loading server plugin spark v1.10.73
[06:58:05 INFO]: [LPC] Loading server plugin LPC v3.6.0
[06:58:05 INFO]: [ClearLag] Loading server plugin ClearLag v3.2.2
[06:58:05 INFO]: [FastLogin] Loading server plugin FastLogin v1.12-SNAPSHOT-07e19b5
[06:58:05 INFO]: [CombatLogX] Loading server plugin CombatLogX v11.4.0.1.1193
[06:58:05 INFO]: [CombatLogX] Configuration version is recent, no major changes necessary.
[06:58:05 INFO]: [CombatLogX] Loading expansions...
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Damage Effects v17.0'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'PlaceholderAPI Compatibility v17.1'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'EssentialsX Compatibility v17.2'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Loot Protection v17.1'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Logger v17.2'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'End Crystal Helper v17.1'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 WARN]: [CombatLogX] Failed to load expansion 'plugins/CombatLogX/expansions/PlayerParticles Compatibility.jar' because a plugin dependency was not loaded: PlayerParticles
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Action Bar v17.3'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Newbie Helper v17.2'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Damage Tagger v17.1'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Force Field v17.4'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'LuckPerms Compatibility v17.1'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Mob Tagger v17.1'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Boss Bar v17.1'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Loading expansion 'Death Effects v17.0'...
[06:58:05 INFO]: [CombatLogX]  
[06:58:05 INFO]: [CombatLogX] Successfully loaded 14 expansions.
[06:58:05 INFO]: [EssentialsChat] Loading server plugin EssentialsChat v2.21.0-dev+102-fcf6e64
[06:58:05 INFO]: [DiscordSRV] Loading server plugin DiscordSRV v1.27.0
[06:58:05 INFO]: [SkinsRestorer] Loading server plugin SkinsRestorer v15.0.15
[06:58:05 INFO]: [TAB] Loading server plugin TAB v4.1.5
[06:58:05 INFO]: Server permissions file permissions.yml is empty, ignoring it
[06:58:05 INFO]: [LuckPerms] Enabling LuckPerms v5.4.131
[06:58:06 INFO]:         __    
[06:58:06 INFO]:   |    |__)   LuckPerms v5.4.131
[06:58:06 INFO]:   |___ |      Running on Bukkit - Purpur
[06:58:06 INFO]: 
[06:58:06 INFO]: [LuckPerms] Loading configuration...
[06:58:06 INFO]: [LuckPerms] Loading storage provider... [H2]
[06:58:07 INFO]: [LuckPerms] Loading internal permission managers...
[06:58:07 INFO]: [LuckPerms] Performing initial data load...
[06:58:07 INFO]: [LuckPerms] Successfully enabled. (took 1906ms)
[06:58:07 INFO]: [Vault] Enabling Vault v1.7.3-b131
[06:58:07 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[06:58:08 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[06:58:08 INFO]: [Vault] Enabled Version 1.7.3-b131
[06:58:08 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[06:58:08 INFO]: [ProtocolLib] Enabling ProtocolLib v5.3.0-SNAPSHOT-719
[06:58:08 INFO]: [Blue Slime Core] Enabling BlueSlimeCore v2.9.4.377
[06:58:08 INFO]: [Blue Slime Core] Successfully loaded 2 language(s).
[06:58:08 INFO]: [Blue Slime Core] Detected server as regular SpigotMC/PaperMC (not Folia)
[06:58:08 INFO]: [SkinsRestorer] Enabling SkinsRestorer v15.0.15
[06:58:10 INFO]: [SkinsRestorer] Running on Minecraft 1.21.
[06:58:10 INFO]: [PlaceholderAPI] Successfully registered internal expansion: skinsrestorer [15.0.15]
[06:58:10 INFO]: [SkinsRestorer] PlaceholderAPI expansion registered!
[06:58:10 INFO]: [SkinsRestorer] Using paper join listener!
[06:58:10 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[06:58:10 WARN]: The server will make no attempt to authenticate usernames. Beware.
[06:58:10 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[06:58:10 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[06:58:10 INFO]: Preparing level "world"
[06:58:10 INFO]: [SkinsRestorer] ----------------------------------------------
[06:58:10 INFO]: [SkinsRestorer]     +==================+
[06:58:10 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[06:58:10 INFO]: [SkinsRestorer]     |------------------|
[06:58:10 INFO]: [SkinsRestorer]     |  Standalone Mode |
[06:58:10 INFO]: [SkinsRestorer]     +==================+
[06:58:10 INFO]: [SkinsRestorer] ----------------------------------------------
[06:58:10 INFO]: [SkinsRestorer]     Version: 15.0.15
[06:58:10 INFO]: [SkinsRestorer]     Commit: fcfa8b9
[06:58:10 INFO]: [SkinsRestorer]     This is the latest version!
[06:58:10 INFO]: [SkinsRestorer] ----------------------------------------------
[06:58:11 INFO]: Preparing start region for dimension minecraft:overworld
[06:58:13 INFO]: Time elapsed: 1443 ms
[06:58:13 INFO]: Preparing start region for dimension minecraft:the_nether
[06:58:13 INFO]: Time elapsed: 276 ms
[06:58:13 INFO]: Preparing start region for dimension minecraft:the_end
[06:58:13 INFO]: Time elapsed: 103 ms
[06:58:13 INFO]: [ViaVersion] Enabling ViaVersion v5.0.1
[06:58:13 INFO]: [ViaVersion] ViaVersion detected server version: 1.21 (767)
[06:58:13 INFO]: [Essentials] Enabling Essentials v2.21.0-dev+102-fcf6e64
[06:58:14 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[06:58:14 INFO]: [Essentials] No kits found to migrate.
[06:58:15 INFO]: [Essentials] Loaded 42679 items from items.json.
[06:58:15 INFO]: [Essentials] Using locale en_US
[06:58:15 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[06:58:16 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[06:58:16 INFO]: [Vault] [Economy] Essentials Economy hooked.
[06:58:16 INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[06:58:16 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.6
[06:58:16 INFO]: [PlaceholderAPI] Fetching available expansion information...
[06:58:16 INFO]: [AuthMe] Enabling AuthMe v5.6.0-beta2-b2453
[06:58:17 INFO]: [AuthMe] SQLite Setup finished
[06:58:17 INFO]: [AuthMe] Hooked into LuckPerms!
[06:58:17 INFO]: [AuthMe] Hooked successfully into Essentials
[06:58:17 INFO]: [AuthMe] Essentials spawn file not found: '/home/container/plugins/Essentials/spawn.yml'
[06:58:17 INFO]: [AuthMe] AuthMe 5.6.0-beta2 build n.2453 successfully enabled!
[06:58:17 INFO]: [ViaBackwards] Enabling ViaBackwards v5.0.1
[06:58:17 INFO]: [spark] Enabling spark v1.10.73
[06:58:18 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[06:58:18 INFO]: [spark] Starting background profiler...
[06:58:19 INFO]: [PlaceholderAPI] Successfully registered internal expansion: spark [1.10.73]
[06:58:19 INFO]: [spark] Registered PlaceholderAPI placeholders
[06:58:19 INFO]: [LPC] Enabling LPC v3.6.0
[06:58:19 INFO]: [ClearLag] Enabling ClearLag v3.2.2
[06:58:19 INFO]: [ClearLag] Using version-adapter: LatestVersionAdapter
[06:58:19 INFO]: [ClearLag] Loading modules...
[06:58:19 WARN]: [ClearLag] Clearlag failed to use the internal TPS tracker during initialization. Reverted to estimation... (Index 3 out of bounds for length 3)
[06:58:19 INFO]: [ClearLag] Modules enabed, loading config values
[06:58:19 INFO]: [ClearLag] Modules have been loaded!
[06:58:19 INFO]: [ClearLag] Clearlag is now enabled!
[06:58:19 WARN]: [ClearLag] Clearlag failed to check for updates - bukkit may be down
[06:58:19 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
[06:58:19 WARN]:        at Clearlag.jar//me.minebuilders.clearlag.Util.getBukkitVersion(Util.java:105)
[06:58:19 WARN]:        at Clearlag.jar//me.minebuilders.clearlag.BukkitUpdater.updateAvailable(BukkitUpdater.java:32)
[06:58:19 WARN]:        at Clearlag.jar//me.minebuilders.clearlag.BukkitUpdater.run(BukkitUpdater.java:82)
[06:58:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[06:58:19 INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-07e19b5
[06:58:19 WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.
[06:58:20 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Starting...
[06:58:20 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Start completed.
[06:58:20 INFO]: [PlaceholderAPI] Successfully registered internal expansion: FastLogin [1.12-SNAPSHOT-07e19b5]
[06:58:20 INFO]: [CombatLogX] Enabling CombatLogX v11.4.0.1.1193
[06:58:20 INFO]: [CombatLogX] Successfully loaded 29 language(s).
[06:58:20 INFO]: [CombatLogX] Detected server as regular SpigotMC/PaperMC (not Folia)
[06:58:20 INFO]: CombatLogX was loaded successfully.
[06:58:20 INFO]: [CombatLogX] Enabling expansions...
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Action Bar v17.3'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Boss Bar v17.1'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'EssentialsX Compatibility v17.2'...
[06:58:20 INFO]: [CombatLogX] [EssentialsX Compatibility] Successfully found a dependency: Essentials v2.21.0-dev+102-fcf6e64
[06:58:20 INFO]: [CombatLogX] [EssentialsX Compatibility] Detected EssentialsX successfully.
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'LuckPerms Compatibility v17.1'...
[06:58:20 INFO]: [CombatLogX] [LuckPerms Compatibility] Successfully found a dependency: LuckPerms v5.4.131
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'PlaceholderAPI Compatibility v17.1'...
[06:58:20 INFO]: [CombatLogX] [PlaceholderAPI Compatibility] Successfully found a dependency: PlaceholderAPI v2.11.6
[06:58:20 INFO]: [PlaceholderAPI] Successfully registered internal expansion: combatlogx [17.1]
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Damage Effects v17.0'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Damage Tagger v17.1'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Death Effects v17.0'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'End Crystal Helper v17.1'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Force Field v17.4'...
[06:58:20 INFO]: [CombatLogX] [Force Field] Successfully found a dependency: ProtocolLib v5.3.0-SNAPSHOT-719
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Logger v17.2'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Loot Protection v17.1'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Mob Tagger v17.1'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Enabling expansion 'Newbie Helper v17.2'...
[06:58:20 INFO]: [CombatLogX]  
[06:58:20 INFO]: [CombatLogX] Successfully enabled 14 expansions.
[06:58:20 INFO]: CombatLogX was enabled successfully.
[06:58:20 INFO]: [EssentialsChat] Enabling EssentialsChat v2.21.0-dev+102-fcf6e64
[06:58:21 INFO]: [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
[06:58:21 INFO]: [DiscordSRV] Enabling DiscordSRV v1.27.0
[06:58:21 INFO]: [TAB] Enabling TAB v4.1.5
[06:58:21 INFO]: [TAB] Loaded NMS hook in 196ms
[06:58:22 INFO]: [DiscordSRV] DiscordSRV is up-to-date. (6405e850eea61a4b9bf4f0d0cbb80fe20b3cfb90)
[06:58:23 INFO]: [TAB] Enabled in 1443ms
[06:58:23 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[06:58:23 INFO]: Running delayed init tasks
[06:58:23 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[06:58:23 INFO]: [AuthMe] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[06:58:23 WARN]: [AuthMe] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[06:58:23 INFO]: [AuthMe] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[06:58:23 INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[06:58:23 INFO]: [PlaceholderAPI] Successfully registered external expansion: server [2.7.2]
[06:58:23 INFO]: 1 placeholder hook(s) registered!
[06:58:23 WARN]: [AuthMe] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[06:58:23 INFO]: [Vault] Checking for Updates ... 
[06:58:23 INFO]: [CombatLogX] Successfully enabled 0 late-load expansions.
[06:58:23 INFO]: Done (29.291s)! For help, type "help"
container@pterodactyl~ Server marked as running...
[06:58:23 INFO]: [Blue Slime Core]  
[06:58:23 INFO]: [Blue Slime Core] [Update Checker] A possible update was found for plugin 'CombatLogX'.
[06:58:23 INFO]: [Blue Slime Core] [Update Checker] Current Version: 11.4.0.1.1193
[06:58:23 INFO]: [Blue Slime Core] [Update Checker] New Version: 11.5.0.0.1242
[06:58:23 INFO]: [Blue Slime Core] [Update Checker] Download Link: https://www.spigotmc.org/resources/31689/
[06:58:23 INFO]: [Vault] No new version available
[06:58:23 INFO]: [Essentials] Fetching version information...
[06:58:23 INFO]: [Blue Slime Core]  
[06:58:23 INFO]: [Blue Slime Core] [Update Checker] Found a possible update for plugin 'BlueSlimeCore'.
[06:58:23 INFO]: [Blue Slime Core] [Update Checker] Local Version: 2.9.4.377
[06:58:23 INFO]: [Blue Slime Core] [Update Checker] Remote Version: 2.9.6.431
[06:58:23 INFO]: [Blue Slime Core] [Update Checker] Download Link: https://hangar.papermc.io/SirBlobman/BlueSlimeCore
[06:58:23 INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook
[06:58:25 INFO]: [DiscordSRV] [JDA] Login Successful!
[06:58:25 INFO]: [DiscordSRV] [JDA] Connected to WebSocket
[06:58:26 INFO]: [DiscordSRV] [JDA] Finished Loading!
[06:58:26 INFO]: [DiscordSRV] Found server G:Destruction - An Anarchy server(1249608280804823141)
[06:58:26 INFO]: [DiscordSRV] - TC:📖-server-info(1249613762160492644)
[06:58:26 INFO]: [DiscordSRV] - TC:🚪joins(1249608280846897248)
[06:58:26 INFO]: [DiscordSRV] - TC:📜rules(1249608280846897249)
[06:58:26 INFO]: [DiscordSRV] - TC:💵-advertisement(1250303399149441095)
[06:58:26 INFO]: [DiscordSRV] - TC:🏅-ranks-perks(1250713364359806997)
[06:58:26 INFO]: [DiscordSRV] - TC:🏅how-to-get-rank(1250712992753127424)
[06:58:26 INFO]: [DiscordSRV] - TC:❗-announcements(1250132738313425049)
[06:58:26 INFO]: [DiscordSRV] - TC:📊-polls(1251186724252553276)
[06:58:26 INFO]: [DiscordSRV] - TC:🎉-giveaway(1255938294076801065)
[06:58:26 INFO]: [DiscordSRV] - TC:🫅-partners(1249608280846897252)
[06:58:26 INFO]: [DiscordSRV] - TC:🪵-logs(1251504800999149648)
[06:58:26 INFO]: [DiscordSRV] - TC:🤖-bot-updates(1252154334989516821)
[06:58:26 INFO]: [DiscordSRV] - TC:💭-chat(1249608281136037934)
[06:58:26 INFO]: [DiscordSRV] - TC:📷images(1249608281136037935)
[06:58:26 INFO]: [DiscordSRV] - TC:😂memes(1251546865544204308)
[06:58:26 INFO]: [DiscordSRV] - TC:🤖commands(1249608281136037937)
[06:58:26 INFO]: [DiscordSRV] - TC:💭off-topic(1249608281136037936)
[06:58:26 INFO]: [DiscordSRV] - TC:🤔-suggestion(1251250828182949928)
[06:58:26 INFO]: [DiscordSRV] - TC:🎮-mc-chat(1249608281136037939)
[06:58:26 INFO]: [DiscordSRV] - TC:💵-trading(1254048890110349344)
[06:58:26 INFO]: [DiscordSRV] - TC:🏠share-base-photos(1254048985132302367)
[06:58:26 INFO]: [DiscordSRV] - TC:🎫-tickets(1249608281324912713)
[06:58:26 INFO]: [DiscordSRV] - TC:👷staff-applications👷(1249608281324912714)
[06:58:26 INFO]: [DiscordSRV] - TC:ticket-0010(1257287497730494515)
[06:58:26 INFO]: [DiscordSRV] - TC:ticket-0012(1257610332676030557)
[06:58:26 INFO]: [DiscordSRV] - TC:staff-chat(1249608281324912719)
[06:58:26 INFO]: [DiscordSRV] - TC:minecraft-server-logs(1249688024036540597)
[06:58:26 INFO]: [DiscordSRV] - TC:very-private(1250299053150044170)
[06:58:26 INFO]: [DiscordSRV] - TC:staff-announcements(1250696123337674785)
[06:58:26 INFO]: [DiscordSRV] - TC:testing-bots(1251176269324750920)
[06:58:26 INFO]: [DiscordSRV] - TC:logs(1251255108407267429)
[06:58:26 INFO]: [DiscordSRV] - TC:discord-logs-ig-idk(1251255528038993970)
[06:58:26 INFO]: [DiscordSRV] - TC:to-do-list(1251506045839474752)
[06:58:26 INFO]: [DiscordSRV] - TC:console(1256600795491733578)
[06:58:26 INFO]: [DiscordSRV] - TC:music(1251491243544805437)
[06:58:26 INFO]: [DiscordSRV] - TC:ticket-0013(1257687726497595442)
[06:58:26 INFO]: [DiscordSRV] - TC:ticket-0015(1258651615963910217)
[06:58:26 INFO]: [DiscordSRV] - TC:ticket-0016(1258663430081085491)
[06:58:26 INFO]: [DiscordSRV] Console channel ID was invalid, not forwarding console output
[06:58:26 ERROR]: [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[06:58:26 INFO]: [DiscordSRV] Enabling Essentials hook
[06:58:26 INFO]: [DiscordSRV] Enabling LuckPerms hook
[06:58:26 INFO]: [DiscordSRV] Enabling PlaceholderAPI hook
[06:58:26 INFO]: [PlaceholderAPI] Successfully registered internal expansion: discordsrv [1.27.0]
[06:58:26 INFO]: [DiscordSRV] Cleared all pre-existing slash commands in 1/1 guilds (0 cancelled)
[06:58:53 INFO]: [FastLogin] New packet START[class=ServerboundHelloPacket, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@7a01f063
[06:58:53 INFO]: [FastLogin] Handling player ProBoy_gaming
[06:58:53 INFO]: UUID of player ProBoy_gaming is f8ba0a6f-ea75-38c5-82cb-a5abdbeb1b47
[06:58:55 INFO]: [DiscordSRV] Player ProBoy_gaming joined with silent joining permission, not sending a join message
[06:58:55 INFO]: ProBoy_gaming joined the game
[06:58:55 INFO]: ProBoy_gaming[ip] logged in with entity id 33 at ([world]8.705665140196352, 104.0, 10.439410724555545)
[06:58:59 INFO]: [AuthMe] ProBoy_gaming logged in ||ip||

### Plugin version

1.12-SNAPSHOT-07e19b5

### Platform

Spigot

### Relevance

- [x] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by At87668** [comment]
I think you should give permissions "fastlogin.bukkit.command.premium" to your players, and tell them should use command "/premium".
I'm doing this, player can auto login, no problem.

**Comment by ProBoyGaming** [comment]
Can any1 send me the download link of FastLogin version 1.12-SNAPSHOT-829c70a? I think that will fix it

**Comment by At87668** [comment]
> any1 可以向我发送 FastLogin 版本 1.12-SNAPSHOT-829c70a 的下载链接吗？我认为这将解决它

https://ci.codemc.io/job/Games647/job/FastLogin/

**Comment by ProBoyGaming** [comment]
> > Can any1 send me the download link of FastLogin version 1.12-SNAPSHOT-829c70a? I think that will fix it
> 
> https://ci.codemc.io/job/Games647/job/FastLogin/

**Comment by ProBoyGaming** [comment]
> > > Can any1 send me the download link of FastLogin version 1.12-SNAPSHOT-829c70a? I think that will fix it
> > 
> > 
> > https://ci.codemc.io/job/Games647/job/FastLogin/

Did not fix unfortunately
