### ISSUE TITLE
Plugin is disabled

### ISSUE THREAD

**Issue by 3limssmile** [games647/FastLogin#1228]
### What happened?

Can use any commands related to this plugin

### Steps to reproduce

/cracked, /fastlogin, /premium 
![image](https://github.com/games647/FastLogin/assets/131522279/a89df61e-d384-4a19-9006-d0a524f96a16)

### Plugin list

AuthMe, FastLogin, Graves. GSit, Mobis ElevatorSigns, ProtocolLib, SimpleTpa, SkinsRestorer, UltimateHomes

### Configuration file

https://gist.github.com/3limssmile/50ccc16a4ee9d96f31f0d794ce48d204

### Server log

```
[12:22:13 ERROR]: null

org.bukkit.command.CommandException: Cannot execute command 'premium' in plugin FastLogin v1.12-SNAPSHOT-4dd6b9a - plugin is disabled.

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-464]

at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-464]

at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]

at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]

at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]

at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]

at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]

at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1557) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-464]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-464]

at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Plugin version

v1.12-SNAPSHOT-4dd6b9a

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)
- [ ] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Then please check for earlier log messages. The plugin disables itself if you have an invalid configuration.

**Comment by 3limssmile** [comment]
okay i had online mode enabled thanks
