### ISSUE TITLE
FastloginVelocity needs SNAP to run correctly

### ISSUE THREAD

**Issue by lonlf** [games647/FastLogin#1235]
### What happened?

When I was trying FastLogin on Velocity, it crushed and errors reported as below.

Then I installed SNAP[https://github.com/Phoenix616/Snap] in order to run FastLoginBungee in Velocity.

But I just run FastLoginVelocity successfully with SNAP.

so weired.

十 Wish it could be help. 十

### Steps to reproduce

Use SNAP[https://github.com/Phoenix616/Snap] with FastLoginVelocity in Velocity.

### Plugin list

FastLoginVelocity

### Server log

`[01:38:23] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loaded 5 plugins
[01:38:23] [Velocity Async Event Executor - #0/INFO] [fastlogin]: Using legacy scheduler
[01:38:24] [Velocity Async Event Executor - #0/ERROR] [fastlogin.hikari.HikariConfig]: Failed to load driver class com.mysql.cj.jdbc.Driver from HikariConfig class classloader com.velocitypowered.proxy.plugin.PluginClassLoader@652ce654
[01:38:24] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to fastlogin 1.12-SNAPSHOT-4dd6b9a
java.lang.RuntimeException: Failed to load driver class com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
	at fastlogin.hikari.HikariConfig.setDriverClassName(HikariConfig.java:491) ~[?:?]
	at com.github.games647.fastlogin.core.storage.MySQLStorage.setParams(MySQLStorage.java:49) ~[?:?]
	at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:42) ~[?:?]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:254) ~[?:?]
	at com.github.games647.fastlogin.velocity.FastLoginVelocity.onProxyInitialization(FastLoginVelocity.java:100) ~[?:?]
	at com.github.games647.fastlogin.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-410.jar:3.3.0-SNAPSHOT (git-d999ee20-b410)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-410.jar:3.3.0-SNAPSHOT (git-d999ee20-b410)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-410.jar:3.3.0-SNAPSHOT (git-d999ee20-b410)]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[01:38:24] [Velocity Async Event Executor - #0/INFO] [authmevelocity]:  --- AuthMeVelocity ---
`

### Plugin version

#1325

### Platform

Velocity

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
As mentioned in the configuration, Velocity has no driver for MySQL. However, FastLogin includes the driver for MariaDB.
