### ISSUE TITLE
Error if config stuff doesn't exist

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#127]
When the config is older and we update the plugin, it will stop working if you added new config options. Stacktrace:
```
[16:40:37] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling FastLogin v1.10-git863607c9a401cd424f3210ec1b7ceb399ba4684e (Is it up to date?)
java.lang.NullPointerException
	at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:129) ~[?:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:57) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
```

**Comment by games647** [comment]
I tried using one of the [oldest config ](https://raw.githubusercontent.com/games647/FastLogin/3e844be65d568e15468440598e09321b5629dc01/core/src/main/resources/config.yml) and it still worked for me.

Tested using PaperSpigot 1.11.2 and Thermos.

**Comment by Eufranio** [comment]
By some reason my server box wont create new files. My bad.
