### ISSUE TITLE
cant connect at the server after update the jar file 

### ISSUE THREAD

**Issue by comonier** [games647/FastLogin#131]
`28.02 03:47:47 [Disconnect] User com.mojang.authlib.GameProfile@1db026[id=231d3715-79e5-3319-bbeb-fd7671b2f412,name=comonier,properties={textures=[com.mojang.authlib.properties.Property@382f7d4b]},legacy=false] (/179.158.130.67:63573) has disconnected, reason: not-started from FastLogin`

updated jar file like u said : http://ci.xephi.fr/job/FastLogin/
choise (FastLogin.jar	308.69 KB) 
not choise (original-FastLogin.jar	2.65 KB)
(you not sad each one)

after do login on server i cant connect anymore
and the server is alredy full started

config.yml

- autoRegister: false
- secondAttemptCracked: true
- switchMode: true
- premiumUuid: true
- nameChangeCheck: true
- forwardSkin: true
- premium-warning: true
- ip-addresses: []
- mojang-request-limit: 600
- autoLogin: true
- driver: org.sqlite.JDBC
- database: '{pluginDir}/FastLogin.db

on messages.yml  i found that:
# Message if the bukkit isn't fully started to inject the packets
not-started: 'not-started from FastLogin' (i renamed just to fast know what plugin is the error)
not-started: '&cServer is not fully started yet. Please retry'

sorry if i dont know what u means... how can i solve it ?

if i try use the other jar ( (original-FastLogin.jar	2.65 KB))  the server do not load the plugin

`[04:17:35] [Server thread/ERROR]: Could not load 'plugins/original-FastLogin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot111-java8.jar:git-Spigot-261f181-7359112]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot111-java8.jar:git-Spigot-261f181-7359112]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot111-java8.jar:git-Spigot-261f181-7359112]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot111-java8.jar:git-Spigot-261f181-7359112]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot111-java8.jar:git-Spigot-261f181-7359112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more`

**Comment by games647** [comment]
Wrong jar file.
