### ISSUE TITLE
Couldn't enable encryption java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Ricky89GR** [games647/FastLogin#134]
19:27:33 ERROR]: [FastLogin] Couldn't enable encryption
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.encryptConnection(VerifyResponseTask.java:150) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:73) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:57) [FastLogin.jar:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-c3e4052-1953f52]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.NoSuchElementException: splitter
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150) ~[spigot.jar:git-Spigot-c3e4052-1953f52]
        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5$1.addBefore(ChannelInjector.java:297) ~[?:?]
        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:260) ~[spigot.jar:git-Spigot-c3e4052-1953f52]

**Comment by games647** [comment]
What's your plugin version? Could you try a dev-build.

**Comment by games647** [comment]
Check if you are using the correct ProtocolLib version.
