### ISSUE TITLE
java.lang.IllegalAccessError: tried to access class com.comphenix.protocol.injector.netty.Injector from class 

### ISSUE THREAD

**Issue by gerbipl** [games647/FastLogin#138]
[23:55:40] [Craft Scheduler Thread - 14/WARN]: Exception in thread "Craft Scheduler Thread - 14" 
[23:55:40] [Craft Scheduler Thread - 14/WARN]: org.apache.commons.lang.UnhandledException: Plugin FastLogin v1.9 generated an exception while executing task 79
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: tried to access class com.comphenix.protocol.injector.netty.Injector from class com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.getNetworkManager(VerifyResponseTask.java:135)
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.encryptConnection(VerifyResponseTask.java:142)
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:73)
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:57)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by games647** [comment]
Please try out an dev-build and post your ProtocolLib version

**Comment by gerbipl** [comment]
I have the latest version of FastLogin and ProtocolLib v3.7.0

**Comment by games647** [comment]
FastLogin v1.9 is not the latest **dev-build**. Please upgrade from ci.xephi.fr/job/FastLogin/

**Comment by gerbipl** [comment]
I checked and run quickly, but will still test it. Thanks!
