### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ucraft02** [games647/FastLogin#139]
my error in spigot server:

[16:03:30] [Netty Epoll Server IO #0/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@aeed083 to net.minecraft.server.v1_11_R1.HandshakeListener@671be280
[16:03:30] [Netty Epoll Server IO #0/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@aeed083 to protocolsupport.zplatform.impl.spigot.network.handler.SpigotFakePacketListener@13d67b78
[16:03:30] [Netty Epoll Server IO #0/DEBUG]: Enabled auto read
[16:03:30] [Netty Epoll Server IO #0/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@aeed083 to protocolsupport.zplatform.impl.spigot.network.handler.SpigotModernHandshakeListener@a192895
[16:03:30] [Netty Epoll Server IO #0/DEBUG]: Enabled auto read
[16:03:30] [Netty Epoll Server IO #0/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@aeed083 to protocolsupport.zplatform.impl.spigot.network.handler.SpigotModernLoginListener@322ec4b4
[16:03:31] [LoginProcessingThread/INFO]: UUID of player Qintiy is 25bd0763-20dc-419f-8fbf-b947fcb0341c
[16:03:31] [LoginProcessingThread/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@aeed083 to protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay@8d34c79
[16:03:31] [LoginProcessingThread/DEBUG]: Disabled auto read
[16:03:31] [Netty Epoll Server IO #0/DEBUG]: Enabled auto read
[16:03:31] [Netty Epoll Server IO #0/DEBUG]: Enabled auto read
[16:03:31] [Server thread/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@aeed083 to net.minecraft.server.v1_11_R1.PlayerConnection@31769708
[16:03:31] [Server thread/INFO]: Qintiy[--------------------] logged in with entity id 91 at ([world]-823.1260749917573, 64.0, 774.0676559904999)
[16:03:31] [Server thread/TRACE]: [FastLogin] Received plugin message for subchannel AUTO_LOGIN from CraftPlayer{name=Qintiy}
[16:03:31] [Server thread/TRACE]: [FastLogin] Received proxy id 0e8a2934-9ef4-4d29-addb-2a1aa771ccd7 from CraftPlayer{name=Qintiy}
[16:03:31] [Server thread/WARN]: Could not pass incoming plugin message to FastLogin v1.9
java.lang.NullPointerException
    at com.github.games647.fastlogin.bukkit.listener.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:71) ~[?:?]
    at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2489) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
    at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by games647** [comment]
Upgrade FastLogin 

ci.xephi.fr/job/FastLogin/

**Comment by ucraft02** [comment]
I still have have this error

**Comment by ucraft02** [comment]
[18:16:16 WARN]: Could not pass incoming plugin message to FastLogin v1.1
java.lang.NullPointerException
    at com.github.games647.fastlogin.bukkit.listener.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:66) ~[?:?]
    at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2489) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
    at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by games647** [comment]
Do you updated the BungeeCord version of FastLogin too and followed the setup guide?

**Comment by ucraft02** [comment]
yes

**Comment by games647** [comment]
Then I need the BungeeCord log too.

**Comment by ucraft02** [comment]
16:17:45 [INFO] Could not load native library: /tmp/bungeecord-native-cipher3610717252789906633.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
16:17:45 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
16:17:45 [INFO] Using native code compressor
16:17:45 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:53cc324:1228
16:17:45 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
16:17:45 [INFO] Epoll is working, utilising it!
16:17:45 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
16:17:45 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
16:17:45 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
16:17:45 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
16:17:45 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
16:17:45 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
16:17:45 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Loaded plugin SkinsRestorer version 12.9.7 by Blackfire62, Th3Tr0LLeR
16:17:45 [INFO] Loaded plugin FastLogin version 1.10 by games647, http://github.com/games647/FastLogin/graphs/contributors
16:17:45 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [WARNING] Forced host server pvp is not defined
16:17:45 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Enabled plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Enabled plugin SkinsRestorer version 12.9.7 by Blackfire62, Th3Tr0LLeR
16:17:45 [SEVERE] Apr 05, 2017 4:17:45 PM com.zaxxer.hikari.HikariDataSource <init>
INFO: HikariPool-1 - Started.

16:17:45 [INFO] 
16:17:45 [INFO]     +===============+
16:17:45 [INFO]     | SkinsRestorer |
16:17:45 [INFO]     +===============+
16:17:45 [INFO] 
16:17:45 [INFO]     STABLE BUILD
16:17:45 [INFO] 
16:17:45 [INFO]     Current version: 12.9.7
16:17:45 [INFO]     The latest version!
16:17:45 [INFO] 
16:17:45 [INFO] Enabled plugin FastLogin version 1.10 by games647, http://github.com/games647/FastLogin/graphs/contributors
16:17:45 [INFO] Enabled plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Enabled plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:45 [INFO] Enabled plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:53cc324:1228 by SpigotMC
16:17:46 [INFO] Listening on /0.0.0.0:25565

**Comment by games647** [comment]
Of course at the time when the error happens and please use pastebin, hastebin or 

<details></details>

**Comment by ucraft02** [comment]
error is only on spigot server

**Comment by games647** [comment]
yes but the BungeeCord doesn't show anyone logging in. It has different timestamps, I need that one that the same.

**Comment by ucraft02** [comment]
https://pastebin.com/k5rWGcX4

**Comment by games647** [comment]
Still not the same timestamp, but could you just try to reset the BungeeCord config.yml (not the FastLogin one). I think you have an invalid stats-id there.

**Comment by ucraft02** [comment]
can you give me example for ip whitlist in spogot fastlogin folder??

**Comment by ucraft02** [comment]
2rz73789zf4385z39395t397t
only this??

**Comment by ucraft02** [comment]
thanks for help

**Comment by ucraft02** [comment]
it's work now
