### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ucraft02** [games647/FastLogin#140]
[18:16:16 WARN]: Could not pass incoming plugin message to FastLogin v1.1
java.lang.NullPointerException
at com.github.games647.fastlogin.bukkit.listener.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:66) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2489) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-27dd3ca]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by games647** [comment]
You already created one ticket. Please use that. You can still post answers there.

#139
