### ISSUE TITLE
Unable to use with AdvancedLogin

### ISSUE THREAD

**Issue by gundamMC** [games647/FastLogin#143]
When using the latest dev version (#736) of FastLogin (from ci.xephi.fr/job/FastLogin/) with AdvancedLogin 3.5 (also latest) it shows this:

Error occurred while enabling AdvancedLogin v3.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/games647/fastlogin/bukkit/PasswordGenerator
        at me.leoko.login.Main.onEnable(Main.java:151) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1081]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.github.games647.fastlogin.bukkit.PasswordGenerator
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1081]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        ... 12 more

And then FastLogin would go on saying no auth plugin were found.

If I use version 1.9 of FastLogin, AdvancedLogin would say it hooked into FastLogin but it's still saying no auth plugin were found.

[16:47.28 INFO]: Hooked AdvancedLogin into FastLogin
[16:47:28 INFO]: [AdvancedLogin] Disabling AdvancedLogin v3.5
[16:47:28 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:47:28 INFO]: Done (1.628s)! For help, type "help" or "?"
[16:47:28 INFO]: Timings Reset
[16:47:28 WARN]: [FastLogin] No support offline Auth plugin found.
[16:47:28 WARN]: [FastLogin] No auth plugin were found by this plugin (other plugins could hook into this after the intialization of this plugin)and bungeecord is deactivated. Either one or both of the checks have to pass in order to use this plugin

I contacted the author of AdvancedLogin and he gave me a "fixed" version of AdvancedLogin based on FastLogin 1.9, when I use it w/ the 1.9 version of FastLogin it's the same as the 3.5 version of AdvancedLogin: It hooked into FastLogin but FastLogin says there are no auth plugins.

Yet, if I use the current dev (#736) FastLogin, it shows this

[16:56:15 INFO]: Hooking into FastLogin >= 1.8...
[16:56:15 ERROR]: Error occurred while enabling AdvancedLogin v3.5 (Is it up to date?)
java.lang.NoSuchMethodError: com.github.games647.fastlogin.bukkit.FastLoginBukkit.getCore()Lcom/github/games647/fastlogin/bukkit/BukkitCore;
        at me.leoko.login.hook.FastLoginHook.initialHook(FastLoginHook.java:11) ~[?:?]
        at me.leoko.login.Main.onEnable(Main.java:149) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1081]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[16:56:15 INFO]: [AdvancedLogin] Disabling AdvancedLogin v3.5

**Comment by games647** [comment]
Outdated FastLogin version. Please update ci.xephi.fr/job/FastLogin/

**Comment by gundamMC** [comment]
It is the latest version, build #736. 

> When using the latest dev version (#736) of FastLogin (from ci.xephi.fr/job/FastLogin/)

It's literally the first line of this post.

**Comment by games647** [comment]
Sorry missed that one. Next time hide the stacktrace with

<details>
Error occurred while enabling AdvancedLogin v3.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/games647/fastlogin/bukkit/PasswordGenerator
at me.leoko.login.Main.onEnable(Main.java:151) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1081]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1081]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1081]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1081]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1081]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1081]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1081]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1081]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1081]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1081]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.github.games647.fastlogin.bukkit.PasswordGenerator
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.11.2.jar:git-Paper-1081]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1081]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
... 12 more
</details>

< details > </ details>, with '>' character or using pastebin.

It looks like the Jenkins builds are a bit outdated, please try this one: https://github.com/games647/FastLogin/releases/tag/advancedlogin

**Comment by gundamMC** [comment]
Thanks for your quick response!
But... The build from github still wouldn't fix the problem...
<details>[11:44:16 ERROR]: Error occurred while enabling AdvancedLogin v3.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/games647/fastlogin/bukkit/PasswordGenerator
        at me.leoko.login.Main.onEnable(Main.java:151) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1081]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.github.games647.fastlogin.bukkit.PasswordGenerator
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1081]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        ... 12 more</details>

**Comment by games647** [comment]
Try to ask the author of AdvancedLogin, because that nothing I can fix. I wrote yesterday with him. I thought he already uploaded the fixed version.

**Comment by gundamMC** [comment]
Ok... I'll go contact him. Thanks!

**Comment by gundamMC** [comment]
So I contacted him and he gave me the fixed version of AdvancedLogin. It says it hooked into FastLogin and everything, and FastLogin kinda just "went with it" without saying anything. But then, it wouldn't let me join the server with this message "server is not fully started yet. Please retry."
I've checked the console and there were no error messages. I could also use commands in the console which means the server did "fully started"

**Comment by games647** [comment]
Do you used the latest Version I sent you?

**Comment by gundamMC** [comment]
Yeah, this one https://github.com/games647/FastLogin/releases/tag/advancedlogin

**Comment by DevLeoko** [comment]
This Issue has also be reported to me so I've already fixed it and created a PR https://github.com/games647/FastLogin/pull/144
Would appreciate if you could check if what I've done is correct :) (Working on localhost)
