### ISSUE TITLE
Broken with Bukkit/Spigot 1.12

### ISSUE THREAD

**Issue by k-jiang** [games647/FastLogin#152]
It seems that [Spigot has changed their API again](https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12.246398/). I could not load the plugin with the new Spigot 1.12:
```
[17:53:00] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.9
[17:53:00] [Server thread/WARN]: [FastLogin] Could not save messages.yml to plugins/FastLogin/messages.yml because messages.yml already exists.
[17:53:00] [Server thread/ERROR]: Error occurred while enabling FastLogin v1.9 (Is it up to date?)
java.lang.NoClassDefFoundError: com/avaje/ebeaninternal/api/ClassUtil
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:55) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.avaje.ebeaninternal.api.ClassUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 9 more
```

According to this [older thread](https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-pre6-released.240317/), they removed something called "ebean", and you may need to figure it out another way:
```
The EBean ORM has been removed from Bukkit. This API was outdated and barely ever used (an old study of dev.bukkit.org plugins showed it being used by half a dozen plugins out of 15,000). In addition updating it from it’s 5 year old version would break plugins anyway. If you still require this API you should include it with / in your plugin yourself.
```

Tested on:
FastLogin 1.9
Spigot 1.12 build 1304

You have been doing a great job on develop and update the plugin. Thank you for your effort!
Hope I could see your update soon :)

**Comment by games647** [comment]
Just update FastLogin to 1.10 https://ci.xephi.fr/job/FastLogin

**Comment by k-jiang** [comment]
Great it is working again! Thank you!
ps. However It seems that the latest build is only working with AuthMe 3.4 but not 5.3.1, I will open a new issue about that.
