### ISSUE TITLE
Exception with AuthMe 5.3.1 (FastLogin 1.10 build 755)

### ISSUE THREAD

**Issue by k-jiang** [games647/FastLogin#153]
Tested with:
FastLogin 1.10 build 755 (retrieve from Jenkins)
Spigot 1.12 build 1304
AuthMe 5.3.1 https://www.spigotmc.org/resources/authme-reloaded.6269/update?update=165238

I'm trying to switch my AuthMe from 3.4 to 5.3.1 yet got an exception while player join:
```
[02:33:04] [Server thread/INFO]: k_jiang[/127.0.0.1:36290] logged in with entity id 2155 at ([world]-430.6451793872549, 67.0, -1107.341865335101)
[02:33:04] [Craft Scheduler Thread - 0/WARN]: [FastLogin] Plugin FastLogin v1.9 generated an exception while executing task 1060
java.lang.NoClassDefFoundError: fr/xephi/authme/api/API
	at com.github.games647.fastlogin.bukkit.hooks.AuthMeHook.forceLogin(AuthMeHook.java:33) ~[?:?]
	at com.github.games647.fastlogin.bukkit.hooks.AuthMeHook.forceLogin(AuthMeHook.java:18) ~[?:?]
	at com.github.games647.fastlogin.bukkit.tasks.ForceLoginTask.forceLogin(ForceLoginTask.java:103) ~[?:?]
	at com.github.games647.fastlogin.bukkit.tasks.ForceLoginTask.run(ForceLoginTask.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: fr.xephi.authme.api.API
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 9 more
```

I guess I could only stick with AuthMe 3.4 at this moment, even though 5.3.1 makes no different for me lol (I don't need the fancy new features. I just want to make it looks "newer").

**Comment by games647** [comment]
It says FastLogin 1.9 in that exception.

**Comment by k-jiang** [comment]
My bad. Forgot to delete the old one :P 
But why can I load two exactly same plugins (v1.9 and v1.10) without any issue at the beginning? Maybe this is a sign that the new 1.12 may came with so many bugs...
