### ISSUE TITLE
Problem with newest Authme

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [games647/FastLogin#161]
`[00:44:10 WARN]: org.apache.commons.lang.UnhandledException: Plugin FastLogin v1.9 generated an exception while executing task 416
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: fr/xephi/authme/api/API
        at com.github.games647.fastlogin.bukkit.hooks.AuthMeHook.forceLogin(AuthMeHook.java:33)
        at com.github.games647.fastlogin.bukkit.hooks.AuthMeHook.forceLogin(AuthMeHook.java:18)
        at com.github.games647.fastlogin.bukkit.tasks.ForceLoginTask.forceLogin(ForceLoginTask.java:103)
        at com.github.games647.fastlogin.bukkit.tasks.ForceLoginTask.run(ForceLoginTask.java:58)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: fr.xephi.authme.api.API
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more
`
Authme 5.3.2

**Comment by games647** [comment]
You have an outdated FastLogin version. Please update here: https://ci.xephi.fr/job/FastLogin/
