### ISSUE TITLE
Multiple IP address aren't working

### ISSUE THREAD

**Issue by M4T14SG4M3R** [games647/FastLogin#179]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # I bought a second IP address for my server and i have it setup correctly but i added it in the config and it's showing an error

### What behaviour is expected:
[//]: # It should work with multiple IP address

### Steps/models to reproduce:
[//]: # Add this in the config
ip-addresses:
    - x-x-x-x
    - x-x-x-x

### Plugin list:
[//]: # It's on bungeecord

### Environment description
[//]: # BungeeCord with mysql enabled

### Plugin version or build number (don't write latest):
[//]: # Latest from spigotmc

### Error Log:
https://hastebin.com/ocoqexiqir.sql

### Configuration:
[//]: # (remember to delete any sensitive data)
https://hastebin.com/veyepenuqe.bash

**Comment by games647** [comment]
Please use a dev-build. It's fixed there.

**Comment by M4T14SG4M3R** [comment]
05:28:58 [GRAVE] [FastLogin] IP-Address is unknown to us
java.net.UnknownHostException: 142-44-172-7: Nombre o servicio desconocido
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at com.github.games647.fastlogin.core.mojang.MojangApiConnector.buildAddresses(MojangApiConnector.java:163)
	at com.github.games647.fastlogin.core.mojang.MojangApiConnector.<init>(MojangApiConnector.java:68)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.makeApiConnector(FastLoginBungee.java:114)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:82)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:43)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by games647** [comment]
Looks like I forgot to convert the IP. I'll fix it.

**Comment by M4T14SG4M3R** [comment]
java.net.UnknownHostException: xxx-xx-xxx-x: Nombre o servicio desconocido
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at com.github.games647.fastlogin.core.mojang.MojangApiConnector.buildAddresses(MojangApiConnector.java:163)
	at com.github.games647.fastlogin.core.mojang.MojangApiConnector.<init>(MojangApiConnector.java:68)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.makeApiConnector(FastLoginBungee.java:114)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:82)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:43)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
05:28:58 [GRAVE] [FastLogin] IP-Address is unknown to us
java.net.UnknownHostException: xxx-xxx-xx-xxx: Nombre o servicio desconocido
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at com.github.games647.fastlogin.core.mojang.MojangApiConnector.buildAddresses(MojangApiConnector.java:163)
	at com.github.games647.fastlogin.core.mojang.MojangApiConnector.<init>(MojangApiConnector.java:68)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.makeApiConnector(FastLoginBungee.java:114)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:82)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:43)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)a:15)

**Comment by games647** [comment]
Could you try it again?

**Comment by M4T14SG4M3R** [comment]
I think is working, it didn't sent any error on startup, thanks!
