### ISSUE TITLE
Multiple IP addresses

### ISSUE THREAD

**Issue by M4T14SG4M3R** [games647/FastLogin#190]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # I added multiple ip addresses that i bought for my server because mojang is blocking the old two ip addresses, but i get an error on startup

### What behaviour is expected:
[//]: # It should work with multiple ip address, i have setup all the ip addresses

### Steps/models to reproduce:
[//]: # Put multiple ip addresses in the ip-address option

### Plugin list:
[//]: # Authme, FastLogin

### Environment description
[//]: # PaperSpigot 1.8.8

### Plugin version or build number (don't write latest):
[//]: # FastLogin version 1.11-25c725f

### Error Log:
[Hastebin](https://hastebin.com/mecowayexu.scala) / [Gist](https://gist.github.com/) link of the error or stacktrace (if any)

### Configuration:
[//]: # ip-addresses:
    - 1xx-xx-xxx-xx
    - 1xx-xx-xxx-xx
    - 1xx-xx-xxx-xx
    - 1xx-xx-xxx-xx

**Comment by games647** [comment]
And where is the error log?

**Comment by games647** [comment]
Do you use Wan or local IPs? Is your server configured to use those IPs?

**Comment by M4T14SG4M3R** [comment]
I configured those ip according to the OVH docs: https://docs.ovh.com/es/dedicated/network-ipaliasing/
And the error logs are in the spigot servers
https://imgur.com/a/31Hud

**Comment by games647** [comment]
If you use Bungeecord, you only have to configure the Bungee instance and follow the setup guide from the main page.

**Comment by M4T14SG4M3R** [comment]
I'm not getting the error on Bungee mode :/

`08:12:45 [ADVERTENCIA] Exception encountered when loading plugin: FastLogin
java.lang.IllegalArgumentException: type DIRECT is not compatible with address /192.x.x.x:0
    at java.net.Proxy.<init>(Proxy.java:95)
    at com.github.games647.fastlogin.core.mojang.MojangApiConnector.<init>(MojangApiConnector.java:69)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.makeApiConnector(FastLoginBungee.java:114)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:82)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:43)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
`

**Comment by games647** [comment]
Could you try it with the latest build.

**Comment by M4T14SG4M3R** [comment]
I'm using the latest dev build (783)

And got the same
`08:32:00 [ADVERTENCIA] Exception encountered when loading plugin: FastLogin
java.lang.IllegalArgumentException: type DIRECT is not compatible with address /192.x.x.x:0
    at java.net.Proxy.<init>(Proxy.java:95)
    at com.github.games647.fastlogin.core.mojang.MojangApiConnector.<init>(MojangApiConnector.java:69)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.makeApiConnector(FastLoginBungee.java:114)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:82)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:43)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

**Comment by games647** [comment]
Oh I forgot to push the changes. Wait two minutes.

**Comment by M4T14SG4M3R** [comment]
Now is working, but i have a spigot error, when it load it doesn't load properly and send an error to console
`[08:41:55] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.11-181ea71
[08:41:55] [Server thread/ERROR]: Error occurred while enabling FastLogin v1.11-181ea71 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
	at com.github.games647.fastlogin.core.mojang.MojangApiConnector.<init>(MojangApiConnector.java:61) ~[?:?]
	at com.github.games647.fastlogin.bukkit.MojangApiBukkit.<init>(MojangApiBukkit.java:28) ~[?:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.makeApiConnector(FastLoginBukkit.java:213) ~[?:?]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:82) ~[?:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[Lobby2.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [Lobby2.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [Lobby2.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [Lobby2.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [Lobby2.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170) [Lobby2.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:493) [Lobby2.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Lobby2.jar:git-PaperSpigot-ea452ce]
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Lobby2.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Lobby2.jar:git-PaperSpigot-ea452ce]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 13 more

I need to use it on the lobby servers because the /premium command doesn't work on Bungee, i'm using PaperSpigot 1.7.10`
