### ISSUE TITLE
"invalid session" insanity

### ISSUE THREAD

**Issue by Stephanech** [games647/FastLogin#199]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # When a premium registered player tries to join, the message "invalid session" appears, and this happens 3 to 20 times in a row, it's mega upsetting and could make some of my server's players leave forever

### What behaviour is expected:
[//]: # This to not happen

### Steps/models to reproduce:
[//]: # Just try to join the server

### Plugin list:
[//]: # 
![2018-03-01_22 14 43](https://user-images.githubusercontent.com/24770934/36876839-ca16e704-1d95-11e8-90a3-4ce56318c847.png)

### Environment description
[//]: # Minecraft 1.12 release. Spigot 1.12-R0.1-SNAPSHOT

### Plugin version or build number (don't write latest):
[//]: # 1.10

### Error Log:
None

### Configuration:
[//]: # (remember to delete any sensitive data)
[Hastebin]https://hastebin.com/ihugohozun.bash

**Comment by games647** [comment]
Please post the complete server log and try a dev build.

**Comment by Stephanech** [comment]
Complete server log? I have important stuff there that I won't release to the public.

I changed to the latest dev build (v1.11-8cbdb66) and the "invalid session" problem dissappeared, but there is another one now: It takes too much time to log in, and sometimes it just cancels the connection due that ("Took to long to log in" message appears). And an error appears in the log:

`[18:20:20] [Craft Scheduler Thread - 23/WARN]: [FastLogin] Failed to verify session
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_161]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_161]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_161]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673) ~[?:1.8.0_161]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_161]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_161]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_161]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_161]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_161]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_161]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199) ~[?:1.8.0_161]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_161]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_161]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_161]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_161]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_161]
	at com.github.games647.fastlogin.bukkit.MojangApiBukkit.hasJoinedServer(MojangApiBukkit.java:41) [FastLogin.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:97) [FastLogin.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:55) [FastLogin.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[18:20:20] [Craft Scheduler Thread - 23/WARN]: [FastLogin] Plugin FastLogin v1.11-8cbdb66 generated an exception while executing task 336
java.lang.NullPointerException: text cannot be NULL.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at com.comphenix.protocol.wrappers.WrappedChatComponent.fromText(WrappedChatComponent.java:102) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.kickPlayer(VerifyResponseTask.java:183) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.disconnect(VerifyResponseTask.java:178) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:105) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[18:20:44] [Server thread/INFO]: Disconnecting /XXX.XX.X.XXX:XXXXX: Took too long to log in
[18:20:44] [Server thread/INFO]: /XXX.XX.X.XXX:XXXXX lost connection: Took too long to log in`

All the other things that appear in the logs related to FastLogin are:

`[Server thread/INFO]: [FastLogin] Loading FastLogin v1.11-8cbdb66`

`[18:19:27] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.11-8cbdb66
[18:19:27] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader FastLogin v1.11-8cbdb66`

`[18:20:09] [Server thread/INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook`

**Comment by games647** [comment]
This means the plugin failed to contact the Mojang API. This could be caused by: 181ea7122278118b0ba8cc5b5aba0ed80f7b2e53

Could you try a build before 784.

**Comment by Stephanech** [comment]
Tried #783 and #780, same problem ( java.net.SocketTimeoutException: connect timed out )

**Comment by games647** [comment]
This means it couldn't connect to the session servers. Could you please post the output of:

>curl -v https://sessionserver.mojang.com/session/minecraft/hasJoined\?username\=games647\&serverId\=test

**Comment by ImSmoch** [comment]
The / premium thing also happens to me and I have a paid account . Any quick fix?
