### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by Feerko** [games647/FastLogin#200]
How can i check if player is premium or cracked? I can't find this in code. Placeholder doesn't work for me.

**Comment by games647** [comment]
(In Spigot)

For Spigot only setup, you can access the login sessions use this method
https://github.com/games647/FastLogin/blob/8272aeac69cfd638d492ad66a05536e274c0e02e/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/BukkitLoginSession.java#L91

Keep in mind that this session is only valid for one minute after login. After that it's removed.

For BungeeCord/Spigot setup, you can check for the Bukkit metadata value fastlogin_status which is only present if the Bungee instance sent a force login command.

**Comment by Feerko** [comment]
I'm using bungee and spigot. Can you help me with code to get this value?

**Comment by games647** [comment]
As I said you just need to access the metadata value from Bukkit which will be set by FastLogin after a short delay.

**Comment by Feerko** [comment]
https://github.com/games647/FastLogin/blob/66b808c9994a10af45b3c03fa3e6409f4d7ecc99/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/PremiumPlaceholder.java it will return a status? I'm tried with PAPI to get player's status and i'm getting %fastlogin_status%

**Comment by games647** [comment]
Just access the data directly using the Bukkit metadata API. You don't need a third-party project for that.

**Comment by Feerko** [comment]
player.getMetadata("fastlogin_status")
and
player.getMetadata("fastlogin")

returns [] for all players

**Comment by games647** [comment]
In BungeeCord environments this value will be set delayed.

**Comment by games647** [comment]
This is required, because we cannot check in Spigot if the login was in onlinemode therefore the instance on BungeeCord have to tell us that. After the force login message, we set a simple boolean with the plugin name as key.

Could you maybe try it with the case-sensitive name FastLogin?

**Comment by Feerko** [comment]
Still only []

**Comment by games647** [comment]
When do you check that value?

**Comment by Feerko** [comment]
On command (few minutes after login in)

**Comment by games647** [comment]
Are you marked as a premium player in FastLogin only then it sets that value? I get 

[org.bukkit.metadata.FixedMetadataValue@6f2b811]

using: 
        `System.out.println(player.getMetadata(core.getPlugin().getName()));`

**Comment by Feerko** [comment]
That's werid. I tried in few ways for non premium and premium players and I'm always getting []. Can you create a small api where can I get premium status of player? Thanks

**Comment by games647** [comment]
>That's werid

Could you post the code that you tried?

>and it will return true/false?

That's not possible, because we get the BungeeCord message delayed. What do you think about an `Optional<Boolean>`

**Comment by QUIQUELHAPPY** [comment]
https://i.imgur.com/WRf44nv.png I'm getting the same with this code an without bungeecord https://i.imgur.com/7I04ZbP.png

**Comment by games647** [comment]
Please try the code from the referenced commit: 

https://github.com/games647/FastLogin/blob/6d207d62ba1d99f08cd8c2613a4173bc3bf93f8a/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/FastLoginBukkit.java#L138-L149

**Comment by QUIQUELHAPPY** [comment]
should I import the plugin jar then?

**Comment by games647** [comment]
@QUIQUELHAPPY Yes

**Comment by QUIQUELHAPPY** [comment]
Imported: https://i.imgur.com/GRoQZFH.png
How can I invoke the code from this function? Sorry, I'm new "developing" minecraft plugins https://i.imgur.com/Q7DC2id.png

**Comment by games647** [comment]
@QUIQUELHAPPY Pseudo code

`JavaPlugin.getPlugin(FastLoginBukkit.class).getStatus(player.getUniqueId())`

**Comment by QUIQUELHAPPY** [comment]
https://i.imgur.com/97yptDN.png unresolved method, idk why, import seems OK

**Comment by games647** [comment]
@QUIQUELHAPPY Ensure you imported one of the latest dev-builds.

**Comment by QUIQUELHAPPY** [comment]
Seems working OK now, but, what does this return, a boolean or...? 😄

**Comment by games647** [comment]
@QUIQUELHAPPY 

>BTW: Will this be deprecated? https://i.imgur.com/kVO6uVt.png

Read the comment about deprecation in the Source-Code.

>Seems working OK now, but, what does this return, a boolean or...?

It returns an enum (like enumeration). Enums are fixed named data type values and this case it's a tristate (Premium, Cracked, Unknown).

**Comment by QUIQUELHAPPY** [comment]
https://i.imgur.com/4kug1rj.png I'm getting this error, do you know what I'm doing wrong? :)
```
[18:30:18 ERROR]: Could not pass event PlayerLoginEvent to guardian v1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:531) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:133) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: com.github.games647.fastlogin.bukkit.FastLoginBukkit.getStatus(Ljava/util/UUID;)Lcom/github/games647/fastlogin/core/PremiumStatus;
        at quiquelhappy.guardian.Main.onPlayerJoinEvent(Main.java:24) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-latest.jar:git-Spigot-4bd94dc-fb414fe]
        ... 13 more
```

**Comment by games647** [comment]
@QUIQUELHAPPY Outdated version installed.

**Comment by QUIQUELHAPPY** [comment]
damn you're right! Thank you!

**Comment by QUIQUELHAPPY** [comment]
I'm always getting unknown 🤔 
![imagen](https://user-images.githubusercontent.com/12534357/37983994-59c0f78c-31f5-11e8-8e4d-9be116b82acf.png)


![imagen](https://user-images.githubusercontent.com/12534357/37984021-6866aa2a-31f5-11e8-8e06-0f74dc018875.png)

**Comment by QUIQUELHAPPY** [comment]
I've tried to slow down the requests and I've waiting for a while and I can not manage to get if it is premium or no premium, all I get is unknown

**Comment by QUIQUELHAPPY** [comment]
working perfectly now, thanks 👍
