### ISSUE TITLE
client 1.13 + fastlogin

### ISSUE THREAD

**Issue by minecraft7net** [games647/FastLogin#217]
version
https://ci.codemc.org/job/Games647/job/FastLogin/839/

bungeecord b1343 or travertine b57

![image](https://user-images.githubusercontent.com/6265706/43106990-4caf7dc8-8edb-11e8-8818-163358677332.png)

`"...."
[00:39:45] [Server thread/ERROR]: Couldn't register custom payload
java.lang.IllegalArgumentException: Channel must be entirely lowercase
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:478) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at org.bukkit.craftbukkit.v1_13_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1203) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2434) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.PacketPlayInCustomPayload.a(SourceFile:45) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
"..."`

00:43:56 [INFO] [minecraft7net] disconnected with: §fInternal Exception: io.netty.handler.codec.DecoderException: net.minecraft.server.v1_13R1.ResourceKeyInvalidException: Non [a-z0-9.-] character in namespace of location: FastLogin:ForceAct

**Comment by games647** [comment]
Duplicate #216
