### ISSUE TITLE
spigot 1.13 - fastlogin b840

### ISSUE THREAD

**Issue by minecraft7net** [games647/FastLogin#219]
Hi,

another.

when loaded on bungee
[13:54:35] [main/INFO]: Loaded plugin FastLogin version 1.11-SNAPSHOT-260b93a by games647, https://github.com/games647/FastLogin/graphs/contributors
[13:54:36] [main/WARN] [fastlogin.hikari.HikariConfig]: FastLogin - idleTimeout is close to or more than maxLifetime, disabling it.
[13:54:36] [main/INFO] [fastlogin.hikari.HikariDataSource]: FastLogin - Starting...
[13:54:36] [main/INFO] [fastlogin.hikari.HikariDataSource]: FastLogin - Start completed.
[13:54:36] [main/INFO]: Enabled plugin FastLogin version 1.11-SNAPSHOT-260b93a by games647, https://github.com/games647/FastLogin/graphs/contributors

when loaded on spigot
[13:09:22] [Server thread/INFO]: [FastLogin] Loading FastLogin v1.11-SNAPSHOT-260b93a
[13:09:23] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.11-SNAPSHOT-260b93a
[13:10:00] [Server thread/INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook
[13:10:00] [Server thread/INFO]: [FastLogin] BungeeCord setting detected. No auth plugin is required

when client 1.13 connect to hub 1.8 and try to connect to spoigot 1.13

[13:55:07] [Server thread/ERROR]: Couldn't register custom payload
java.lang.IllegalArgumentException: Channel must be entirely lowercase
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:478) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at org.bukkit.craftbukkit.v1_13_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1203) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2434) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.PacketPlayInCustomPayload.a(SourceFile:45) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13-b1668.jar:git-Spigot-a85f7ec-5870145]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

[13:56:15] [Netty Worker IO Thread #0/INFO]: [minecraft7net] disconnected with: Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.server.v1_13R1.ResourceKeyInvalidException: Non [a-z0-9.-] character in namespace of location: FastLogin:force-act

![image](https://user-images.githubusercontent.com/6265706/43137002-c52b9e34-8f4a-11e8-86f5-23f28d0d4f0a.png)

**Comment by games647** [comment]
Stop spamming issues. Use existing ones.
