### ISSUE TITLE
2 NulPointerException with FastLogin V1.4

### ISSUE THREAD

**Issue by k-jiang** [games647/FastLogin#22]
1: BungeeCord error occurs while **cracked** player join the server every time.
> 21:22:51 [ERRO] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@10163d6, id=55, owner=com.github.games647.fastlogin.bungee.FastLoginBungee@58e1d9d, task=com.github.games647.fastlogin.bungee.tasks.ForceLoginTask@61879bb5, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
	at com.github.games647.fastlogin.bungee.tasks.ForceLoginTask.run(ForceLoginTask.java:32)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2: Spigot/Bukkit error occurs while **premium** player join the server. It shows up at the first time only and the premium player gets no auto login no meter how many time he/she re-join the game:
> [21:16:41] [Server thread/WARN]: Could not pass incoming plugin message to FastLogin v1.4
java.lang.NullPointerException
	at com.github.games647.fastlogin.bukkit.listener.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:71) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:2485) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInCustomPayload.a(SourceFile:58) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInCustomPayload.a(SourceFile:8) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

Environment:
FastLogin 1.4 from https://www.spigotmc.org/resources/fastlogin.14153/history
ProtocolLib 4.0.1
BungeeCord build 1158 http://ci.md-5.net/job/BungeeCord/1158/
Spigot 1.9.4 build 849
AuthMe 3.4 fixed with spigot BuildTools 1.9

P.S. Interestingly I tried to download the source code from github and build with mvn. it loads fine in spigot and bungee yet shows the same errors above.

**Comment by k-jiang** [comment]
Config:
autoRegister: false
premiumUuid: true
nameChangeCheck: true
forwardSkin: true
MySQL used.

**Comment by games647** [comment]
Your Proxy-Id list is empty. Please check if there is an error on startup.

**Comment by k-jiang** [comment]
There is no error on startup. My proxy-whitelist.txt is also not empty. I have tried to encode the txt file with both UTF-8 NO-BOM and ANSI and problem remains the same (bukkit/spigot side NPE). Also, switching between Windows (\r\n), UNIX (\n) and MAC (\r) line-ending-style makes no different. (I tested on Windows 7)

The format I put on proxy-whitelist.txt is like this:
> 2892xxxx-xxxx-xxxx-xxxx-xxxxxxxxc840
f591xxxx-xxxx-xxxx-xxxx-xxxxxxxx0bbf
a999xxxx-xxxx-xxxx-xxxx-xxxxxxxx304d

When I put only one bungee on the file (only one line), it keeps the same NPE.

If I remove the dash line inside the bungee stats uuid, it gives error:
> [04:02:32] [Server thread/ERROR]: [FastLogin] Failed to retrieve proxy Id. Disabling BungeeCord support
java.lang.IllegalArgumentException: Invalid UUID string: 2892xxxxxxxxxxxxxxxxxxxxxxxxc840
	at java.util.UUID.fromString(Unknown Source) ~[?:1.8.0_92]
	at com.github.games647.fastlogin.bukkit.listener.BungeeCordListener.loadBungeeCordIds(BungeeCordListener.java:119) [FastLogin-1.4.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.BungeeCordListener.<init>(BungeeCordListener.java:41) [FastLogin-1.4.jar:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:85) [FastLogin-1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

I have tried basically everything I can so please help me out!

**Comment by games647** [comment]
Okay, I'm really stupid. Sorry

**Comment by games647** [comment]
I forgot to save the ids in memory.

**Comment by games647** [comment]
Could you try it?

https://github.com/games647/FastLogin/releases/tag/1.5.1

**Comment by k-jiang** [comment]
1.5.1 runs perfectly well. Good job!

**Comment by games647** [comment]
Thank you very much for the info.
