### ISSUE TITLE
Resume lost connection to a remote database

### ISSUE THREAD

**Issue by k-jiang** [games647/FastLogin#227]
We are using a remote MySQL database for FastLogin. Usually it is reliable yet in sometimes connection to the remove db could be lost when network were unstable.

I found out that FastLogin seems not be able to resume from a lost MySQL connection, even when the network is stable again. The Bungeecord server prevents player from join with this exception:
```
[13:49:35 ERROR] [FastLogin]: Failed to query profile: kjiang
java.sql.SQLTransientConnectionException: FastLogin - Connection is not available, request timed out after 30000ms.
        at fastlogin.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676) ~[?:?]
        at fastlogin.hikari.pool.HikariPool.getConnection(HikariPool.java:190) ~[?:?]
        at fastlogin.hikari.pool.HikariPool.getConnection(HikariPool.java:155) ~[?:?]
        at fastlogin.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
        at com.github.games647.fastlogin.core.AuthStorage.loadProfile(AuthStorage.java:90) ~[?:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:23) ~[?:?]
        at com.github.games647.fastlogin.bungee.task.AsyncPremiumCheck.run(AsyncPremiumCheck.java:38) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
Note that at this moment I can connect to the MySQL DB by `mysql -u xxx -p` with no problem. I have to restart the Bungee server in order to restore it.

Tested with:
[Waterfall](https://aquifermc.org/pages/about-waterfall/)(A fork of BungeeCord) [build 215](https://destroystokyo.com/ci/job/Waterfall/215/changes)
FastLogin 1.11 [build 845](https://ci.codemc.org/job/Games647/job/FastLogin/845/)

**Comment by games647** [comment]
According to the HikariCP Github page, the database should already try to reconnect.

>The delay between retries will slowly increase from 250ms up to connectionTimeout (30 seconds by default).

**Comment by k-jiang** [comment]
This shows up during server startup, not sure if it is the problem:
```
[12:59:46 WARN] [fastlogin.hikari.HikariConfig]: FastLogin - idleTimeout is close to or more than maxLifetime, disabling it.
[12:59:46 INFO] [fastlogin.hikari.HikariDataSource]: FastLogin - Starting...
[12:59:47 INFO] [fastlogin.hikari.HikariDataSource]: FastLogin - Start completed.
[12:59:47 INFO]: Enabled plugin FastLogin version 1.11-SNAPSHOT-101f720 by games647, https://github.com/games647/FastLogin/graphs/contributors
```
Startup time is definitely less than 30s (under 10s). The warning shows up almost instantly during startup.

**Comment by games647** [comment]
This **warning** is unrelated and will be fixed in future builds. It's an invalid configuration of **default** values.
