### ISSUE TITLE
Random Auto-LogIn for Premium

### ISSUE THREAD

**Issue by ludgart** [games647/FastLogin#23]
Sometime premium player need to login via Authme last version.
The problem is, the player dont know the password, because auto-register (gen random password).
I can solve the problem manually with the command /premium name.
And the player losing ranks / skins / stuff.
Im using the lastest version and I have no error codes.

**Comment by games647** [comment]
Could be a bug of the previous version. Are you sure the players are saved as premium in the database.

**Comment by ludgart** [comment]
For few minutes I player was as cracked detected, I did /premium name and problem was solved.
https://gyazo.com/5123363b16cbdb9def336d5d59993558

**Comment by games647** [comment]
And what about new player, because it looks like it works for me using the last recent version.

**Comment by ludgart** [comment]
Not tested yet, but my old players are still buggy. A database clear could solve the problem?

**Comment by games647** [comment]
I don't have any problems like you described. Maybe that would help.

**Comment by ludgart** [comment]
The Problem is not solved for me. I updated to newest version.

**Comment by games647** [comment]
Which AuthMe version do you use?

**Comment by games647** [comment]
Bukkit or BungeeCord?

**Comment by games647** [comment]
Which version do you used? 1.5.2 or the one directly from the source code?

**Comment by ludgart** [comment]
BungeeCord
Authme version 5.2 (Snapshot 1035).
FastLogin 1.5.1

I see, some players produce this error:

13:59:19 [INFORMATION] [Rodrimdom] <-> ServerConnector [skyblock] has connected
13:59:19 [SCHWERWIEGEND] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@5023bb8b, id=138609, owner=com.github.games647.fastlogin.bungee.FastLoginBungee@12ed9db6, task=com.github.games647.fastlogin.bungee.tasks.ForceLoginTask@41220254, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
13:59:20 [INFORMATION] [Rodrimdom] <-> DownstreamBridge <-> [lobby] has disconnected

**Comment by games647** [comment]
What's full error of the NullPointerException? I need the stack trace.

**Comment by ludgart** [comment]
I know it, but I have only this error from the BungeeCord Server.
I watched in my spigot server and sometime a get from authme?:

[20:25:27 INFO]: [AuthMe] SpeciaIGames logged in!
[20:25:27 WARN]: Exception in thread "pool-4-thread-130" 
[20:25:27 WARN]: net.minecraft.server.v1_8_R3.CancelledPacketHandleException
[20:25:28 WARN]: Exception in thread "pool-4-thread-131" 
[20:25:28 WARN]: net.minecraft.server.v1_8_R3.CancelledPacketHandleException
[20:25:28 WARN]: Exception in thread "pool-4-thread-132" 
[20:25:28 WARN]: net.minecraft.server.v1_8_R3.CancelledPacketHandleException
[20:25:28 WARN]: Exception in thread "pool-4-thread-133" 
[20:25:28 WARN]: net.minecraft.server.v1_8_R3.CancelledPacketHandleException
[20:25:28 WARN]: Exception in thread "pool-4-thread-129" 
[20:25:28 WARN]: net.minecraft.server.v1_8_R3.CancelledPacketHandleException
[20:25:28 WARN]: Exception in thread "pool-4-thread-135" 
[20:25:28 WARN]: net.minecraft.server.v1_8_R3.CancelledPacketHandleException
[20:25:28 WARN]: Exception in thread "pool-4-thread-134" 
[20:25:28 WARN]: net.minecraft.server.v1_8_R3.CancelledPacketHandleException

**Comment by games647** [comment]
Really no stacktrace? That's weird. Do you have a plugin which prevent stacktraces?

**Comment by games647** [comment]
Do you use Waterfall?

**Comment by ludgart** [comment]
I can't find a stacktrace.No plugin prevent a stacktrace, earlier I got from my plugin some stacktraces.
Im not using Waterfall.

**Comment by games647** [comment]
What do you mean by earlier? On the startup?

**Comment by ludgart** [comment]
With my plugin, not from your plugin. I have no plugin that prevent a stacktrace.

**Comment by games647** [comment]
Could you try that one: https://github.com/games647/FastLogin/releases/tag/debug-bungee

**Comment by ludgart** [comment]
I install it later, because I cant stop the server, because to many players are online. Thanks.

**Comment by games647** [comment]
Any progress?

**Comment by ludgart** [comment]
Hello,

sorry for my late reply, but here is the error:

15:41:03 [INFORMATION] [FastLogin] ERROR ON FORCE LOGIN
java.lang.NullPointerException
    at com.github.games647.fastlogin.bungee.tasks.ForceLoginTask.run(ForceLoginTask.java:34)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

I think you added a debug message on the login event.

**Comment by games647** [comment]
This exactly what I needed

**Comment by games647** [comment]
Could you send me your config?

**Comment by games647** [comment]
Should be fixed now. https://github.com/games647/FastLogin/releases/tag/1-9
