### ISSUE TITLE
Channel must contain : separator (attempted to use FastLogin)

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [games647/FastLogin#232]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
Not working on 1.13

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
git-Paper-319 (MC: 1.13.1)

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432
### Error Log:
[//]: # (No images please - only the textual representation)
```
02.10 16:01:24 [Server] INFO [FastLogin] Enabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432*
02.10 16:01:24 [Server] ERROR Error occurred while enabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432 (Is it up to date?)
02.10 16:01:24 [Server] INFO java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use FastLogin)
02.10 16:01:24 [Server] INFO at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[PaperSpigot-1.13.1-b319.jar:git-Paper-319]
02.10 16:01:24 [Server] INFO at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:209) ~[PaperSpigot-1.13.1-b319.jar:git-Paper-319]
02.10 16:01:24 [Server] INFO at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:72) ~[?:?]
02.10 16:01:24 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[PaperSpigot-1.13.1-b319.jar:git-Paper-319]
02.10 16:01:24 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[PaperSpigot-1.13.1-b319.jar:git-Paper-319]
02.10 16:01:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[PaperSpigot-1.13.1-b319.jar:git-Paper-319]
02.10 16:01:24 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[PaperSpigot-1.13.1-b319.jar:git-Paper-319]
```

**Comment by games647** [comment]
Outdated plugin version. Please download a dev-build.

**Comment by ax3lt** [comment]
Not working also with latest version
