### ISSUE TITLE
FastLogin error (PaperSpigot 1.8.8)

### ISSUE THREAD

**Issue by ghost** [games647/FastLogin#234]
[14:43:39 ERROR]: [FastLogin] Couldn't enable encryption
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.encryptConnection(VerifyResponseTask.java:148) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:70) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:54) [FastLogin.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [spigot.jar:git-TacoSpigot-bf023c7d]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-TacoSpigot-bf023c7d]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.NoSuchElementException: splitter
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) ~[spigot.jar:git-TacoSpigot-bf023c7d]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157) ~[spigot.jar:git-TacoSpigot-bf023c7d]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150) ~[spigot.jar:git-TacoSpigot-bf023c7d]
        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:272) ~[?:?]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:258) ~[spigot.jar:git-TacoSpigot-bf023c7d]
        ... 12 more
[14:43:39 ERROR]: [FastLogin] Couldn't enable encryption

**Comment by games647** [comment]
This isn't PaperSpigot

>~[spigot.jar:git-TacoSpigot-bf023c7d]

Could you try it out with PaperSpigot please?

**Comment by AntoLuMeju99** [comment]
It is TacoSpigot

**Comment by games647** [comment]
Yes, so could you please test it PaperSpigot?

**Comment by AntoLuMeju99** [comment]
FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432
