### ISSUE TITLE
Doss attack

### ISSUE THREAD

**Issue by xion87** [games647/FastLogin#276]
hi i just noticed people recently have fun attacking my server to port 80, so fastlogin is unable to comunicate with mojang server trowing this error https://gist.github.com/xion87/e6e8775da95d06153a3e617e33ea1665
I am using fastlogin 1.11-SNAPSHOT-62a8b93  at bungee/login/hub1/hub2
there is any thing that i can do for prevent it? i am using ovh dedicate

**Comment by games647** [comment]
First of all this error is about DNS requests. (port 53 I believe) Furthermore how the port 80 related to this. FastLogin connecting to the Mojang API strictly using HTTPS (TLS -> port 443). Even then port 443 is the target server port, not the local port used to hold this connection. You can verify this for example using the Linux tool `ss -t`.

**Comment by xion87** [comment]
so i can just limit the maximum connection to that port? or what you suggest? using iptables maybe

**Comment by games647** [comment]
Yes you can block that port, but maybe you should allow outgoing TCP connections in case any plugin requires HTTP (not HTTPS) connection. However, nowadays with certificate services like `Let's Encrypt` all services should use HTTPS every time.

**Comment by games647** [comment]
Besides `IPTables` are also easier solutions like `ufw`. IMO it's easier to manage it.

**Comment by xion87** [comment]
the problem that i use also ptero  panel for manage my server and are all dockered

**Comment by games647** [comment]
>[/127.0.0.11:53] query timed out after 5000 milliseconds

Could please check if your local DNS server port is closed to the public? This sounds more like an attack (or just a crashed one) on the local resolver.

**Comment by xion87** [comment]
it happen only when i get the email from ovh that my server is under attack

**Comment by games647** [comment]
I don't know how OVH DDOS protection works, but maybe it blocks DNS requests on the OVH DNS server if that happens. You could try to switch to different DNS provider.

**Comment by xion87** [comment]
I use cloudflare as dns provider... Maybe is that

Il dom 20 ott 2019, 20:26 games647 <notifications@github.com> ha scritto:

**Comment by games647** [comment]
No I meant the DNS server that is used **by** your server and not pointing to your server.

**Comment by sgdc3** [comment]
What about defining "143.204.5.174 sessionserver.mojang.com" in your hosts file?

**Comment by xion87** [comment]
same issue
`[17:39:03] [Netty Worker IO Thread #7/INFO]: [/95.234.27.128:49215|sossimone] <-> DownstreamBridge <-> [hub-1] has disconnected
[17:39:03] [Netty Worker IO Thread #11/INFO]: [/5.88.100.246:36683|agomon] <-> DownstreamBridge <-> [login] has disconnected
[17:39:05] [Netty Worker IO Thread #44/ERROR]: Error authenticating Tosto777 with minecraft.net
java.net.UnknownHostException: failed to resolve 'sessionserver.mojang.com' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:382) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:220) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:170) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/127.0.0.11:53] query timed out after 5000 milliseconds (no stack trace available)
[17:39:07] [Netty Worker IO Thread #61/INFO]: [KilledSam|/151.34.50.23:50231] <-> ServerConnector [thepit] has connected
[17:39:08] [Netty Worker IO Thread #61/INFO]: [/151.34.50.23:50231|KilledSam] <-> DownstreamBridge <-> [kitpvp] has disconnected
[17:39:08] [Netty Worker IO Thread #13/INFO]: [/5.88.111.26:50806|coolgirl1] <-> DownstreamBridge <-> [luckywars] has disconnected
[17:39:08] [Netty Worker IO Thread #35/INFO]: [ash1987|/37.183.21.146:30536] <-> ServerConnector [hub-1] has connected
[17:39:09] [Netty Worker IO Thread #35/INFO]: [/37.183.21.146:30536|ash1987] <-> DownstreamBridge <-> [login] has disconnected
[17:39:10] [Netty Worker IO Thread #23/INFO]: [matteo_pro|/151.52.203.30:58326] <-> ServerConnector [thepit] has connected
[17:39:10] [Netty Worker IO Thread #23/INFO]: [/151.52.203.30:58326|matteo_pro] <-> DownstreamBridge <-> [kitpvp] has disconnected
[17:39:11] [Netty Worker IO Thread #70/WARN] [BungeePacketLimiter]: Alienoid35 is sending over 155 packets per second!
[17:39:14] [Netty Worker IO Thread #11/INFO]: [agomon|/5.88.100.246:36683] <-> ServerConnector [practice] has connected
[17:39:15] [Netty Worker IO Thread #11/INFO]: [/5.88.100.246:36683|agomon] <-> DownstreamBridge <-> [hub-1] has disconnected
[17:39:17] [Netty Worker IO Thread #29/ERROR]: Error authenticating Tosto777 with minecraft.net
java.net.UnknownHostException: failed to resolve 'sessionserver.mojang.com' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:382) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:220) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:170) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`
