### ISSUE TITLE
Database: ClassCastException: java.lang.String cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by WhiteSkyAngel** [games647/FastLogin#280]
Errors:

20:43:56 [WARNING] Exception encountered when loading plugin: FastLogin
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:159)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:44)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

19:39:01 [SEVERE] Nov 07, 2019 7:39:01 PM fastlogin.hikari.HikariDataSource <init>
INFO: FastLogin - Starting...

19:39:01 [SEVERE] Nov 07, 2019 7:39:01 PM fastlogin.hikari.pool.HikariPool throwPoolInitializationException
SEVERE: FastLogin - Exception during pool initialization.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Can you help me ?
Please.

**Comment by games647** [comment]
If your password or username only consists of numbers wrap them around into `''`
