### ISSUE TITLE
AuthActionEvent cannot be triggered asynchronously from another thread.

### ISSUE THREAD

**Issue by jusobreira** [games647/FastLogin#315]
03.04 00:48:49 [Server] INFO [00:48:49] [Server thread/WARN]: [FastLogin] Loaded class com.lenis0012.bukkit.loginsecurity.session.AuthAction from LoginSecurity v2.1.9 which is not a depend, softdepend or loadbefore of this plugin.
03.04 00:48:49 [Server] INFO [00:48:49] [Server thread/INFO]: [FastLogin] Hooking into auth plugin: LoginSecurity
03.04 00:48:59 [Server] INFO [00:48:59] [Craft Scheduler Thread - 10/INFO]: [FastLogin] Player jusobreira has a verified premium account
03.04 00:48:59 [Server] INFO [00:48:59] [User Authenticator #1/INFO]: Disconnecting com.mojang.authlib.GameProfilelegacy=false]
03.04 00:49:29 [Server] INFO [00:49:29] [Craft Scheduler Thread - 8/INFO]: Initialized items.yml
03.04 00:49:44 [Server] INFO [00:49:44] [Craft Scheduler Thread - 7/INFO]: [FastLogin] Player jusobreira has a verified premium account
03.04 00:49:44 [Server] INFO [00:49:44] [User Authenticator #3/INFO]: UUID of player jusobreira is XXXXXXXXXXXXXXXXXXXXXXX

03.04 00:50:05 [00:50:05] [Server thread/INFO]: jusobreira ran command Message of the Day
03.04 00:50:06 [Server] INFO [00:50:06] [Server thread/INFO]: ---------------[ Player List ]---------------
03.04 00:50:06 [Server] INFO [00:50:06] [Server thread/INFO]: Online Players 1/100: jusobreira

03.04 00:50:08 [Server] INFO [00:50:08] [Craft Scheduler Thread - 16/INFO]: [FastLogin] Register player jusobreira
03.04 00:50:08 [Server] INFO [00:50:08] [Craft Scheduler Thread - 16/WARN]: [FastLogin] ERROR ON FORCE LOGIN
03.04 00:50:08 [Server] INFO java.lang.IllegalStateException: AuthActionEvent cannot be triggered asynchronously from another thread.
03.04 00:50:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
03.04 00:50:08 [Server] INFO at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:158) ~[LoginSecurity-2.1.9-Bukkit.jar:?]
03.04 00:50:08 [Server] INFO at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:153) ~[LoginSecurity-2.1.9-Bukkit.jar:?]
03.04 00:50:08 [Server] INFO at com.github.games647.fastlogin.bukkit.hooks.LoginSecurityHook.forceRegister(LoginSecurityHook.java:43) ~[FastLogin.jar:?]
03.04 00:50:08 [Server] INFO at com.github.games647.fastlogin.bukkit.hooks.LoginSecurityHook.forceRegister(LoginSecurityHook.java:20) ~[FastLogin.jar:?]
03.04 00:50:08 [Server] INFO at com.github.games647.fastlogin.core.shared.ForceLoginManagement.forceRegister(ForceLoginManagement.java:77) ~[FastLogin.jar:?]
03.04 00:50:08 [Server] INFO at com.github.games647.fastlogin.core.shared.ForceLoginManagement.run(ForceLoginManagement.java:45) [FastLogin.jar:?]
03.04 00:50:08 [Server] INFO at com.github.games647.fastlogin.bukkit.tasks.ForceLoginTask.run(ForceLoginTask.java:35) [FastLogin.jar:?]
03.04 00:50:08 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
03.04 00:50:08 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
03.04 00:50:08 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
03.04 00:50:08 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
03.04 00:50:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
03.04 00:50:09 [Server] INFO [00:50:09] [Craft Scheduler Thread - 7/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 31.025ms!
03.04 00:50:09 [Server] INFO [00:50:09] [Craft Scheduler Thread - 7/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 63.912ms!
03.04 00:50:10 [Server] INFO [00:50:10] [Craft Scheduler Thread - 7/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 72.957ms!
03.04 00:50:10 [Server] INFO [00:50:10] [Craft Scheduler Thread - 7/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 45.03ms!
03.04 00:50:10 [Server] INFO [00:50:10] [Craft Scheduler Thread - 7/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 66.678ms!
03.04 00:50:10 [Server] INFO [00:50:10] [Craft Scheduler Thread - 7/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 59.432ms!
03.04 00:50:10 [Server] INFO [00:50:10] [Craft Scheduler Thread - 7/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 28.38ms!
03.04 00:50:10 [Server] INFO [00:50:10] [Craft Scheduler Thread - 7/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 96.532ms!
03.04 00:50:12 [Server] INFO [00:50:12] [Server thread/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 61.981ms!
03.04 00:50:12 [Server] INFO [00:50:12] [Server thread/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 35.604ms!
03.04 00:50:12 [Server] INFO [00:50:12] [Server thread/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 85.69ms!
03.04 00:50:12 [Server] INFO [00:50:12] [Server thread/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 88.735ms!
03.04 00:50:12 [Server] INFO [00:50:12] [Server thread/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 72.725ms!
03.04 00:50:12 [Server] INFO [00:50:12] [Server thread/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 46.667ms!
03.04 00:50:27 [Server] INFO [00:50:27] [Craft Scheduler Thread - 9/INFO]: [FastLogin] Player AdvancedGames has a verified premium account
03.04 00:50:27 [Server] INFO [00:50:27] [User Authenticator #4/INFO]: UUID of player AdvancedGames is fxxxxxxxxxxxxxxxxxxxxx

03.04 00:50:34 [Server] INFO [00:50:34] [Craft Scheduler Thread - 4/INFO]: [FastLogin] Register player AdvancedGames
03.04 00:50:34 [Server] INFO [00:50:34] [Craft Scheduler Thread - 4/WARN]: [FastLogin] ERROR ON FORCE LOGIN
03.04 00:50:34 [Server] INFO java.lang.IllegalStateException: AuthActionEvent cannot be triggered asynchronously from another thread.
03.04 00:50:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
03.04 00:50:34 [Server] INFO at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:158) ~[LoginSecurity-2.1.9-Bukkit.jar:?]
03.04 00:50:34 [Server] INFO at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:153) ~[LoginSecurity-2.1.9-Bukkit.jar:?]
03.04 00:50:34 [Server] INFO at com.github.games647.fastlogin.bukkit.hooks.LoginSecurityHook.forceRegister(LoginSecurityHook.java:43) ~[FastLogin.jar:?]
03.04 00:50:34 [Server] INFO at com.github.games647.fastlogin.bukkit.hooks.LoginSecurityHook.forceRegister(LoginSecurityHook.java:20) ~[FastLogin.jar:?]
03.04 00:50:34 [Server] INFO at com.github.games647.fastlogin.core.shared.ForceLoginManagement.forceRegister(ForceLoginManagement.java:77) ~[FastLogin.jar:?]
03.04 00:50:34 [Server] INFO at com.github.games647.fastlogin.core.shared.ForceLoginManagement.run(ForceLoginManagement.java:45) [FastLogin.jar:?]
03.04 00:50:34 [Server] INFO at com.github.games647.fastlogin.bukkit.tasks.ForceLoginTask.run(ForceLoginTask.java:35) [FastLogin.jar:?]
03.04 00:50:34 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
03.04 00:50:34 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
03.04 00:50:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
03.04 00:50:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
03.04 00:50:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by games647** [comment]
Please update to a development build.

**Comment by jusobreira** [comment]
It worked. Tnx
