### ISSUE TITLE
[FastLogin] Failed to verify session

### ISSUE THREAD

**Issue by mastermc05** [games647/FastLogin#325]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
on login with my premium acount
[16:02:13 WARN]: [FastLogin] Failed to verify session

### What behaviour is expected:
[//]: # (What did you expect?)
to login
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
after restart i never can join in first 5 minutes , after if i'm lucky 
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
[//]: # (This can be found by running `/pl`)
https://hastebin.com/ulafimapoh.cs
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Server-Software: PAPERSPIGOT
Server-Version: 1.12.2
JAVA: OPENJDK-11 (but on java 8 was the same)
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
 FastLogin 1.10-git484855724b794de1fe057cf7360245362658b432
### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://hastebin.com/mizedesudo.md
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://hastebin.com/ivadofanal.makefile

**Comment by AlphaBs** [comment]
I have same error. 
`org.json.simple.parser.ParseException: null
    at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[JSONParser.class:?]
    at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[JSONParser.class:?]
    at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[JSONParser.class:?]
    at org.json.simple.JSONValue.parseWithException(JSONValue.java:78) ~[JSONValue.class:?]
    at com.github.games647.fastlogin.bukkit.MojangApiBukkit.hasJoinedServer(MojangApiBukkit.java:47) [FastLogin.jar:?]
    at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:84) [FastLogin.jar:?]
    at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:54) [FastLogin.jar:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [CraftTask.class:git-CatServerAsync-1.12.2-41eb28c]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServerAsync-1.12.2-41eb28c]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by mastermc05** [comment]
i found FastLogin 1.11-SNAPSHOT-5b1b609 on this github and it works fine , please update it to https://www.spigotmc.org , because other can have this bug too

**Comment by AlphaBs** [comment]
Thanks! it works

**Comment by games647** [comment]
Looks like Mojang changed something in their API. That made the old JSON parser incompatible. Strange...

**Comment by choco3224** [comment]
when a premium user uses the / premium and exits when reconnecting it puts ¨invalid session¨

**Comment by games647** [comment]
@choco3224 Update to a development build. It's already fixed.

**Comment by choco3224** [comment]
where do i find that update?

**Comment by games647** [comment]
@choco3224 https://github.com/games647/FastLogin#development-builds and then click on the build on the left side.

**Comment by ZarkxWorld** [comment]
hi, there're some build for 1.7.10 without "invalid session" issue? thx

**Comment by games647** [comment]
https://ci.codemc.io/job/Games647/job/FastLogin/912/

**Comment by ZarkxWorld** [comment]
> https://ci.codemc.io/job/Games647/job/FastLogin/912/

hi, i put this in my thermos 1.7.10, but don't work, i can put /premium or /cracked bu when i login another time i need put my offline password

**Comment by games647** [comment]
Please open another issue, because it's not related to this ticket.
