### ISSUE TITLE
Problem with Bungee connexion

### ISSUE THREAD

**Issue by Matthysse** [games647/FastLogin#356]
Hello!

I installed FastLoginBukkit on my lobby (with AuthMe reloaded) and on the Bungeecord server (with AuthmeBungee). (Spigot 1.12.2) The problem is I set the stats ID (from the Bungeecord config) in the proxy-whitelist file and it does FastLogin on the lobby doesn't seem to find Bungee.

**Comment by games647** [comment]
Please post the bungee log.

**Comment by Matthysse** [comment]
Here it is, sorry if this isn't on pastbin, it's too large for them.
[logs.zip](https://github.com/games647/FastLogin/files/4707837/logs.zip)

**Comment by games647** [comment]
Please take a look at the last step of the setup guide. You still have SQLite configured. 

>11:31:29 [WARNING] Exception encountered when loading plugin: FastLogin
java.lang.RuntimeException: Failed to load driver class org.sqlite.JDBC in either of HikariConfig class loader or Thread context classloader
	at fastlogin.hikari.HikariConfig.setDriverClassName(HikariConfig.java:486)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:162)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:51)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Matthysse** [comment]
Problem solved thanks for the quick replies ! Just make sure the noobs like me understand how to configure the database, the tutorial doesn't help that much for that. You just saved my server, it's the perfect plugin, we have as premiums our real uuids, and we are separate from the cracked versions. It's the best of both worlds ! Keep it updated, cheers !
