### ISSUE TITLE
MariaDB with fastlogin

### ISSUE THREAD

**Issue by Ariel01X** [games647/FastLogin#370]
Hey , I wanna use mariadb database for my bungeecord and spigot hub , But can't seem to make it work. this is how my configuration looks for the bungeecord fastlogin config and the spigot hub config. Of course db_name , username and pass are placeholders.

driver: 'com.mysql.jdbc.Driver'
host: 'localhost'
port: 3306
database: 'db_name'
username: 'username'
password: 'pass'

And when I go ingame and type /premium it says " sending request (dont forget to follow the bungeecord guide) "

This is the error log in console: 

15:27:59 [WARNING] Exception encountered when loading plugin: FastLogin
java.lang.RuntimeException: Failed to load class of driverClassName [org.sqlite.JDBC] in either of HikariConfig class loader or Thread context classloader
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:334)
	at com.github.games647.fastlogin.core.AuthStorage.<init>(AuthStorage.java:34)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:167)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:44)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15

And this is my full startup log (bungeecord)
: https://pastebin.com/CFhXX8CM

I'm probably doing something wrong , Will appreciate it very much if you can help me. Thanks for your time , @games647

**Comment by games647** [comment]
Do you uncommented the SQLite driver, because it still tries to load that one.

**Comment by Ariel01X** [comment]
Nope , It's commented

**Comment by Ariel01X** [comment]
@games647  maybe I need to change the driver name?

**Comment by games647** [comment]
>@games647 maybe I need to change the driver name?

No It's the same. The driver is still compatible with both systems. However could you update to dev build. Maybe it's already fixed there.

**Comment by Ariel01X** [comment]
I'll try.

**Comment by Ariel01X** [comment]
Nope , and this is the error in the bungeecord server  
 [INFO] Enabled plugin AuthMeBungee version 2.2.0-beta1 by AuthMeTeam
04:41:38 [SEVERE] Jun 27, 2020 4:41:38 AM com.zaxxer.hikari.HikariConfig setDriverClassName
SEVERE: Failed to load class of driverClassName org.sqlite.JDBC in either of HikariConfig class classloader net.md_5.bungee.api.plugin.PluginClassloader@188715b5 or Thread context classloader sun.misc.Launcher$AppClassLoader@70dea4e

04:41:38 [WARNING] Exception encountered when loading plugin: FastLogin
java.lang.RuntimeException: Failed to load class of driverClassName [org.sqlite.JDBC] in either of HikariConfig class loader or Thread context classloader
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:334)
	at com.github.games647.fastlogin.core.AuthStorage.<init>(AuthStorage.java:34)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:167)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:44)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)




@games647  maybe I need to configure something with stats id? I heard something about it and that I need to put it in proxy whitelist or something.. no idea though

**Comment by games647** [comment]
Could you post the config file. I guess something went wrong reading it.

**Comment by Ariel01X** [comment]
Yes. https://pastebin.com/Mj5YQHXY @games647

**Comment by games647** [comment]
Okay that's strange. That should work fine. Is this the configuration file of FastLogin on BungeeCord?

**Comment by Ariel01X** [comment]
bungeecord , Is there any chance we can discuss this on discord? It's quicker for me to check on it and we're releasing our server very soon so I wanna solve it @games647

**Comment by Ariel01X** [comment]
My discord is Ariel#9732 , Please add me asap. @games647

**Comment by Ariel01X** [comment]
Fixed. To All those that might have the same problem as me , you need to put localhost instead of your ip in host: 'localhost'
Thank you @games647  For the help anyways Though ! Closing.
