### ISSUE TITLE
PlaceholderAPI 2.10.7 error with FastLogin

### ISSUE THREAD

**Issue by andris155** [games647/FastLogin#386]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
Fastlogin write this error when I stop server.
```
[11:41:22] [Server thread/INFO]: [FastLogin] Disabling FastLogin v1.11-SNAPSHOT-cae2f8f
[11:41:22] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: FastLogin
[11:41:22] [Server thread/INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
[11:41:22] [Server thread/ERROR]: Error occurred while disabling FastLogin v1.11-SNAPSHOT-cae2f8f (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean me.clip.placeholderapi.PlaceholderAPI.unregisterPlaceholderHook(java.lang.String)'
	at com.github.games647.fastlogin.bukkit.PremiumPlaceholder.unregisterAll(PremiumPlaceholder.java:19) ~[?:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onDisable(FastLoginBukkit.java:107) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.16.1.jar:git-Paper-127]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.disablePlugins(CraftServer.java:434) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:775) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1048) ~[patched_1.16.1.jar:git-Paper-127]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-127]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

### What behaviour is expected:
[//]: # (What did you expect?)
No write this error.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
1. Install Fastlogin and PlaceholderAPI 2.10.7 plugin.
2. Start server.
3. Stop server.

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
[//]: # (This can be found by running `/pl`)

Plugins (30): AuthMe, BetterGUI, ChatControl, Citizens, ConditionalCommands, CoreProtect, EasySetSpawn*, FastLogin, HolographicDisplays, HolographicExtension, ImageMaps, ItemJoin, LuckPerms, NoCheatPlus, PlaceholderAPI, PlayerVedelem, PlugMan, ProtocolLib, SkinsRestorer, StaffChat, SuperTrailsPro*, TitleManager, Vault, VaultChatFormatter*, ViaBackwards, ViaVersion, WDLCompanion*, WorldBorder, WorldEdit, WorldGuard

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Minecraft 1.16.1, SQLite

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
v1.11-SNAPSHOT-cae2f8f

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file

**Comment by games647** [comment]
Great a breaking change between two followed version in combination with a version number change that is normally only used for bug fix releases.
