### ISSUE TITLE
Premium Account is shown "Invalid session"

### ISSUE THREAD

**Issue by octo-kumo** [games647/FastLogin#397]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
Premium accounts can not login, and are shown "Invalid session"

### What behaviour is expected:
[//]: # (What did you expect?)
Premium accounts able to login automatically

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
1. Install FastLogin
2. Install LoginSecurity

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
<img width="546" alt="Screenshot 2020-08-30 at 10 41 29 AM" src="https://user-images.githubusercontent.com/26460801/91650062-61d7dd00-eaad-11ea-9ba1-a8fde20c0723.png">

### Plugin list:
[//]: # (This can be found by running `/pl`)

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
```
Plugins (15): LuckPerms, LoginSecurity, PlaceholderAPI, ViaVersion, Vault, ViaBackwards, ProtocolLib, FastLogin, 
BossShopPro, Essentials, PlayerShops, EssentialsChat, ChatItemDisplay, DiscordSRV, IridiumSkyblock
```

### Server Log:
```stack
[02:38:54] [Craft Scheduler Thread - 36/WARN]: [FastLogin] Failed to verify session
org.json.simple.parser.ParseException: null
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[server.jar:git-Spigot-b5a13e6-3f57283]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[server.jar:git-Spigot-b5a13e6-3f57283]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[server.jar:git-Spigot-b5a13e6-3f57283]
	at org.json.simple.JSONValue.parseWithException(JSONValue.java:78) ~[server.jar:git-Spigot-b5a13e6-3f57283]
	at com.github.games647.fastlogin.bukkit.MojangApiBukkit.hasJoinedServer(MojangApiBukkit.java:47) [FastLogin.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:84) [FastLogin.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:54) [FastLogin.jar:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) [server.jar:git-Spigot-b5a13e6-3f57283]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-b5a13e6-3f57283]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[02:38:54] [Server thread/INFO]: /**.***.**.***:* lost connection: Disconnected
```

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/tovaqoyoza.makefile)

**Comment by games647** [comment]
Update the plugin version to a dev build. Already fixed.
