### ISSUE TITLE
I can't get the fastlogin plugin to work

### ISSUE THREAD

**Issue by JayJLV** [games647/FastLogin#420]
Hello im asking a small question because i cant understand how it works.
I did everything as said in https://github.com/games647/FastLogin#bungeecordwaterfall-1
but when i come to 3. Now there is allowed-proxies.txt file in the FastLogin folder Put your stats id from the BungeeCord config into this file i dont see the allowed-proxies.txt file.

**Comment by games647** [comment]
Do you activated BungeeCord support in the Spigot `config.yml` (not FastLogin) and restarted the server. Could maybe post that file.

**Comment by JayJLV** [comment]
My BungeeCord support is enabled
https://pastebin.com/NpvbCkE0

**Comment by games647** [comment]
Please post the server log.

**Comment by JayJLV** [comment]
Server logs:
https://pastebin.com/y8k8K9KT

**Comment by JayJLV** [comment]
But used newest from spigotmc.org
Where can i find newest fastlogin download?

**Comment by games647** [comment]
See the plugin project or this project page about dev builds.

**Comment by JayJLV** [comment]
So i just reinsalled all my Fastlogin files and set it up as said.
When i join sever i login in authme and then i type fastlogin and it just says:
Sending request... (Dont forget to follow the BungeeCord setup guide)

**Comment by games647** [comment]
Please post the bungee loh

**Comment by JayJLV** [comment]
bungee log:
https://pastebin.com/AVQv6WTh
For some resson it can't get to my database

**Comment by games647** [comment]
As you can see, it shows access denied. Please check if your BungeeCord configuration for FastLogin is correct. The MySQL/MariaDB database requires that the password is put into quotes: `'HERE'`.

**Comment by JayJLV** [comment]
yup i add '   ' in the password and it removed that error, but a new one popped up:

12:29:53 [WARNING] Exception encountered when loading plugin: FastLogin
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:159)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:44)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by games647** [comment]
This means that the plugin expected somewhere a number, but read text. Putting them into quotes forces to read them as text. So you should do this for something like the port.

**Comment by JayJLV** [comment]
yep my mistake in port but it still dosent work
Bungee logs:
https://pastebin.com/zCe4PMMA
Spigot logs:
https://pastebin.com/UGTwURKD

**Comment by games647** [comment]
You also have an outdated version on Bungee. They have to be in sync most of the time.
