### ISSUE TITLE
Error... Please help...

### ISSUE THREAD

**Issue by NojusssYT** [games647/FastLogin#427]
[06:52:19] [Craft Scheduler Thread - 2/WARN]: [ProtocolLib] Loaded class com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource from FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432 which is not a depend, softdepend or loadbefore of this plugin.
[06:52:19] [Craft Scheduler Thread - 2/ERROR]: [FastLogin] Cannot send encryption packet. Falling back to cracked login
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.security.PublicKey exists in class PacketLoginOutEncryptionBegin.
at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:363) ~[?:?]
at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343) ~[?:?]
at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.sentEncryptionRequest(ProtocolLibLoginSource.java:84) ~[?:?]
at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.setOnlineMode(ProtocolLibLoginSource.java:49) ~[?:?]
at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:51) ~[?:?]
at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:16) ~[?:?]
at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:57) ~[?:?]
at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:40) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-261]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-261]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]

**Comment by games647** [comment]
Update to a dev build
