### ISSUE TITLE
Got errors when Player Join

### ISSUE THREAD

**Issue by x9nico** [games647/FastLogin#444]
When Player join my server and when they are on premium list, there is this error:

[12:03:10 ERROR]: [FastLogin] Cannot send encryption packet. Falling back to cracked login for: StoredProfile{rowId=1, premium=true, lastIp='127.0.0.1', lastLogin=2020-12-13T10:41:14Z} StoredProfile{id=null, name='x9nico'}
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.security.PublicKey exists in class PacketLoginOutEncryptionBegin.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:363) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.setOnlineMode(ProtocolLibLoginSource.java:52) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:64) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:18) ~[?:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:38) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-418]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-418]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-418]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Skopii** [comment]
Have you found a solution? I have the same thing and i dont know how to solve it.

**Comment by x9nico** [comment]
> Have you found a solution? I have the same thing and i dont know how to solve it.

Yes, I just haven't ProtocolSupport on the server.
You need it.

**Comment by games647** [comment]
To clarify for others too. This error means that the plugin wasn't updated for the server version it was running under. Therefore it cannot modify the packets.
