### ISSUE TITLE
PostBlast fatal error login

### ISSUE THREAD

**Issue by DragonArthur** [games647/FastLogin#48]
https://www.dropbox.com/s/2myrltgu4yzr5wz/ScreenCaptureProject1.mp4?dl=0
https://www.dropbox.com/s/jdiqsk065ih968h/techniclauncher_2016-07-31.log?dl=0

**Comment by Andrew2070** [comment]
yeah.

**Comment by games647** [comment]
Please use Paste bin or put it directly here. I won'the download files from dropbox

**Comment by Andrew2070** [comment]
Its a video showing the error ebcause it doesnt get logged.
and second link is the launcher log.

**Comment by DragonArthur** [comment]
trying to but its kinda big and pastebins frozen xP

**Comment by games647** [comment]
Just upload the video to Youtube or upload a picture directly here to Github as I assume it's just a kick message.

**Comment by Andrew2070** [comment]
```
Hi another issue:
[04:23:44 INFO]: UUID of player Ploxer is 1644f736-d4c4-39ae-adbc-c2801a146929

[04:23:44 INFO]: Client protocol version 2


4:23:46 INFO]: [Server thread] Server side modded connection established

[04:23:46 INFO]: Galacticraft server sending dimension IDs to connecting client: -30 -1022 -1023 -1026 -1021 -1007 -2554 -2542 -2546 -1025 -2547 -1009 -1010 -29 -2549 -2545 -2551 -2544 -2548 -1027 -2550 -1024 -1012 -1016 -1014 -1015 -1013 -2543 -28 -1018 -1011 -1019 -1017 -1020 

[04:23:46 INFO]: SMP: Sync dimensions to client

[04:23:46 INFO]: Loading GC player data for Ploxer : 0

[04:23:46 INFO]: Ploxer[/5.178.163.6:49600] logged in with entity id 659169 at ([SpawnWorld] -341.1277734423461, 5.0, 1434.5445190446228)

[04:23:46 ERROR]: Could not pass event PlayerJoinEvent to SkinsRestorer v12.4.2

org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:361) [oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:217) [oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) [NetworkDispatcher.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465) [NetworkDispatcher.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) [HandshakeCompletionHandler.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:1.7.10-R0.1-SNAPSHOT]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.network.play.server.S38PacketPlayerListItem.removePlayer(Lnet/minecraft/entity/player/EntityPlayerMP;)Lnet/minecraft/network/play/server/S38PacketPlayerListItem;
	at skinsrestorer.bukkit.skinfactory.SkinFactory_v1_7_R4.updateSkin(SkinFactory_v1_7_R4.java:42) ~[?:?]
	at skinsrestorer.bukkit.listeners.LoginListener.onJoin(LoginListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
	... 26 more
[04:23:46 INFO]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler

[04:23:46 INFO]: Sending mutations to player: Ploxer

[04:23:46 INFO]: Player EntityPlayerMP['Ploxer'/659169, l='SpawnWorld', x=-341.13, y=5.00, z=1434.54](Ploxer at -341.1277734423461,5.0,1434.5445190446228) connected. Sending ping

[04:23:46 INFO]: Sent config to 'Ploxer.'

[04:23:46 INFO]: SMP: Player logged in: Sync diminfo to clients

[04:23:46 INFO]: Sync dimension info to clients!

[04:23:46 INFO]: Send validation data to the client

[04:23:48 INFO]: syncToClient: style = STYLE_FLAT_GRADIENT

[04:23:49 INFO]: Ploxer lost connection: Disconnected

[04:23:52 WARN]: Exception in thread "Craft Scheduler Thread - 206" 

[04:23:52 WARN]: org.apache.commons.lang.UnhandledException: Plugin SkinsRestorer v12.4.2 generated an exception while executing task 7009

	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

Caused by: java.lang.NoSuchMethodError: net.minecraft.network.play.server.S38PacketPlayerListItem.removePlayer(Lnet/minecraft/entity/player/EntityPlayerMP;)Lnet/minecraft/network/play/server/S38PacketPlayerListItem;

	at skinsrestorer.bukkit.skinfactory.SkinFactory_v1_7_R4.updateSkin(SkinFactory_v1_7_R4.java:42)

	at skinsrestorer.bukkit.listeners.LoginListener$1.run(LoginListener.java:50)

	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)

	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

	... 3 more



```

**Comment by games647** [comment]
The errors are from SkinsRestorer. Maybe an issue of SkinsRestorer. You could try it without.

**Comment by Andrew2070** [comment]
problem is when I remove/disable skin-restorer it gives them a fatal error instead of invalid session. However for the player specified in the error above, "Plox" We don't know what specific error he has, whether it is an invalid session error or a fatal error.

**Comment by games647** [comment]
Invalid session is normal, because it means it requested an premium authentication, but the player isn't premium.

**Comment by Andrew2070** [comment]
So how do i fix it?

**Comment by games647** [comment]
Report the error to SkinsRestorer and as I said to in the other ticket run /cracked for the pending players.

**Comment by games647** [comment]
@DragonArthur news?

**Comment by DragonArthur** [comment]
fixed the issue. i had to delete the texture pack plus i was using 32x while the pack was 64x.
everythings fine now
