### ISSUE TITLE
NoSuchMethodError PremiumPlaceholder.unregister()

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [games647/FastLogin#499]
```
[02:41:15] [Server thread/INFO]: Saving the game (this may take a moment!)
[02:41:15] [Server thread/INFO]: Saved the game
[02:41:16] [Server thread/INFO]: Stopping the server
[02:41:16] [Server thread/INFO]: Stopping server (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[02:41:16] [Server thread/INFO]: [FastLogin] Disabling FastLogin v1.11-SNAPSHOT-d9f254f
[02:41:16] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: FastLogin
[02:41:16] [Server thread/INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
[02:41:16] [Server thread/ERROR]: Error occurred while disabling FastLogin v1.11-SNAPSHOT-d9f254f (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean com.github.games647.fastlogin.bukkit.PremiumPlaceholder.unregister()'
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onDisable(FastLoginBukkit.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:406) ~[patched_1.15.2.jar:git-Purpur-606]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:760) ~[patched_1.15.2.jar:git-Purpur-606]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:791) ~[patched_1.15.2.jar:git-Purpur-606]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:1040) ~[patched_1.15.2.jar:git-Purpur-606]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
I am interested to know for the sake of this line:
`[02:41:16] [Server thread/INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.`
Did it run well despite the error?

**Comment by games647** [comment]
It disabled itself, because of a breaking change in PlaceholderAPI once again.

**Comment by games647** [comment]
Or you just have an outdated version installed.

**Comment by 7wOv6ySCjo** [comment]
> Or you just have an outdated version installed.

Exactly. I can't update PlaceholderAPI because too many placeholders breaks down. I have PlaceholderAPI ([2.10.5](https://www.spigotmc.org/resources/placeholderapi.6245/history))

Can I safely ignore that message?

**Comment by games647** [comment]
Yes it was fine, because nothing was changed after, but I introduce a fail safe catch.
