### ISSUE TITLE
save error

### ISSUE THREAD

**Issue by xuso5556589** [games647/FastLogin#500]
[FastLogin] Failed to save playerProfile StoredProfile{rowId=-1, premium=false, lastIp='xxxxx', lastLogin=2021-03-30T16:24:20.091Z} StoredProfile{id=null, name='xxxxx'}
java.sql.SQLException: Field 'UserID' doesn't have a default value
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
    at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281)
    at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1254)
    at fastlogin.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
    at fastlogin.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
    at com.github.games647.fastlogin.core.AuthStorage.save(AuthStorage.java:207)
    at com.github.games647.fastlogin.core.shared.ForceLoginManagement.run(ForceLoginManagement.java:70)
    at com.github.games647.fastlogin.bungee.task.ForceLoginTask.run(ForceLoginTask.java:40)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by games647** [comment]
This id is specified as auto incrementing by the plugin on creation. Either create the table manually with the correct table definition  or let the plugin use it. If another application is using the same table name `premium`, please respond back.
