### ISSUE TITLE
The database is not working for me.

### ISSUE THREAD

**Issue by paj1s** [games647/FastLogin#501]
I have switched to bungeecord and did all of the things from the turorial. But the problems just keeps going, i have installed mysql server and configured it but now im stuck on this and can't move on without help.

00:47:25 [WARNING] Exception encountered when loading plugin: FastLogin
fastlogin.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Public Key Retrieval is not allowed
    at fastlogin.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
    at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
    at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:115)
    at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
    at com.github.games647.fastlogin.core.AuthStorage.<init>(AuthStorage.java:107)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:186)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:53)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Public Key Retrieval is not allowed
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
    at com.mysql.jdbc.Util.getInstance(Util.java:386)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:878)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:874)
    at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1770)
    at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
    at fastlogin.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    at fastlogin.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
    at fastlogin.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
    at fastlogin.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
    at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
    ... 9 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Public Key Retrieval is not allowed
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
    at com.mysql.jdbc.Util.getInstance(Util.java:386)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
    at com.mysql.jdbc.authentication.Sha256PasswordPlugin.nextAuthenticationStep(Sha256PasswordPlugin.java:121)
    at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1768)
    ... 27 more

**Comment by games647** [comment]
Duplicate #433

**Comment by games647** [comment]
Try to login with the command line `mysql -u USER -p`

**Comment by paj1s** [comment]
I sorted it out, it was my mistake, the only problem a have now is that it wants me to login (i have paid account)

**Comment by games647** [comment]
The plugin is opt-in by default unless you change the configuration file.

**Comment by paj1s** [comment]
I solved it, idk why maybe i forgot to save it but the bungeecord config was different to server config and that was making the trouble. It's now working fine, sometimes it doesn't apply skin on premium but i figured that one too and i hope it will work fine from now on. Thanks for support.
