### ISSUE TITLE
Error in 1.16.5 - Cannot send encryption packet. Falling back to cracked login

### ISSUE THREAD

**Issue by CookieCraftMcSrv** [games647/FastLogin#538]
[FastLogin] Cannot send encryption packet. Falling back to cracked login

1.16.5

Paper

**Comment by games647** [comment]
Please post the full error log.

**Comment by CookieCraftMcSrv** [comment]
ok 1 second

**Comment by CookieCraftMcSrv** [comment]
Error Log:

[16:06:07 ERROR]: [FastLogin] Cannot send encryption packet. Falling back to cracked login
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.security.PublicKey exists in class PacketLoginOutEncryptionBegin.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.sentEncryptionRequest(ProtocolLibLoginSource.java:84) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.setOnlineMode(ProtocolLibLoginSource.java:49) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:51) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:16) ~[?:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:57) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-762]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-762]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-762]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:823) [?:1.8.0_292]

**Comment by CookieCraftMcSrv** [comment]
Can you help me? @games647 ?

**Comment by games647** [comment]
Update to a dev build. You are using a outdated version.

**Comment by CookieCraftMcSrv** [comment]
Where i can download it for my minecraft server? (Paper Spigot) @games647

**Comment by CookieCraftMcSrv** [comment]
Oh i found it. Thanks
