### ISSUE TITLE
1.17 bungee driver error

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [games647/FastLogin#573]
### What happened?

15:30:45 [WARNING] [FastLogin] This driver org.sqlite.JDBC is not supported on this platform
15:30:45 [WARNING] [FastLogin] Please choose MySQL (Spigot+BungeeCord), SQLite (Spigot+Sponge) or MariaDB (Sponge)
java.lang.ClassNotFoundException: org.sqlite.JDBC
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:375)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.checkDriver(FastLoginCore.java:223)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:192)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:82)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Steps to reproduce

1.17 bungee

### Plugin version

999

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
For BungeeCord, you need to use MySQL or MariaDB. This means that you have to update the configuration as well as install the server software if not already running.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> For BungeeCord, you need to use MySQL or MariaDB. This means that you have to update the configuration as well as install the server software if not already running.

i used sqlite on 1.16 and everything worked. i can't just switch to mysql because all the saved data will be reset

**Comment by Envel-Nikita-Gutsenkov** [comment]
for some reason, the plugin starts to assume that everyone has a license if I reset the database

**Comment by Envel-Nikita-Gutsenkov** [comment]
therefore, I need to somehow make sqlite work or convert it to mysql

**Comment by games647** [comment]
There are tools like SQLiteman that could convert the existing data to MySQL.

**Comment by wfjsw** [comment]
I once was able to use SQLite on bungeecord by changing the java args to following things:
```
java -cp 'waterfall-1.17-443.jar:sqlite.jar' net.md_5.bungee.Bootstrap
```
while the sqlite jar can be occupied at https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.36.0.1/
