### ISSUE TITLE
NullPointerException when joining a closed network.

### ISSUE THREAD

**Issue by brandonlooksdumb** [games647/FastLogin#582]
### What happened?

when I activate the maintenance of my Minecraft server and players try to join it, I get an error in the console of my BungeeCord server.

### What did you expect?

I expect that this error will no longer occur because it is very annoying even if it does not affect the server.

### Steps to reproduce

prevent players from entering the server on a `PreLoginEvent` with `HIGHEST` priority.

### Configuration file

https://pastebin.com/raw/G5piRxsv

### Server log

```shell
[00:51:20 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@56e07a08, id=8826, owner=com.github.games647.fastlogin.bungee.FastLoginBungee@63a5d002, task=com.github.games647.fastlogin.bungee.tasks.AsyncPremiumCheck@302a638f, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: null
        at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:74) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:752f972:unknown]
        at net.md_5.bungee.connection.InitialHandler.disconnect(InitialHandler.java:642) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:752f972:unknown]
        at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:432) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:752f972:unknown]
        at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:425) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:752f972:unknown]
        at net.md_5.bungee.api.event.AsyncEvent.completeIntent(AsyncEvent.java:87) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:752f972:unknown]
        at com.github.games647.fastlogin.bungee.tasks.AsyncPremiumCheck.run(AsyncPremiumCheck.java:40) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:752f972:unknown]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

### Plugin version

1.10

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [x] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Duplicate of #292

There is a explanation here: https://github.com/games647/FastLogin/issues/292#issuecomment-573190395

FastLogin is only the last plugin that causes to resume the processing not the cause of this bug. That's why you see it in the stacktrace. BTW: 1.10 is outdated.

**Comment by brandonlooksdumb** [comment]
> Duplicate of #292
> 
> There is a explanation here: [#292 (comment)](https://github.com/games647/FastLogin/issues/292#issuecomment-573190395)
> 
> FastLogin is only the last plugin that causes to resume the processing not the cause of this bug. That's why you see it in the stacktrace. BTW: 1.10 is outdated.

Hello, 

I have indeed solved the problem. It was coming from my plugin. 
Sorry for the duplicate!
