### ISSUE TITLE
FastLogin not autoRegistering premium users with AuthMeReloaded

### ISSUE THREAD

**Issue by AlexPresso** [games647/FastLogin#595]
### What happened?

FastLogin isn't autoRegistering premium users with AuthMeReloaded. I activated both `autoRegister` and `autoLogin`, tried to remove both plugin databases + folders, it just refuses to generate a password.
From what I see in the logs, it seems that FastLogin uses the TCPShield proxy IP and AuthMe uses the "real IP", could the issue be related to that ?

### What did you expect?

FastLogin hooks into AuthMeReloaded to generate a password for the premium user.

### Steps to reproduce

- Set the server to online-mode: false
- Install FastLogin (v1.11-SNAPSHOT-4d4ecf3)
- Install AuthMeReloaded (5.6.0-SNAPSHOT-b2482)
- Set `autoRegister: true` in the FastLogin's config file
- Try to connect to the server

### Plugin list

AuthMe (5.6.0-SNAPSHOT-b2482), FastLogin (1.11-SNAPSHOT-4d4ecf3), EpicWorldGenerator, ProtocolLib, TCPShield, Essentials, EssentialsChat, EssentialsSpawn

### Configuration file

https://hastebin.com/amiqorejug.yaml

### Server log

```shell
https://hastebin.com/asasecipob.md
```

### Plugin version

v1.11-SNAPSHOT-4d4ecf3

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Sorry the link you posted expired, could you post the startup log and the part where you are trying to login with the databases removed.

>From what I see in the logs, it seems that FastLogin uses the TCPShield proxy IP and AuthMe uses the "real IP", could the issue be related to that ?

For FastLogin the ip is mostly irrelevant. However it's not possible for FastLogin to change the onlinemode if the proxy is managing the online mode.

**Comment by AlexPresso** [comment]
Sorry for the delay, here is the new link: https://hastebin.com/gemunenisi.md

**Comment by games647** [comment]
Okay found it. It's because another plugin changed the IP, which is unexpected for FastLogin.

**Comment by games647** [comment]
That's the meaning for the message: `No on-going login session for player: CraftPlayer{name=AlexPresso} `

**Comment by AlexPresso** [comment]
Thanks for your reply, okay I get it, so this is because of TCPShield.

Since the player is supposed to have the same UUID, could FastLogin check for an IP Change (even if it's illogic) so it can work behind proxies changing player's IP ?
Or would it be better to post an issue on TCPShield to ask them what we can do with that IP change ?

**Comment by games647** [comment]
>Since the player is supposed to have the same UUID,

That's not possible, because can change during the login process. It will be set on the spoofedUUID field (exposed from the Bungee support). Changing the IP during a connection is something during a handshake unexpected, because it means it would mean there is a new endpoint. I could work on a fix, but I guess there are others plugins which could have an issue with that too.

**Comment by AlexPresso** [comment]
Alright, in the mean time, is there any alternative/workaround I could use to make it work ?

**Comment by games647** [comment]
I also uploaded a version with more debug logging for the session: https://github.com/games647/FastLogin/releases/tag/tcpshield

I'll need to know if the session ids match together.

**Comment by AlexPresso** [comment]
The TCPShield version I was using (2.5.3) wasn't working but it seems like it works with TCPShield 2.4 (https://github.com/TCPShield/RealIP/releases/tag/2.3.1) 

here are the logs with the debugging version:
```
[17:13:13 INFO]: [FastLogin] Handling player AlexPresso
[17:13:13 INFO]: [FastLogin] GameProfile AlexPresso uses a premium username
[17:13:13 INFO]: [FastLogin] Starting session 51.178.221.23:28525
[17:13:14 INFO]: [FastLogin] Enabling onlinemode encryption for /51.178.221.23:28525
[17:13:15 INFO]: [FastLogin] Profile AlexPresso has a verified premium account
[17:13:15 INFO]: UUID of player AlexPresso is b5ddf389-ac0a-33d2-a804-d21e198db7ec
[17:13:15 INFO]: AlexPresso[/XX.XX.195.XX:28525] logged in with entity id 247 at ([world]-21.72740728936991, 85.49313562283125, 47.39723970506711)
[17:13:16 INFO]: [+++] AlexPresso a rejoint le serveur.
[17:13:16 INFO]: [FastLogin] No session found for id XX.XX.195.XX:28525
[17:13:16 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=AlexPresso} with ID XX.XX.195.XX:28525

```

**Comment by games647** [comment]
Do you run Paper or a fork of it?

**Comment by AlexPresso** [comment]
Yes, I use latest version of Paper

**Comment by games647** [comment]
Okay it seems that TCPShield 2.5 activated support for its Paper implementation, which caused the bug to trigger. 2.4 should work fine for now.

**Comment by cicatrice74** [comment]
Is the issue going to be fixed ?

**Comment by games647** [comment]
The referenced commit should fixed it, but it's currently experimental. As said above you could still use 2.4 of TCPShield.

**Comment by AlexPresso** [comment]
The 2.4 version of TCPShield is initialized as a legacy plugin, and is causing a lot of network performances issues since it is using an old version of the Paper networking.
Thank you for that experimental commit, is there any CI / GithubAction generating the jar artifact for the branch tcpshield ?

**Comment by AlexPresso** [comment]
I tried to execute the "package" maven goal (Adopt OpenJDK 16) for the tcpshield branch but the `FastLoginBukkit.jar` seems to be corrupted, could you please provide an built version so I can test it ?
```
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[patched_1.17.1.jar:git-Paper-209]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) [patched_1.17.1.jar:git-Paper-209]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:404) [patched_1.17.1.jar:git-Paper-209]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:276) [patched_1.17.1.jar:git-Paper-209]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) [patched_1.17.1.jar:git-Paper-209]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) [patched_1.17.1.jar:git-Paper-209]
        at net.minecraft.server.MinecraftServer$$Lambda$3679/0x00000000d5fde400.run(Unknown Source) [patched_1.17.1.jar:git-Paper-209]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.zerror(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.findEND(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.get(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[patched_1.17.1.jar:git-Paper-209]
        ... 7 more
```

**Comment by cicatrice74** [comment]
Can we finally know if this is a tcpshield bug/issue or a fastlogin bug/issue, there is not a final sentence on this.

**Comment by AlexPresso** [comment]
TCPShield is working fully as intended, the problem is due to FastLogin not being able to handle the player IP change:

When a player joins the server, he has the TCPShield proxy IP, FastLogin tries to auto-login the player with that IP. When TCPShield has finished connecting the player to the server, it replaces its IP with the real player's IP (not the proxy one anymore). Then FastLogin is unable to retrieve the player in the auto-logged list while using the first player IP (the proxy one which isn't used anymore).

**Comment by cicatrice74** [comment]
I read all the stuff here but i cannot find a solution to use fastlogin + tcpshield with latest 1.17.1 paper, it is going to ask players for login even on /premium config. Is there a final way to use them together ? I cannot use tcpshield 2.4 anymore as i updated  1.16.5 to 1.17.1 paper, can i finally have a functioning 1.17.1 paper(offline) + fastlogin + authme + tcpshield latest ? O will i must remove tcpshield or setup my server to online and remove fastlogin + authme ?

**Comment by AlexPresso** [comment]
You can build and use the plugin from the [tcpshield](https://github.com/games647/FastLogin/compare/tcpshield) branch, it works pretty well on my server.
I forked the project and did it for you if you want, here are both [FastLoginBukkit.jar & FastLoginBungee.jar](https://github.com/AlexPresso/FastLogin/releases/tag/tcpshield-fix)

**Comment by kedavlar** [comment]
news about the compatibility?

**Comment by cicatrice74** [comment]
The issue is on again with latest tcpshield 2.5.5, will you try to fix it ?

**Comment by cicatrice74** [comment]
Is there someone with a solution for the problem finally ?

**Comment by AlexPresso** [comment]
Spamming the issue won't be of any help... Maintaining this plugin is a huge task for a single dev. This issue also relies on the one mentionned above in the TCPShield plugin.

Still, there's a `tcpshield` branch that is some kind of a "temporary" fix for it: https://github.com/games647/FastLogin/tree/tcpshield

Just clone that branch, build the plugin yourself and put it on your server, it worked for me.

**Comment by cicatrice74** [comment]
@AlexPresso i cannot build it by myself, can u do it for me and send me a link for that ?

**Comment by AlexPresso** [comment]
There you go: https://we.tl/t-Pp4v6JuNSq

**Comment by cicatrice74** [comment]
Tnx alot

Il Sab 5 Feb 2022, 18:17 AlexPresso ***@***.***> ha scritto:
