### ISSUE TITLE
Error cannot reply to EncryptionRequestPacket on Floodgate players

### ISSUE THREAD

**Issue by EnriqueGF** [games647/FastLogin#616]
### What happened?

Floodgate players get this error:

`
19:19:30 [SEVERE] java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token.
`

It only happens with FastLogin plugin installed

### Plugin list

Floodgate, GeyserMC, Fastlogin

### Server log

```shell
19:44:32 [INFO] [Geyser-BungeeCord] /86.127.253.13:59375 ha tratado de conectarse!
19:44:33 [INFO] [Geyser-BungeeCord] Jugador conectado con Gamertag EnriqueGFX1337
19:44:35 [INFO] [Geyser-BungeeCord] Intentando iniciar sesión usando el modo Floodgate... La autentificación será encriptada.
19:44:35 [INFO] [Geyser-BungeeCord] EnriqueGFX1337 (logged in as: EnriqueGFX1337) has connected to the Java server
19:44:35 [INFO] [EnriqueGFX1337,/86.127.253.13:0] <-> InitialHandler has connected
19:44:35 [INFO] [FastLogin] Incoming login request for .EnriqueGFX1337 from /86.127.253.13:0
19:44:35 [INFO] [FastLogin] Handling player .EnriqueGFX1337
19:44:35 [INFO] [FastLogin] Requesting premium login for registered player: .EnriqueGFX1337
19:44:35 [INFO] [floodgate] Jugador conectado por Floodgate como .EnriqueGFX1337 se ha desconectado
19:44:35 [INFO] [Geyser-BungeeCord] EnriqueGFX1337 has disconnected from the Java server because of java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token.
19:44:35 [SEVERE] java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token.

19:44:35 [SEVERE]     at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)

19:44:35 [SEVERE]     at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)

19:44:35 [SEVERE]     at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146)

19:44:35 [SEVERE]     at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:332)

19:44:35 [SEVERE]     at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:36)

19:44:35 [SEVERE]     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)

19:44:35 [SEVERE]     at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

19:44:35 [SEVERE]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

19:44:35 [SEVERE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

19:44:35 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

19:44:35 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

19:44:35 [SEVERE]     at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)

19:44:35 [SEVERE]     at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)

19:44:35 [SEVERE]     at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)

19:44:35 [SEVERE]     at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)

19:44:35 [SEVERE]     at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)

19:44:35 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

19:44:35 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

19:44:35 [SEVERE]     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

19:44:35 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:831)
```

### Plugin version

latest

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
EncryptionRequest packets don't require an access token or profile. This seems to be bug another plugin. FastLogin doesn't include MCProtocolLib and it appears to configured in a client configuration which is unusual for BungeeCord systems.

**Comment by EnriqueGF** [comment]
> EncryptionRequest packets don't require an access token or profile. This seems to be bug another plugin. FastLogin doesn't include MCProtocolLib and it appears to configured in a client configuration which is unusual for BungeeCord systems.

Hello, thank's you for replying

[](https://i.gyazo.com/1a0d2b5d9949805ab8f48a0dfa678c64.png)

These are my current plugins, the only that is not opensource is Classic-HC, developed by me and it doesnt use MCProtocolLib

So, do you have any idea of what's causing this? it's strange because a days ago all was correctly working but today I encountered with this

**Comment by games647** [comment]
Open your plugins with an archiver program. `.jar` are only zipped files. Then check for folders like the posted class path: `com/github/steveice10/mc/protocol`

**Comment by EnriqueGF** [comment]
> steveice10

I found that Geyser is using it

**Comment by EnriqueGF** [comment]
This solved it:

https://github.com/games647/FastLogin/pull/608

Please merge it! :)

**Comment by Smart123s** [comment]
> while read p; do

not yet, please :D
I want to test some edge cases first

**Comment by jondycz** [comment]
It isn't only about floodgate. Having only Fast Login(with protocolLib) installed along side GeyserMC, any player that is "cracked" player can login just fine from bedrock device. But if the account is PREMIUM, the bedrock account gets disconnected.

This is due to FastLogin sending the packet to the client to verify if the account is PREMIUM or not. Normal PC clients ignore this packet but geyser does not. And since bedrock players are not authenticated with a java account, it assumes the server is in ONLINE MODE. And the player gets kicked.

I suggest to detect when player is connected through geyser and skip the premium verification and just assume the player isn't premium and require a password.

**Comment by Smart123s** [comment]
> It isn't only about floodgate. Having only Fast Login(with protocolLib) installed along side GeyserMC, any player that is "cracked" player can login just fine from bedrock device. But if the account is PREMIUM, the bedrock account gets disconnected.
> 
> This is due to FastLogin sending the packet to the client to verify if the account is PREMIUM or not. Normal PC clients ignore this packet but geyser does not. And since bedrock players are not authenticated with a java account, it assumes the server is in ONLINE MODE. And the player gets kicked.
> 
> I suggest to detect when player is connected through geyser and skip the premium verification and just assume the player isn't premium and require a password.

The current version of FastLogin uses `FloodgateApi` to detect Floodgate players. If you are using Geyser with cracked authentication, then bedrock players will be treated the same way as Java players. Or at least they should be. Can you join your server using a Cracked Java client with a Premium username?

**Comment by cmod31** [comment]
Depends on the auth plugin Authme blocks it completely with premium username cracked players but maybe thats something in the config idk

**Comment by Smart123s** [comment]
Yes, it's probably FastLogin's config. You can configure it to block
cracked players from using premium players names. Try different config
options. Pay high attention to the value of "nameChangeCheck", as it's the
main way (but not the only one) to configure this behavior.

**Comment by jondycz** [comment]
> > It isn't only about floodgate. Having only Fast Login(with protocolLib) installed along side GeyserMC, any player that is "cracked" player can login just fine from bedrock device. But if the account is PREMIUM, the bedrock account gets disconnected.
> > This is due to FastLogin sending the packet to the client to verify if the account is PREMIUM or not. Normal PC clients ignore this packet but geyser does not. And since bedrock players are not authenticated with a java account, it assumes the server is in ONLINE MODE. And the player gets kicked.
> > I suggest to detect when player is connected through geyser and skip the premium verification and just assume the player isn't premium and require a password.
> 
> The current version of FastLogin uses `FloodgateApi` to detect Floodgate players. If you are using Geyser with cracked authentication, then bedrock players will be treated the same way as Java players. Or at least they should be. Can you join your server using a Cracked Java client with a Premium username?

They are treated the same yes. Yes I can join my server using a cracked client with premium user name. It just requires me to insert the password.

Issue with FastLogin is that it ASKS clients connected through Geyser "hey are you authenticated with mojang servers?" (If the user is treated as premium - did /premium command) and due to this packet, users with legit Java Minecraft - who also use the same name as their XBOX GamerTag are being automatically disconnected. Because Geyser can not handle this packet asking if they are authenticated. Geyser assumes the server is in ONLINE mode, cuz why the hell would the server ask otherwise, right? And the player is kicked.

**Comment by Smart123s** [comment]
Ok, I got it now, I'll add it to my to do list, but I'm busy with school at
the moment, so it might take a long time before I can actually make
something about this.
