### ISSUE TITLE
NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi (I dont use this floodgate)

### ISSUE THREAD

**Issue by ehetteNandaYo** [games647/FastLogin#619]
### What happened?

[06:45:24 WARN] [FastLogin]: Error occurred on thread pool
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:80) ~[?:?]
        at com.github.games647.fastlogin.bungee.task.AsyncPremiumCheck.run(AsyncPremiumCheck.java:65) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        ... 3 more

### Plugin version

#1012 from jenkins

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by laontme** [comment]
Can confirm on Paper 1.17.1(build 278) without geysermc installed
