### ISSUE TITLE
NPE if Floodgate is not installed

### ISSUE THREAD

**Issue by ArtifactyNight** [games647/FastLogin#620]
### What happened?

i'm not using Geyser / Floodgate but why it's error?
it's error for someone (not everyone) who joined the server
```vc
02:24:56 [SEVERE] [FastLogin] Failed to check premium state of YedzDoo
java.lang.NullPointerException: Cannot invoke "org.geysermc.floodgate.api.FloodgateApi.getPlayerPrefix()" because the return value of "org.geysermc.floodgate.api.FloodgateApi.getInstance()" is null
    at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:80)
    at com.github.games647.fastlogin.bungee.task.AsyncPremiumCheck.run(AsyncPremiumCheck.java:65)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:831)
```

### What did you expect?

It's should be not error

### Plugin list

i installed FastLogin (dev build) in bungeecord/spigot server and AuthmeReloaded-5.6.0 in Lobby Server

### Configuration file

Default config with mysql connect

### Plugin version

v.1.11

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Krakenied** [comment]
```[14:10:03 WARN] [FastLogin]: Error occurred on thread pool
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:80) ~[?:?]
        at com.github.games647.fastlogin.bungee.task.AsyncPremiumCheck.run(AsyncPremiumCheck.java:65) ~[?:?]
        ... 4 more
