### ISSUE TITLE
FastLoginBukkit doesn't enable (using build 1015)

### ISSUE THREAD

**Issue by Krakenied** [games647/FastLogin#627]
```[03:08:20 INFO]: [FastLogin] Enabling FastLogin v1.11-SNAPSHOT-28480a0
[03:08:20 ERROR]: Error occurred while enabling FastLogin v1.11-SNAPSHOT-28480a0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.github.games647.fastlogin.core.hooks.FloodgateService.isValidFloodgateConfigString(String)" because "this.floodgateService" is null
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.initializeFloodgate(FastLoginBukkit.java:154) ~[?:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:94) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at java.lang.Thread.run(Unknown Source) [?:?]
[03:08:20 INFO]: [FastLogin] Disabling FastLogin v1.11-SNAPSHOT-28480a0
[03:08:20 INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
[03:08:20 ERROR]: Error occurred while disabling FastLogin v1.11-SNAPSHOT-28480a0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.github.games647.fastlogin.bukkit.BungeeManager.cleanup()" because "this.bungeeManager" is null
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onDisable(FastLoginBukkit.java:171) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[purpur-server-1.16.5-R0.1-SNAPSHOT-893e79f03c2db1677d19d610cbfe81c8627cb27b.jar:git-Purpur-"893e79f"]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by frafol** [comment]
same issue
