### ISSUE TITLE
SPIGOT FastLogin Just dont work

### ISSUE THREAD

**Issue by Hugytor09YT** [games647/FastLogin#641]
### What happened?

The plugin don't Work

### What did you expect?

An error.

### Steps to reproduce

I downloaded the lasted version of FastLogin and i used it on my Spigot Server.

### Plugin list

LunarClient-API, WorldEdit, LunarUtils, VoidTeleport, IPWhitelist, VoidWorld, AquaCore, BuycraftX, ProtocolSupport, AntiBuildQL, ProtocolLib, SuperLobby, AuthMe, FastLogin

### Server log

```shell
Error occurred while enabling FastLogin v1.11-SNAPSHOT-d2c94af (Is it up to date?)
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:161) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at com.google.common.net.HostAndPort.getPort(HostAndPort.java:110) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.lambda$load$2(FastLoginCore.java:129) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:131) ~[?:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:85) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.base/java.lang.Thread.run(Thread.java:831) [?:?]
```

### Plugin version

FastLogin v1.11-SNAPSHOT-d2c94af

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [x] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Hugytor09YT** [comment]
PD: The config file is the default.

**Comment by Hugytor09YT** [comment]
I removed 3 times the config file, and it works.
