### ISSUE TITLE
Cannot send encryption packet. Falling back to cracked login

### ISSUE THREAD

**Issue by Etheride** [games647/FastLogin#675]
### What happened?

[19:20:21 ERROR]: [FastLogin] Cannot send encryption packet. Falling back to cracked login
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.security.PublicKey exists in class PacketLoginOutEncryptionBegin.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[ProtocolLib-4.8.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[ProtocolLib-4.8.0-SNAPSHOT.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.sentEncryptionRequest(ProtocolLibLoginSource.java:84) ~[FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.setOnlineMode(ProtocolLibLoginSource.java:49) ~[FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:51) ~[FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:16) ~[FastLogin.jar:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:57) ~[FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:40) ~[FastLogin.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-22]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-22]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-22]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:20:21 INFO]: UUID of player TogglingSpeed is bf9fe9dc-7efe-3312-89b1-69467a3463fd
[19:20:21 INFO]: TogglingSpeed joined the game

### What did you expect?

Player should automatically be authenticated however so the login fallback to default authme login.  

### Steps to reproduce

Paper 1.18
Load Fastlogin, Authme and Protocollub
Join the server with a premium account.
Register and then execute the command /premium.
Error is outputted

### Plugin list

Plugins (10): AuthMe, Chunky, ChunkyBorder, DiscordSRV, eco, EcoEnchants, FastLogin*, ProtocolLib, SkinsRestorer, VanillaTweaks

### Configuration file

https://www.toptal.com/developers/hastebin/ikojeloced.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/peqarudoho.yaml
```

### Plugin version

1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version for your server. Please download the a dev build as you don't have the latest build.

**Comment by Etheride** [comment]
Fixed! Thanks alot!
