### ISSUE TITLE
Exception encountered when loading plugin: FastLogin

### ISSUE THREAD

**Issue by EspartaProJunior** [games647/FastLogin#685]
### What happened?

When I start the server I get an error, but it is really strange because I have enough ram assigned to the server.

[23:30:08 WARN]: Exception encountered when loading plugin: FastLogin
java.lang.OutOfMemoryError: Java heap space
        at com.github.games647.fastlogin.core.RateLimiter.<init>(RateLimiter.java:39) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:125) ~[?:?]
        at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:88) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:7133a98:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:283) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:7133a98:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:7133a98:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:7133a98:unknown]
[23:30:08 INFO]: Enabled plugin CleanMOTD version 0.2.7 by 2LS

### Steps to reproduce

start the server

### Plugin list

Plugins (44): AdvancedPet, AuthMe, BetterRTP, BuycraftX, Chunky, Citizens, ClickTpa*, CMILib, Codex, CommandWhitelist, ConditionalEvents, DeathMessages, eco, Essentials, EssentialsSpawn, EzChat*, FastLogin, HolographicDisplays, Insights, InteractionVisualizer, Jobs, LibsDisguises, LuckPerms, MMOCore, ModelEngine, ModelEnginePatch, MoneyHunters, Multiverse-Core, MyCommand, MythicCrucible, MythicLib, MythicMobs, NexEngine, Oraxen, PlaceholderAPI, ProtocolLib, TAB, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

### Configuration file

https://www.toptal.com/developers/hastebin/vovifuqebi.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/rejolaquqa.yaml
```

### Plugin version

1.11-SNAPSHOT-4a5516c

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Your server doesn't have enough memory. Maybe too many plugins installed or they consume too much themselves.

**Comment by EspartaProJunior** [comment]
I added 2gb of ram more to my vps and the same thing appears.

**Comment by games647** [comment]
Okay it's your high bot connection number. In the current design of FastLogin, this number allocates the amount of memory accordingly for rate limiting. Reduce the number expire minutes and the connections accordingly. It's a issue of FastLogin. We didn't expect so high numbers.

**Comment by EspartaProJunior** [comment]
thank you already
