### ISSUE TITLE
Thread starvation or clock leap detected

### ISSUE THREAD

**Issue by Polda18** [games647/FastLogin#687]
### What happened?

Occasionally FastLogin in our server reports this error. Server is lagging, dropping, players are unable to login and play, the lag is so intense that players are suffocating in excavated walls and losing items.

### What did you expect?

I have no idea what could cause this issue, the expected behaviour would be obviously a working server without errors like these spamming the console.

### Steps to reproduce

I don't know if there is any user input that would reproduce this issue, it seems to happen kinda randomly out of blue.

### Plugin list

AuthMe, BetterWhitelist, Chunky, CoreProtect, FastLogin, Geyser-Spigot, InvSeePlusPlus, LuckPerms, Maintenance, PlugManX, ProtocolLib, ServerUtils, Shopkeepers, SkinsRestorer, TabList, Vault, WorldBorder and dynmap

### Configuration file

https://gist.github.com/Polda18/96d6b0feff171262d990443f1304b1d0

### Server log

```shell
[18:30:02] [FastLogin Pool Thread #0/WARN]: [fastlogin.hikari.pool.HikariPool] FastLogin - Thread starvation or clock leap detected (housekeeper delta=13m13s420ms290Âµs963ns).
[18:37:57] [Thread-10/WARN]: org.sqlite.SQLiteException: [SQLITE_IOERR_WRITE]  I/O error in the VFS layer while trying to write to a file on disk (disk I/O error)
[18:37:57] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:37:57] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[18:37:57] [Paper Watchdog Thread/ERROR]: 	PID: 23 | Suspended: false | Native: false | State: RUNNABLE
[18:37:57] [Paper Watchdog Thread/ERROR]: 	Stack:
[18:37:57] [Thread-10/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
[18:37:57] [Thread-10/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
[18:37:57] [Thread-10/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:1007)
[18:37:57] [Thread-10/WARN]: 	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
[18:37:57] [Thread-10/WARN]: 	at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
```

### Plugin version

v1.11-SNAPSHOT-3ca8ae6

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
>I/O error in the VFS layer while trying to write to a file on disk 

Could you check your operating system log messages? In case of systemd's journald `journalctl --reverse --boot`

**Comment by Polda18** [comment]
I'm afraid I couldn't check for myself as the server is hosted via an external service. May I pass the suggestion to them?

**Comment by games647** [comment]
Thread starvation is only a warning, indicating that there was a long pause where the housekeeping couldn't run. So it's normal after CPU starvation. The SQLite error is described as following: 

https://www.sqlite.org/rescode.html
>This error might result from a hardware malfunction or because a filesystem came unmounted while the file was open

Try to check your server performance with the typical tools like timings. Verify if a plugin or internal system is malfunction that generated a lot of load. You could also rename the database file or disable FastLogin temporarily to rule out the SQLite error. After all that it could also be some issue with your host.

**Comment by Polda18** [comment]
It most likely is issue with host. Some plugins couldn't write to the disk, some plugins couldn't load data to memory, that indicates issues with the host system, which is unfortunately something we cannot solve ourselves, we have to depend on the hosting service to solve for us. It may also be a temporary glitch that occured once and is gone now, or host already solved it.
