### ISSUE TITLE
Incompatibility with TCPShield on Velocity

### ISSUE THREAD

**Issue by SlimeBluKing** [games647/FastLogin#692]
### What happened?

[09:24:07 ERROR]: Couldn't pass GameProfileRequestEvent to fastlogin
java.lang.NullPointerException: Cannot invoke "com.github.games647.fastlogin.core.shared.LoginSession.setUuid(java.util.UUID)" because "session" is null
        at com.github.games647.fastlogin.velocity.listener.ConnectListener.onGameprofileRequest(ConnectListener.java:88) ~[?:?]
        at com.github.games647.fastlogin.velocity.listener.Lmbda$27.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[proxy.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[proxy.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[proxy.jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### What did you expect?

No autologin
This problem happen on Velocity

### Plugin list

AdvancedBans, CraftingStore, FastLogin, LuckPerms, ServerListPlus, SkinRestorer, snap, TCPShield, VulcanVelocity

### Server log

```shell
[09:23:53] [main/INFO]: Booting up Velocity 3.1.1...
[09:23:53] [main/INFO]: Loading localizations...
[09:23:53] [main/INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[09:23:54] [main/WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[09:23:54] [main/INFO]: Loading plugins...
[09:23:54] [main/INFO]: Loaded plugin luckperms 5.3.89 by Luck
[09:23:54] [main/INFO]: Loaded plugin advancedban 2.4.0 by 
[09:23:54] [main/INFO]: Loaded plugin craftingstore <UNKNOWN> by 
[09:23:54] [main/INFO]: Loaded plugin fastlogin 1.11-SNAPSHOT-4a5516c by games647, https://github.com/games647/FastLogin/graphs/contributors
[09:23:54] [main/INFO]: Loaded plugin serverlistplus <UNKNOWN> by 
[09:23:54] [main/INFO]: Loaded plugin skinsrestorer 14.1.10 by Blackfire62, McLive
[09:23:54] [main/INFO]: Loaded plugin snap 1.0-SNAPSHOT (build 25) by Phoenix616
[09:23:54] [main/INFO]: Loaded plugin tcpshield 2.5.5 by TCPShield
[09:23:54] [main/INFO]: Loaded plugin vulcan 2.0.1 by Jaren
[09:23:54] [main/INFO]: Loaded 9 plugins
[09:23:55] [Velocity Async Event Executor - #0/INFO]:         __    
[09:23:55] [Velocity Async Event Executor - #0/INFO]:   |    |__)   LuckPerms v5.3.89
[09:23:55] [Velocity Async Event Executor - #0/INFO]:   |___ |      Running on Velocity - Velocity
[09:23:55] [Velocity Async Event Executor - #0/INFO]: 
[09:23:55] [Velocity Async Event Executor - #0/INFO]: Loading configuration...
[09:23:55] [Velocity Async Event Executor - #0/INFO]: Loading storage provider... [MARIADB]
[09:23:55] [Velocity Async Event Executor - #0/INFO]: luckperms-hikari - Starting...
[09:23:55] [Velocity Async Event Executor - #0/INFO]: luckperms-hikari - Start completed.
[09:23:55] [Velocity Async Event Executor - #0/INFO]: Loading messaging service... [SQL]
[09:23:55] [Velocity Async Event Executor - #0/INFO]: Loading internal permission managers...
[09:23:55] [Velocity Async Event Executor - #0/INFO]: Performing initial data load...
[09:23:55] [Velocity Async Event Executor - #0/INFO]: Successfully enabled. (took 886ms)
[09:23:55] [Velocity Async Event Executor - #0/INFO]: [AdvancedBan] Offline permission support through LuckPerms active
[09:23:55] [Velocity Async Event Executor - #0/INFO]: HikariPool-1 - Starting...
[09:23:55] [Velocity Async Event Executor - #0/INFO]: HikariPool-1 - Start completed.
[09:23:55] [Velocity Async Event Executor - #0/INFO]: 
 
&8[]=====[&7Enabling AdvancedBan&8]=====[]
&8| &cInformation:
&8|   &cName: &7AdvancedBan
&8|   &cDeveloper: &7Leoko
&8|   &cVersion: &72.4.0
&8|   &cStorage: &7MySQL (external)
&8| &cSupport:
&8|   &cGithub: &7https://github.com/DevLeoko/AdvancedBan/issues
&8|   &cDiscord: &7https://discord.gg/ycDG6rS
&8| &cTwitter: &7@LeokoGar
&8| &cUpdate:
&8|   &7There is a new version available! [2.3.0]
&8[]================================[]&r
 
[09:23:56] [Velocity Async Event Executor - #0/ERROR]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[09:23:56] [Velocity Async Event Executor - #0/INFO]: fastlogin - Starting...
[09:23:56] [Velocity Async Event Executor - #0/WARN]: Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[09:23:56] [Velocity Async Event Executor - #0/INFO]: fastlogin - Start completed.
[09:23:56] [Velocity Async Event Executor - #0/INFO]: [Core] Reloading configuration...
[09:23:56] [Velocity Async Event Executor - #0/INFO]: [Core] Loaded configuration: ServerStatusConf
[09:23:56] [Velocity Async Event Executor - #0/WARN]: [Core] Unknown configuration property: Stats @ PluginConf
[09:23:56] [Velocity Async Event Executor - #0/WARN]: [Core] Unknown configuration property: Samples @ PluginConf
[09:23:56] [Velocity Async Event Executor - #0/INFO]: [Core] Loaded configuration: PluginConf
[09:23:56] [Velocity Async Event Executor - #0/WARN]: [Core] Configuration is not enabled, nothing will be changed on the server! Please execute /slp enable to enable the configuration.
[09:23:56] [Velocity Async Event Executor - #0/INFO]: [Core] Reloading saved player identities...
[09:23:56] [Velocity Async Event Executor - #0/INFO]: Successfully loaded!
[09:23:56] [pool-6-thread-1/INFO]: ----------------------------------------------
[09:23:56] [pool-6-thread-1/INFO]:     +==================+
[09:23:56] [pool-6-thread-1/INFO]:     |   SkinsRestorer  |
[09:23:56] [pool-6-thread-1/INFO]:     |------------------|
[09:23:56] [pool-6-thread-1/INFO]:     +==================+
[09:23:56] [pool-6-thread-1/INFO]: ----------------------------------------------
[09:23:56] [pool-6-thread-1/INFO]:     Current version: 14.1.10
[09:23:56] [pool-6-thread-1/INFO]:     This is the latest version!
[09:23:56] [pool-6-thread-1/INFO]: ----------------------------------------------
[09:23:56] [Velocity Async Event Executor - #0/INFO]: Enabled SkinsRestorer v14.1.10
[09:23:57] [Velocity Async Event Executor - #0/INFO]: Loaded snap.conf
[09:23:57] [Velocity Async Event Executor - #0/WARN]: Could not initialize LibraryLoader (missing dependencies?)
[09:23:57] [Velocity Async Event Executor - #0/INFO]: Loaded 0 plugins!
[09:23:57] [main/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 50:cc:74:34:80:6b:fe:5f
[09:23:57] [Netty epoll Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[09:23:57] [main/INFO]: Done (4.7s)!
[09:24:01] [Velocity Async Event Executor - #3/INFO]: Incoming login request for SlimeBlu24 from /51.77.31.53:12881
[09:24:01] [fastlogin Pool Thread #0/INFO]: Handling player SlimeBlu24
[09:24:02] [fastlogin Pool Thread #0/INFO]: Requesting premium login for registered player: SlimeBlu24
[09:24:02] [Velocity Async Event Executor - #5/INFO]: Overridden UUID from 15e44f95-a1f0-4d8c-86c6-af02a7394b35 to e467e403-c10b-3951-b56f-c7c6c6b76936 (based of SlimeBlu24) on com.velocitypowered.proxy.connection.client.LoginInboundConnection@3e6eda45
[09:24:02] [Netty epoll Worker #0/INFO]: [connected player] SlimeBlu24 (/2.39.74.22:10432) has connected
[09:24:02] [Velocity Task Scheduler - #0/WARN]: LuckPerms already has data for player 'SlimeBlu24' - but this data is stored under a different UUID.
[09:24:02] [Velocity Task Scheduler - #0/WARN]: 'SlimeBlu24' has previously used the unique ids [15e44f95-a1f0-4d8c-86c6-af02a7394b35] but is now connecting with 'e467e403-c10b-3951-b56f-c7c6c6b76936'
[09:24:02] [Velocity Task Scheduler - #0/WARN]: The UUID the player is connecting with now is NOT Mojang-assigned (type 3). This implies that THIS server is not authenticating correctly, but one (or more) of the other servers/proxies in the network are.
[09:24:02] [Velocity Task Scheduler - #0/WARN]: If you're using BungeeCord/Velocity, please ensure that IP-Forwarding is setup correctly on all of your backend servers!
[09:24:02] [Velocity Task Scheduler - #0/WARN]: See here for more info: https://luckperms.net/wiki/Network-Installation#pre-setup
[09:24:03] [Netty epoll Worker #0/INFO]: [server connection] SlimeBlu24 -> hub has connected
[09:24:05] [Netty epoll Worker #0/INFO]: [connected player] SlimeBlu24 (/2.39.74.22:10432) has disconnected
[09:24:05] [Netty epoll Worker #0/INFO]: [server connection] SlimeBlu24 -> hub has disconnected
[09:24:07] [Velocity Async Event Executor - #0/INFO]: Incoming login request for SlimeBlu24 from /51.77.31.57:37923
[09:24:07] [fastlogin Pool Thread #3/INFO]: Handling player SlimeBlu24
[09:24:07] [fastlogin Pool Thread #3/INFO]: Requesting premium login for registered player: SlimeBlu24
[09:24:07] [Velocity Async Event Executor - #3/ERROR]: Couldn't pass GameProfileRequestEvent to fastlogin
java.lang.NullPointerException: Cannot invoke "com.github.games647.fastlogin.core.shared.LoginSession.setUuid(java.util.UUID)" because "session" is null
	at com.github.games647.fastlogin.velocity.listener.ConnectListener.onGameprofileRequest(ConnectListener.java:88) ~[?:?]
	at com.github.games647.fastlogin.velocity.listener.Lmbda$27.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[proxy.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[proxy.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[proxy.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[09:24:07] [Netty epoll Worker #3/INFO]: [connected player] SlimeBlu24 (/2.39.74.22:10452) has connected
[09:24:07] [Velocity Task Scheduler - #4/WARN]: LuckPerms already has data for player 'SlimeBlu24' - but this data is stored under a different UUID.
[09:24:07] [Velocity Task Scheduler - #4/WARN]: 'SlimeBlu24' has previously used the unique ids [e467e403-c10b-3951-b56f-c7c6c6b76936] but is now connecting with '15e44f95-a1f0-4d8c-86c6-af02a7394b35'
[09:24:07] [Velocity Task Scheduler - #4/WARN]: The UUID the player is connecting with now is Mojang-assigned (type 4). This implies that Velocity's IP-Forwarding has not been setup correctly on one (or more) of the backend servers.
[09:24:07] [Velocity Task Scheduler - #4/WARN]: See here for more info: https://luckperms.net/wiki/Network-Installation#pre-setup
[09:24:07] [Netty epoll Worker #3/INFO]: [server connection] SlimeBlu24 -> hub has connected
[09:24:11] [Netty epoll Worker #3/INFO]: [connected player] SlimeBlu24 (/2.39.74.22:10452) has disconnected
[09:24:11] [Netty epoll Worker #3/INFO]: [server connection] SlimeBlu24 -> hub has disconnected
[09:24:17] [Thread-11/INFO]: Shutting down the proxy...
[09:24:17] [Thread-11/INFO]: Closing endpoint /0.0.0.0:25565
[09:24:17] [Velocity Async Event Executor - #5/INFO]: HikariPool-1 - Shutdown initiated...
[09:24:17] [Velocity Async Event Executor - #5/INFO]: HikariPool-1 - Shutdown completed.
[09:24:17] [Velocity Async Event Executor - #5/INFO]: 
 
&8[]=====[&7Disabling AdvancedBan&8]=====[]
&8| &cInformation:
&8|   &cName: &7AdvancedBan
&8|   &cDeveloper: &7Leoko
&8|   &cVersion: &72.4.0
&8|   &cStorage: &7MySQL (external)
&8| &cSupport:
&8|   &cGithub: &7https://github.com/DevLeoko/AdvancedBan/issues
&8|   &cDiscord: &7https://discord.gg/ycDG6rS
&8| &cTwitter: &7@LeokoGar
&8[]================================[]&r
 
[09:24:17] [Velocity Async Event Executor - #5/INFO]: Safely shutting down scheduler. This could take up to one minute.
[09:24:17] [Velocity Async Event Executor - #5/INFO]: fastlogin - Shutdown initiated...
[09:24:17] [Velocity Async Event Executor - #5/INFO]: fastlogin - Shutdown completed.
[09:24:17] [Velocity Async Event Executor - #5/INFO]: Starting shutdown process...
[09:24:17] [Velocity Async Event Executor - #5/INFO]: Closing messaging service...
[09:24:17] [Velocity Async Event Executor - #5/INFO]: Closing storage...
[09:24:17] [Velocity Async Event Executor - #5/INFO]: luckperms-hikari - Shutdown initiated...
[09:24:17] [Velocity Async Event Executor - #5/INFO]: luckperms-hikari - Shutdown completed.
[09:24:17] [Velocity Async Event Executor - #5/INFO]: Goodbye!
```

### Plugin version

Build #1039 on CodeMC

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
The reported IP address is largely different. `2.39.74.XX` and `51.77.31.XX`. FastLogin heavily depends on them to be consistent. It's again TCPShield that modifies this.

**Comment by SlimeBluKing** [comment]
and what should i do?

**Comment by zMario34** [comment]
Got this too.

**Comment by games647** [comment]
@zMario34 Sorry I had to remove your link, because it's not possible to verify the source of the file from the link you posted. Please reference only official sources where we could check if it's from the original authors and not from an untrusted third-party. 

Discord links are fine as long as mentioned details are accessible. You could for example reference the message from an accessible channel.

**Comment by zMario34** [comment]
Alright.
The issue is still present after the 2.5.6 version given by Tcpshield.

**Comment by Neeonn** [comment]
Hello, I took the liberty of testing and contacted TCPShield for more information.
They gave me the same build that @zMario34 received and it seems to be working fine. I'm not seeing skins but that may be an issue with me, I'll have to check later. That error goes away when using the mentioned TCPShield build.

They also told me the following:
> fastLogin by-pass our event listener, you can't use it with TCPShield
> if that build works (somehow), then its fine, but generally not recommended
you showed me the github issue where the problem is with fastLogin, that's why I gave you the answer.

**Comment by games647** [comment]
Version 2.5.6 of TCPShield should fix the incompatibility, because it sets the correct IP address before FastLogin, so FastLogin only sees the correct IP, which is no longer modified. 

Reference: https://github.com/TCPShield/RealIP/commit/41ff3f412c96a0808e95892224d62bd33e7b16ca
Changing the IP address during login is a very dangerous process. FastLogin assumed this value stays constant as there is now official method of changing it.
