### ISSUE TITLE
bungeecord + lobby + server

### ISSUE THREAD

**Issue by comonier** [games647/FastLogin#732]
Hello! Its my first time doing it so i need some help.

i am trying make a server with that setup
1 a bungeecord 
2 a lobby
3 a cracked server
4 a premium server
-
1) using plugins: authme + fastlogin (bukkit/spigot version) on lobby and cracked server
2) and using autheme and fastlogin (bungecoord version) on bungecoord
-
config.yml from bungeecord:
```java
prevent_proxy_connections: false
listeners:
- query_port: 25577
  motd: '&1HBS'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    hu3.net.br: lobby
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: false
  host: 0.0.0.0:25560
  max_players: 50
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  comonier:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: uuid
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: ''
    address: localhost:25561
    restricted: false
  server1:
    motd: 'premium'
    address: localhost:25735
    restricted: false
  server2:
    motd: 'cracked'
    address: localhost:25734
    restricted: false
```
config of authme bungeecord
```java
# List of servers in the network where authme is installed
authServers: 
- lobby
# Consider every server as an auth server
allServersAreAuthServers: true
commands:
    # Allows or not commands to be performed if user is not logged in
    requireAuth: true
    # List of commands allowed to be perform without being authenticated
    whitelist: 
    - /login
    - /register
    - /l
    - /reg
    - /email
    - /captcha
# Allows or not user to talk in chat if he is not logged in
chatRequiresAuth: true
serverSwitch:
    # Kick all players who switch servers without being authenticated (eg. plugin teleport)
    requiresAuth: true
    kickMessage: Authentication required.
# Enable auto-login between servers
autoLogin: true
# If enabled, unlogged users will be sent to the unloggedUserServer server!
sendOnLogout: true
# If sendOnLogout is enabled, unlogged users will be sent to this server!
unloggedUserServer: 'lobby'
```
config from fastlogin of bungecoord:
```java
anti-bot:
  enabled: true
  connections: 600
  expire: 10
autoRegister: true
respectIpLimit: true
secondAttemptCracked: false
switchMode: false
premiumUuid: true
nameChangeCheck: true
forwardSkin: true
premium-warning: true
ip-addresses: []
mojang-request-limit: 600
auto-register-unknown: false
autoLogin: true
autoLoginFloodgate: true
allowFloodgateNameConflict: false
autoRegisterFloodgate: true
floodgatePrefixWorkaround: true
driver: 'org.sqlite.JDBC'
database: '{pluginDir}/FastLogin.db'
proxies:
```
fastlogin config from lobby:
```java
anti-bot:
  enabled: true
  connections: 600
  expire: 10
autoRegister: true
respectIpLimit: true
secondAttemptCracked: false
switchMode: false
premiumUuid: true
nameChangeCheck: true
forwardSkin: true
premium-warning: true
ip-addresses: []
mojang-request-limit: 600
auto-register-unknown: false
autoLogin: true
autoLoginFloodgate: true
allowFloodgateNameConflict: true
autoRegisterFloodgate: true
floodgatePrefixWorkaround: true
driver: 'org.sqlite.JDBC'
database: '{pluginDir}/FastLogin.db'
proxies:
```

authme config hook from lobby:
```java
Hooks:
    multiverse: true
    bungeecord: true
    sendPlayerTo: lobby
    disableSocialSpy: false
    useEssentialsMotd: false
```

lobby: server.properties: online-mode=false
lobby: spigot.yml bungeecord: true
the allowed-proxies.txt file already have the uuid from config.yml [bungeecord] in stats
-
so... who join on server ip join on lobby ( working fine )

For now, let's forget about the connection between the lobby and the servers, to premium or cracked, that I intend to do.

For now, I would just like a support to understand where I'm going wrong in the Bungeecord and Lobby settings regarding their configuration files and the fastlogin and authme plugins to know why the auto login doesn't work for my original premium account that is logged in using mojang's own client. 

Thank you very much first of all in case you decide to try to help me 😍

![image](https://user-images.githubusercontent.com/19571541/154825545-ddba0988-d9ab-4806-b9bf-c973a25096e8.png)

console from lobby
[23:03:35 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=comonier} with ID IP/DOOR
[23:06:04 INFO]: comonier issued server command: /premium
![image](https://user-images.githubusercontent.com/19571541/154825496-535b879b-f1fd-4265-aee8-f175c529b6b8.png)

console from bungee
23:03:34 [INFO] [comonier] <-> ServerConnector [lobby] has connected

serverip: hu3.net.br (if you want to test it)

```java
23:59:33 [SEVERE] Feb 19, 2022 11:59:33 PM com.github.games647.fastlogin.core.CommonUtil initializeLoggerService
INFO: Initialize logging service

23:59:33 [WARNING] [FastLogin] This driver org.sqlite.JDBC is not supported on this platform
23:59:33 [WARNING] [FastLogin] Please choose either MySQL (Spigot, BungeeCord), SQLite (Spigot, Sponge) or MariaDB (Sponge, Velocity)
java.lang.[ClassNotFoundException](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+classnotfoundexception): org.sqlite.JDBC
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.[ClassLoader](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+classloader).loadClass([ClassLoader](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+classloader).java:520)
    at java.base/java.lang.Class.forName0(Native [Method](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+method))
    at java.base/java.lang.Class.forName(Class.java:375)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.checkDriver(FastLoginCore.java:248)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:207)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:89)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
maybe that is the big problem ? should i create an mysql database to fastlogin from bungeecord ?

**Comment by comonier** [comment]
well it took me a while but I managed to finally create a mysql database a user and guarantee the permissions for the user created to the database, I edited the bungeecord fastlogin config with this information without the comment in front...
now there is another error in the console

```java
00:49:39 [SEVERE] Feb 20, 2022 12:49:39 AM com.github.games647.fastlogin.core.CommonUtil initializeLoggerService
INFO: Initialize logging service

00:49:39 [SEVERE] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

00:49:39 [SEVERE] Feb 20, 2022 12:49:39 AM fastlogin.hikari.HikariDataSource <init>
INFO: FastLogin - Starting...

00:49:39 [SEVERE] Feb 20, 2022 12:49:39 AM fastlogin.hikari.util.DriverDataSource <init>
WARNING: Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.

00:49:40 [SEVERE] Feb 20, 2022 12:49:40 AM fastlogin.hikari.pool.HikariPool throwPoolInitializationException
SEVERE: FastLogin - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
    at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
    at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
    at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
    at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
    at fastlogin.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    at fastlogin.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
    at fastlogin.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
    at fastlogin.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
    at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
    at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:115)
    at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
    at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:83)
    at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:10)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:234)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:89)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
    at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
    at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
    at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
    at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
    at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
    at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
    ... 18 more
Caused by: java.net.ConnectException: Connection refused
    at java.base/sun.nio.ch.Net.pollConnect(Native Method)
    at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
    at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
    at java.base/java.net.Socket.connect(Socket.java:633)
    at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
    at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
    ... 21 more


00:49:40 [WARNING] Exception encountered when loading plugin: FastLogin
fastlogin.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
    at fastlogin.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
    at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
    at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:115)
    at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
    at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:83)
    at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:10)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:234)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:89)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
    at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
    at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
    at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
    at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
    at fastlogin.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    at fastlogin.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
    at fastlogin.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
    at fastlogin.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
    at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
    ... 10 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
    at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
    at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
    at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
    at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
    at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
    at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
    ... 18 more
Caused by: java.net.ConnectException: Connection refused
    at java.base/sun.nio.ch.Net.pollConnect(Native Method)
    at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
    at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
    at java.base/java.net.Socket.connect(Socket.java:633)
    at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
    at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
    ... 21 more
    ```

**Comment by comonier** [comment]
a second question on **proxies:** in the config from fastlogin (of bungeecord)
what should i add ? ip/door from bungeecord only ? or i should add all 
bugeecord / lobby / server1 / server 2 doors ?
example:
```java
proxies:
  - 'hu3.net.br:25560'  (bungeecord)
  - 'hu3.net.br:25561'  (lobby)
  - 'hu3.net.br:25735'  (premium server)
  - 'hu3.net.br:25734'  (cracked server)
```

**Comment by games647** [comment]
> java.net.ConnectException: Connection refused

That means there is no service listening on the given host and port number.

**Comment by comonier** [comment]
> > java.net.ConnectException: Connection refused
> 
> That means there is no service listening on the given host and port number.

which one ?

is referring to information in the proxy part? where I put 4 times ip / port ?

which one should i for?

just the bunge one?

**Comment by games647** [comment]
From the server where your log is from. Likely your proxy, but you didn't provided that information.

**Comment by comonier** [comment]
mas essa

> From the server where your log is from. Likely your proxy, but you didn't provided that information.

ok i will check it - but in relation to my question about the proxies part of the fastlogin configuration, what should I do there? the ip / port of the server ? in the case only of the bunge ?

**Comment by games647** [comment]
If you mean: https://github.com/games647/FastLogin/blob/033fdd55ae105dd5bd0fb1709a87b29ee16e2981/core/src/main/resources/config.yml#L294

Those are web proxies for contacting Mojang. That are not Minecraft servers.

**Comment by comonier** [comment]
> If you mean:
> 
> https://github.com/games647/FastLogin/blob/033fdd55ae105dd5bd0fb1709a87b29ee16e2981/core/src/main/resources/config.yml#L294
> 
> Those are web proxies for contacting Mojang. That are not Minecraft servers.

by default I should leave this space blank?

or do you have any finromação that you can guide me to put there already pre-defined?

**Comment by comonier** [comment]
> From the server where your log is from. Likely your proxy, but you didn't provided that information.

So... continuing from here, as it's the first time I create a mysql database + 1 user to access it and grant all permissions to the user, I'm having a little difficulty here to test if this information is correct... I did some adjustments and I tried to restart the bungeecord now it gives other error messages that I will post here for you to interpret ok?

```java
09:45:03 [SEVERE] Feb 20, 2022 9:45:03 AM com.github.games647.fastlogin.core.CommonUtil initializeLoggerService
INFO: Initialize logging service

09:45:04 [SEVERE] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

09:45:04 [SEVERE] Feb 20, 2022 9:45:04 AM fastlogin.hikari.HikariDataSource <init>
INFO: FastLogin - Starting...

09:45:04 [SEVERE] Feb 20, 2022 9:45:04 AM fastlogin.hikari.util.DriverDataSource <init>
WARNING: Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.

09:45:04 [SEVERE] Feb 20, 2022 9:45:04 AM fastlogin.hikari.HikariDataSource <init>
INFO: FastLogin - Start completed.

09:45:04 [INFO] Enabled plugin FastLogin version 1.11-SNAPSHOT-033fdd5 by games647, https://github.com/games647/FastLogin/graphs/contributors
```

**Comment by comonier** [comment]
WOWWWWWWWWWWWWWW I HAVE SKIN NOW IT WORKS
![image](https://user-images.githubusercontent.com/19571541/154843290-cee051fb-7416-4f32-9caf-6f2d97c2739b.png)

**Comment by games647** [comment]
>by default I should leave this space blank?
or do you have any information that you can guide me to put there already pre-defined?

Leave it blank. Only necessary if you hit the Mojang rate limit

**Comment by comonier** [comment]
now I'm trying to learn how to have a premium server and a cracked one, (of course the second option is not a problem) it is already released for users to enter, whether cracked or premium, even premiums enter without having to have a password if they activate this option from fastlogin, but I thought that I could leave the option online-mode: true in the server.properties on the premium server too, because as I am authenticated by fastlogin it would not block anymore, but it keeps blocking and sending the online-mode to false ... any tips to make it possible to connect the lobby to the premium server only for premium players?

**Comment by comonier** [comment]
> now I'm trying to learn how to have a premium server and a cracked one, (of course the second option is not a problem) it is already released for users to enter, whether cracked or premium, even premiums enter without having to have a password if they activate this option from fastlogin, but I thought that I could leave the option online-mode: true in the server.properties on the premium server too, because as I am authenticated by fastlogin it would not block anymore, but it keeps blocking and sending the online-mode to false ... any tips to make it possible to connect the lobby to the premium server only for premium players?

I don't want any player to be able to enter the server, I just want premium accounts to be able to enter, understand? if it is mandatory to change the online-mode to false to allow the connection from the lobby to the server in question, how to configure so that users without premium UUID can enter?

**Comment by comonier** [comment]
> > now I'm trying to learn how to have a premium server and a cracked one, (of course the second option is not a problem) it is already released for users to enter, whether cracked or premium, even premiums enter without having to have a password if they activate this option from fastlogin, but I thought that I could leave the option online-mode: true in the server.properties on the premium server too, because as I am authenticated by fastlogin it would not block anymore, but it keeps blocking and sending the online-mode to false ... any tips to make it possible to connect the lobby to the premium server only for premium players?
> 
> I don't want any player to be able to enter the server, I just want premium accounts to be able to enter, understand? if it is mandatory to change the online-mode to false to allow the connection from the lobby to the server in question, how to configure so that users without premium UUID can enter?

so... basically what I need now is to ignore the premium-only server and use the cracked server as a test to try to allow only users with premium account uuid to enter it, understand?

when I get this I copy this information to the premium server and release the cracked accounts entry on the cracked server again

**Comment by games647** [comment]
>because as I am authenticated by fastlogin it would not block anymore, but it keeps blocking and sending the online-mode to false

Why is that necessary? Your server is mixed onlinemode anyway, so it's better to keep it disabled.

>any tips to make it possible to connect the lobby to the premium server only for premium players?

You can use FastLogin's switchMode feature for that.

**Comment by comonier** [comment]
> > because as I am authenticated by fastlogin it would not block anymore, but it keeps blocking and sending the online-mode to false
> 
> Why is that necessary? Your server is mixed onlinemode anyway, so it's better to keep it disabled.
> 
> > any tips to make it possible to connect the lobby to the premium server only for premium players?
> 
> You can use FastLogin's switchMode feature for that.

i need have it [fastlogin] installed on bungeecoord [the fastlogin bungeecord version] + another plugin fastlogin bukket on lobby ? + one on servers ?

**Comment by games647** [comment]
The plugin only needs to be installed on the server where your login plugin is.

**Comment by comonier** [comment]
> The plugin only needs to be installed on the server where your login plugin is.

if you have authme bungee in bungeecord and authme bukkit in the lobby, do I keep fastlogin bungeecord and fastlogin bukkit in the lobby too? that's it ?

so can i delete fast login from servers i want to release 1 for premium only and 1 for cracked and premium?

**Comment by comonier** [comment]
my objective for now is just to try through some of the features of fastlogin to allow only premium players to be able to enter the server comming from the lobby is it possible? what do i need to do for this? install fastlogin on the server too?

bungeecord  > lobby > server

bungeecord in offline mode, lobby in off line mode and server in offline mode
fastlogin get premium uuid, fastlogin block cracked uuid from join on server coming from looby

**Comment by comonier** [comment]
i have authme bungeecord on bungeecord server and authme bukkit on lobby server (i dont know if i really need have both but the wiki from authme say to do that) is the same to fastlogin right ?

**Comment by games647** [comment]
>so i need e fastlogin get premium uuid, fastlogin block cracked uuid from join on server coming from looby

The decision needs to be made at login. There is no concept coming through X. If a player connects to your proxy, BungeeCord or Velocity, a decision has to be made if this should be an onlinemode connection. There is no way to change it later.

**Comment by comonier** [comment]
i had a friend who have a server [ z12 ] in the past he had 2 servers 

z 12 Epic ( to cracked ) with option to who had premium enable it [by fastlogin]

and other server called origins

on origins - only premium accounts can do login and join

do you mean he was not using fastlogin to configurate that ?

that option was on lobby drom z12 network server.... 

do you mean probally that origins server to premium only is not a server in the same host ? but probally another host?

**Comment by games647** [comment]
You can just the server directly. Like `premium.mc-server.com` or `cracked.mc-server.com`, but it's not possible to do that after a server switch.

**Comment by comonier** [comment]
> 



> You can just the server directly. Like `premium.mc-server.com` or `cracked.mc-server.com`, but it's not possible to do that after a server switch.

DO YOU MEAN ..... 
insert that informations on config.yml from bungeecord ? and create and cloudflare to same ip with subdomain ? [changing door with srv?]

**Comment by comonier** [comment]
well i just found another solution for the problem....
ou cloudflare i back original configuration from the premium server 
A > hu3.net.br > IP [proxy up]
SRV > @ > premium door > hu3.net.br
and create another SRV to bungeecord door
SRV > mc > bungee door > hu3.net.br 

so i need to give 2 ips because i not found a solution to keep inside the lobby 2 ways to player join in a premium and a cracked server =(

**Comment by games647** [comment]
BungeeCord can differentiate users based on the hostname they are connecting to. So you don't need two IP addresses.
