### ISSUE TITLE
Incompatible with ProtocolLib version > 4.8

### ISSUE THREAD

**Issue by MarkoBogSrb** [games647/FastLogin#749]
### What happened?

```
[03:37:21 INFO]: [FastLogin] Handling player NoSugar365
[03:37:21 INFO]: [FastLogin] Requesting premium login for registered player: NoSugar365
[03:37:21 INFO]: [FastLogin] Enabling onlinemode encryption for UNKNOWN[/127.0.0.1:62683]
[03:37:21 WARN]: [FastLogin] Error occurred on thread pool
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayerFactory
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayerFactory
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.getNetworkManager(VerifyResponseTask.java:203) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:233) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:125) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:101) ~[FastLoginBukkit.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.server.TemporaryPlayerFactory
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.getNetworkManager(VerifyResponseTask.java:203) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:233) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:125) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:101) ~[FastLoginBukkit.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        ... 3 more
[03:37:51 INFO]: Disconnecting /127.0.0.1:62683: Took too long to log in
[03:37:51 INFO]: /127.0.0.1:62683 lost connection: Took too long to log in
```
Using latest DEV version of fastlogin, authmereloaded, and protocollib

### Plugin list

AuthMe, Chunky, ChunkyBorder, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), FastLogin, GSit, LuckPerms, PlaceholderAPI,  ProtocolLib, SkinsRestorer, spark, StaffPlus, Vault, WorldGuard

### Plugin version

1.11-SNAPSHOT-59eb9ce

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by MarkoBogSrb** [comment]
Downgrading to 4.8 works just fine. Thank you!
