### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Uniqeues** [games647/FastLogin#764]
### What happened?

[20:11:53 ERROR]: Could not pass event PlayerJoinEvent to EssentialsSpawn v2.20.0-dev+2-e12f1b5
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[paper-1.18.2.jar:git-Paper-267]
        at com.earth2me.essentials.Essentials.runTaskAsynchronously(Essentials.java:1140) ~[EssentialsX-2.20.0-dev+3-c4f10d9.jar:?]
        at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.onPlayerJoin(EssentialsSpawnPlayerListener.java:75) ~[EssentialsXSpawn-2.20.0-dev+2-e12f1b5.jar:?]
        at com.earth2me.essentials.spawn.EssentialsSpawn.lambda$onEnable$1(EssentialsSpawn.java:49) ~[EssentialsXSpawn-2.20.0-dev+2-e12f1b5.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-267]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:305) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin list

Authme, BotSentry, Essentials, EssentialsChat, EssentialsSpawn, WorldEdit, FastLogin, ItemEdit, LiteBans, Luck Perms, Multiverse-core, Mv-nether, plhidepro, projectileknockback, protocollib, worldguard

### Plugin version

Newest

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
This is a different plugin: 

PlayerJoinEvent to EssentialsSpawn
