### ISSUE TITLE
SQLException: HOUR_OF_DAY

### ISSUE THREAD

**Issue by msmanui** [games647/FastLogin#766]
### What happened?

When a player logins to the network it will drop this error. Only when he has premium enable.
```
[23:53:50] [FastLogin Pool Thread #3/INFO] [FastLogin]: Handling player PlayerName
[23:53:50] [FastLogin Pool Thread #3/ERROR] [FastLogin]: Failed to query profile: PlayerName
java.sql.SQLException: HOUR_OF_DAY: 2 -> 3
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:939) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at fastlogin.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProxyResultSet.java) ~[?:?]
	at com.github.games647.fastlogin.core.AuthStorage.parseResult(AuthStorage.java:176) ~[?:?]
	at com.github.games647.fastlogin.core.AuthStorage.loadProfile(AuthStorage.java:143) ~[?:?]
	at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:25) ~[?:?]
	at com.github.games647.fastlogin.bungee.task.AsyncPremiumCheck.run(AsyncPremiumCheck.java:40) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.mysql.cj.exceptions.WrongArgumentException: HOUR_OF_DAY: 2 -> 3
	at jdk.internal.reflect.GeneratedConstructorAccessor89.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:165) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:51) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromTimestamp(AbstractDateTimeValueFactory.java:89) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.protocol.a.MysqlBinaryValueDecoder.decodeTimestamp(MysqlBinaryValueDecoder.java:85) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:89) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	... 10 more
Caused by: java.lang.IllegalArgumentException: HOUR_OF_DAY: 2 -> 3
	at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2826) ~[?:?]
	at java.util.Calendar.updateTime(Calendar.java:3433) ~[?:?]
	at java.util.Calendar.getTimeInMillis(Calendar.java:1815) ~[?:?]
	at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:161) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromTimestamp(SqlTimestampValueFactory.java:51) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromTimestamp(AbstractDateTimeValueFactory.java:89) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.protocol.a.MysqlBinaryValueDecoder.decodeTimestamp(MysqlBinaryValueDecoder.java:85) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:89) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91) ~[waterfall-1.18-468.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:e767b40:480]
	... 10 more
```

### Plugin version

Latest

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Check that the timezone of your database and your Java server are the same.

**Comment by msmanui** [comment]
The time of the machine where the mariadb is hosted says
![image](https://user-images.githubusercontent.com/63617395/160335646-6bb351c2-c171-4781-8edb-7d3a88347a9d.png)
 Mon Mar 28 06:01:08 UTC 2022

The time of the machine where the server is (Another machine)
Mon Mar 28 02:01:44 EDT 2022


Both need to match??

**Comment by games647** [comment]
Yes, because the last login timestamp is updated locally on the database server `ON_UPDATE=CURRENT_TIMESTAMP`, but it's read by Minecraft server. The error is about seeing the last login in the future.
