### ISSUE TITLE
NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi

### ISSUE THREAD

**Issue by MenachemMarozov** [games647/FastLogin#769]
### What happened?

when i try to run the command i get an error in chat
"An internal error occurred while attempting to perform this command "

### What did you expect?

it to run successfully 

### Steps to reproduce

typing /premium

### Plugin list

AdvancedHelp, AdvancedPortals, AdvancedReplay*, AutoPlug-Plugin, BedrockPlayerManager, BedWars, ClientDetector, ConsoleSpamFix, CoreProtect, DecentHolograms, DiscordSRV, EazyNick, Essentials, EssentialsAntiBuild, EssentialsProtect, FastLogin, floodgate, Geyser-Spigot, GeyserUpdater, Global_Powertool, GriefPrevention, HideStream*, Horse_Inspector, InvSeePlusPlus, IP-Check*, LightAntiCheat, LiveKit, LockettePro*, LoginSecurity*, LuckPerms, LWC, Matrix, MineableSpawners, MobArena, MoneyHunters, MoneyNote, MOTD, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, NexEngine, NiceWeather, NoteBlockAPI, NPCLibPlugin*, OpenInv, PaperMoney, PlaceholderAPI, ProtocolLib, RankGrantPlus, SBA, SecondThreadAPI*, SkinsRestorer, SkQuery, Skript, Skywars, SmartHarvest, Spleef*, StaffPlus, SuperVanish, TAB, ThrowableFireballs, TNTRun_reloaded, Vault, VaultChatFormatter*, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard, XrayAlerts*

### Configuration file

i did not change any configs

### Server log

```shell
[Wed 02:42:29 INFO  Server/PlayerConnection] Magnorite issued server command: /fastlogin:premium
 
[10:42 PM]
- [Wed 02:42:29 ERROR Server/PlayerConnection] null
org.bukkit.command.CommandException: Cannot execute command 'fastlogin:premium' in plugin FastLogin v1.11-SNAPSHOT-666fabd - plugin is disabled.
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098)
    at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46)
    at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376)
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369)
    at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1503)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
    at net.minecraft.server
```

### Plugin version

 1.11-SNAPSHOT-666fabd

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by From-pErfo** [comment]
`plugin is disabled`
There should be other error messages before this

**Comment by MenachemMarozov** [comment]
[03:11:38 INFO]: [FastLogin] Enabling FastLogin v1.11-SNAPSHOT-666fabd
[03:11:38 ERROR]: Error occurred while enabling FastLogin v1.11-SNAPSHOT-666fabd (Is it up to date?)
java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.initializeFloodgate(FastLoginBukkit.java:175) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:100) ~[FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
[03:11:38 INFO]: [FastLogin] Disabling FastLogin v1.11-SNAPSHOT-666fabd
[03:11:38 INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.

**Comment by games647** [comment]
FastLogin is incompatible with the Flood version you have installed.

**Comment by MenachemMarozov** [comment]
i have the latest floodgate version (2.0), 
can you update the plugin to support it?

**Comment by games647** [comment]
FastLogin supports that Floodgate version. Could you check if that missing class file is present in Floodgate by opening the floodgate plugin with any archiver program. The file should be at `org/geysermc.floodgate.api.FloodgateApi`

**Comment by Smart123s** [comment]
Could not reproduce the issue on FastLogin https://github.com/games647/FastLogin/commit/a32791687cb21534f26975a7c185470bba034e05 with latest Floodgate & Geyser. Could you upload the Floodgate JAR file you have issues with? (put it in a .zip archive, GitHub doesn't allow posting .jar files directly). I'd like to try it.

**Comment by MenachemMarozov** [comment]
im not sure how, here is the geyser/flood plugins 
https://www.sendbig.com/view-files?Id=9c3deb70-8f6a-7b53-b87a-184c6399945d

**Comment by games647** [comment]
Please post the startup log. It could be that an issue during class loading

**Comment by Smart123s** [comment]
> im not sure how, here is the geyser/flood plugins https://www.sendbig.com/view-files?Id=9c3deb70-8f6a-7b53-b87a-184c6399945d

URL is valid for 7 days only. Archived URL: https://web.archive.org/web/20220407143147/https://sss3.sendbig.com/api/Files/download/2945070/9c3deb70-8f6a-7b53-b87a-184c6399945d/0

Plugin versions in zip:
- https://github.com/GeyserMC/Geyser/commit/3251d9010c9596dbb9d5b5d25a3b25a2330181bf (2022. Jan. 01.)
- https://github.com/GeyserMC/Floodgate/commit/0216b6d79821ef861445ff8cc7cdc0431d3e80f1 (2021. Jul. 05.)

These version are really old. Could you try updating to the latest version?

Here's what's happend to me on a clean server with only the plugins & configs you've provided (even without FastLogin):
On startup:
```
[16:47:26 INFO]: [floodgate] Enabling floodgate v2.0-SNAPSHOT
[16:47:26 ERROR]: Error occurred while enabling floodgate v2.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:156) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:59) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:124) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.SpigotPlatform.enable(SpigotPlatform.java:48) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:62) ~[floodgate-spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-276]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-276]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-276]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-276]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-276]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-276]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-276]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Is whitelisted cannot be null
        at org.geysermc.floodgate.shaded.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.util.ClassNames.checkNotNull(ClassNames.java:219) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:118) ~[floodgate-spigot.jar:?]
        ... 16 more
[16:47:26 INFO]: [floodgate] Disabling floodgate v2.0-SNAPSHOT
```

When joining from BE:
![image](https://user-images.githubusercontent.com/28480228/162227280-14a1e37f-96a3-4c57-b321-da705ee3d3b9.png)

**Comment by MenachemMarozov** [comment]
That's strange bc I have geyser auto updater plugin

**Comment by Smart123s** [comment]
> That's strange bc I have geyser auto updater plugin

Well, it's not doing it's job then.

You can also check the modification date of the files:

![modificationdate](https://user-images.githubusercontent.com/28480228/162270814-89761782-f308-4599-99cc-e44d511a2a58.png)

**Comment by MenachemMarozov** [comment]
so i re-downloaded geyser and floodgate and it worked! thanks for all your help!
