### ISSUE TITLE
Plugin make an exception on premium

### ISSUE THREAD

**Issue by NotZer0Two** [games647/FastLogin#784]
### What happened?

when users do /premium again the plugin make an exception

### What did you expect?

premium

### Steps to reproduce

I just downloaded the plugin and started the server

### Plugin list

2FA, AdvancedEnchantments, AdvancedReplay, ajParkour, AmethtystMCUtils, AntiCheatReplay, AntiCommandTab, AntiDrop, AuctionMaster, AuthMe, AutoBroadcast, AutoSell, BattlePass, BeastWithdraw, BlockParticles, BountyHunters, BowVoteParty, ChatGames, Citizens, CombatLogX, CommandAlias, CommandNPC, CommandRegions, CommandToItem, ConsoleSpamFix, CrazyCrates, CryptoCurrency, DeluxeMenus, DeluxeTags, Duels, EazyNick, EconomyShopGUI, EpicChatPrefix, Essentials, EssentialsSpawn, EZColors, FastAsyncWorldEdit, FastLogin, GambleBarLite, GuiBalance, Guilds, HolographicDisplays, InfiniteVouchers, InteractiveBooks, InteractiveChat, JukeBox, KnockbackMaster, LuckPerms, Minepacks, MineResetLite, MoneyPouch, MovingDevApi, Multiverse-Core, MVdWPlaceholderAPI, NBTAPI, NoteBlockAPI, OldCombatMechanics, PlaceholderAPI, PlotSquared, PluginManager, PlugMan, PowerLib, PrisonRanksX, ProtocolLib, React, RevEnchants, RewardPRO, SimpleRename, SirBlobmanCore, SkinsRestorer, spark, TAB, TitleManager, TradeSystem, UltimateKits, UltimateRepairing, Vault, ViaBackwards, ViaRewind, ViaVersion, VoteRoulette, Votifier, Vulcan, WorldEdit, WorldGuard, WorldGuardFlyStop

### Configuration file

https://www.toptal.com/developers/hastebin/jiyekevilo.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/lihufiyoho.properties
```

### Plugin version

1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version.

**Comment by NotZer0Two** [comment]
can you link me the new one?

**Comment by From-pErfo** [comment]
> can you link me the new one?

https://ci.codemc.org/job/Games647/job/FastLogin/

**Comment by NotZer0Two** [comment]
now i have a problem on the player join

```
[07:49:46 ERROR]: [FastLogin] Unhandled exception occured in onAsyncPacket() for FastLogin
java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getMeta(Ljava/lang/String;)Ljava/util/Optional;
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.isFastLoginPacket(ProtocolLibListener.java:103) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:83) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:642) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) ~[?:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Comment by games647** [comment]
Outdated Protocollib version.

**Comment by NotZer0Two** [comment]
Solved
