### ISSUE TITLE
Console error when connecting a player

### ISSUE THREAD

**Issue by iammehdib** [games647/FastLogin#802]
### What happened?

Since I use the fork of TacoSpigot which is NachoSpigot I have error that appears in the console when connecting any type of player (premium or crack).

### What did you expect?

test

### Steps to reproduce

1. Install NachoSpigot 1.8.9 for the server;
2. Install the latest version of FastLoginBukkit and AuthMe-5.6.0-beta2 plugins.
3. Start the server and connect to the server

### Plugin list

Authme

### Configuration file

https://www.toptal.com/developers/hastebin/exageqaxes.yaml

### Server log

```shell
[00:18:19 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to FastLogin v1.11-SNAPSHOT-4f3c8ad
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-NachoSpigot-"74ed0ea"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-NachoSpigot-"74ed0ea"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-NachoSpigot-"74ed0ea"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:490) ~[server.jar:git-NachoSpigot-"74ed0ea"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) ~[server.jar:git-NachoSpigot-"74ed0ea"]
        at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:255) ~[server.jar:git-NachoSpigot-"74ed0ea"]
        at net.minecraft.server.v1_8_R3.LoginListener.lambda$a$1(LoginListener.java:181) ~[server.jar:git-NachoSpigot-"74ed0ea"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.AsyncPlayerPreLoginEvent.getPlayerProfile()Lcom/destroystokyo/paper/profile/PlayerProfile;
        at com.github.games647.fastlogin.bukkit.listener.PaperCacheListener.lambda$onAsyncPlayerPreLogin$0(PaperCacheListener.java:60) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_312]
        at com.github.games647.fastlogin.bukkit.listener.PaperCacheListener.onAsyncPlayerPreLogin(PaperCacheListener.java:60) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-NachoSpigot-"74ed0ea"]
        ... 9 more
```

### Plugin version

v1.11-SNAPSHOT-4f3c8ad

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
What's your server version?

**Comment by iammehdib** [comment]
![screeen](https://user-images.githubusercontent.com/100452676/172068780-656bd00d-29a1-4275-a59b-2d928f4cb103.png)

**Comment by iammehdib** [comment]
```
[01:01:43 WARN]: [FastLogin] Cannot access proxy field
java.lang.NoSuchFieldException: velocitySupport
        at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_312]
        at com.github.games647.fastlogin.bukkit.BungeeManager.isProxySupported(BungeeManager.java:104) [FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.BungeeManager.detectProxy(BungeeManager.java:116) [FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.BungeeManager.initialize(BungeeManager.java:91) [FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:108) [FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [server.jar:git-NachoSpigot-"74ed0ea"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-NachoSpigot-"74ed0ea"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393) [server.jar:git-NachoSpigot-"74ed0ea"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:392) [server.jar:git-NachoSpigot-"74ed0ea"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:351) [server.jar:git-NachoSpigot-"74ed0ea"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:402) [server.jar:git-NachoSpigot-"74ed0ea"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:366) [server.jar:git-NachoSpigot-"74ed0ea"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:328) [server.jar:git-NachoSpigot-"74ed0ea"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:295) [server.jar:git-NachoSpigot-"74ed0ea"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:559) [server.jar:git-NachoSpigot-"74ed0ea"]
```

I also get this error when I start my server

**Comment by iammehdib** [comment]
No

**Comment by games647** [comment]
Then don't use the TCPShield version. As noted in the release description, this is a special version.

**Comment by iammehdib** [comment]
Okey sorry
