### ISSUE TITLE
Invalid session

### ISSUE THREAD

**Issue by CristianoRino** [games647/FastLogin#803]
### What happened?

[00:32:45] [Craft Scheduler Thread - 9 - FastLogin/INFO]: [FastLogin] Handling player Cristiano_Rino
[00:32:45] [Craft Scheduler Thread - 9 - FastLogin/INFO]: [FastLogin] Requesting premium login for registered player: Cristiano_Rino
[00:32:46] [Craft Scheduler Thread - 9 - FastLogin/INFO]: [FastLogin] Enabling onlinemode encryption for UNKNOWN[/182.106.212.145:33973]
[00:32:57] [Craft Scheduler Thread - 9 - FastLogin/ERROR]: [FastLogin] Failed to connect to session server
java.net.UnknownHostException: sessionserver.mojang.com
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
	at com.github.games647.craftapi.resolver.MojangResolver.hasJoined(MojangResolver.java:80) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:140) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:101) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.lambda$runAsync$0(AsyncScheduler.java:70) ~[FastLoginBukkit.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1612]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1612]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1612]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

### What did you expect?

No response

### Steps to reproduce

No response

### Plugin list

Authme，whitelist，ProtocolLib，FastLogin

### Configuration file

No response

### Server log

```shell
No response
```

### Plugin version

1.11-SNAPSHOT-fc50c99

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Check your DNS settings. Your server isn't able to find the Mojang servers. That would happen also without FastLogin with an onlinemode server.

**Comment by CristianoRino** [comment]
My English is so bad that I can only use a translator to translate it. Please forgive me! I have tried to choose a better DNS, but it still doesn't work. A login rejection report of "invalid session" will be generated. The following are the records generated in the background. If I use genuine authentication, I won't be denied access to the server. Thank you very much for your reply!!!
I have also tried to downgrade protocollib, but it still produces "invalid session", and I am logged in online mode. I really don't know what happened...

[18:37:38 INFO]: [FastLogin] Handling player Cristiano_Rino
[18:37:38 INFO]: [FastLogin] Requesting premium login for registered player: Cristiano_Rino
[18:37:39 INFO]: [FastLogin] Enabling onlinemode encryption for UNKNOWN[/182.106.212.145:34199]
[18:37:49 INFO]: /182.106.212.145:34199 lost connection: Disconnected

> Check your DNS settings. Your server isn't able to find the Mojang servers. That would happen also without FastLogin with an onlinemode server.

**Comment by games647** [comment]
Are you authenticated with the Mojang client? Invalid session likely means an error on the client-side.

**Comment by From-pErfo** [comment]
I had a similar question! It's in Discord.

**Comment by CristianoRino** [comment]
> 您是否已通过 Mojang 客户端的身份验证？无效会话可能意味着客户端出现错误。

I'm very sorry. I still can't log in using PCL login and official login respectively. Now I suspect that DNS pollution exists in my area, so I can't connect to the mojang server...

**Comment by games647** [comment]
Could you both verify if the error also happens on onlinemode servers? According to the server log the client terminates the connection. This means we are either requesting invalid data or there are issues between the client and Mojang. Namely I assuming the following:

1. The `prevent-proxy` option that verifies the connection between Mojang and Minecraft client is the same as Minecraft client to server.
2. Mojang is blocking some client connections.

**Comment by From-pErfo** [comment]
This is the log of the player who had a problem: 
```
[19:24:18 INFO]: [FastLogin] Handling player Picasso_YSHG
[19:24:18 INFO]: [FastLogin] GameProfile Picasso_YSHG uses a premium username
[19:24:19 INFO]: [FastLogin] Enabling onlinemode encryption for UNKNOWN[/127.0.0.1:65142]
[19:24:20 ERROR]: [FastLogin] GameProfile {0} ({1}) tried to log in with an invalid session ServerId: {2}
[19:24:20 INFO]: /127.0.0.1:65142 lost connection: Disconnected
```

It's my own: 
```
[19:10:07 INFO]: Done (14.267s)! For help, type "help"
[19:10:07 INFO]: Timings Reset
[19:10:07 INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook
[19:10:26 INFO]: [FastLogin] Handling player From_pErfo
[19:10:27 INFO]: [FastLogin] GameProfile From_pErfo uses a premium username
[19:10:28 INFO]: [FastLogin] Enabling onlinemode encryption for UNKNOWN[/127.0.0.1:64932]
[19:10:28 INFO]: [FastLogin] Profile From_pErfo has a verified premium account
[19:10:28 INFO]: UUID of player From_pErfo is c5c3a31f-2e13-407c-9591-42401b02d14d
[19:10:28 INFO]: From_pErfo joined the game
[19:10:28 INFO]: From_pErfo[/127.0.0.1:64932] logged in with entity id 238 at ([world]-20.5, 91.0, -56.5)
[19:10:28 WARN]: [AuthMe] Could not save LimboPlayer for 'From_pErfo' [InaccessibleObjectException]: Unable to make private java.util.Collections$EmptyList() accessible: module java.base does not "opens java.util" to unnamed module @6991b171
[19:10:29 INFO]: [FastLogin] Register player From_pErfo
[19:10:29 INFO]: [AuthMe] From_pErfo registered 127.0.0.1
[19:10:29 INFO]: [AuthMe] From_pErfo logged in 127.0.0.1
[19:12:44 INFO]: From_pErfo lost connection: Disconnected
[19:12:44 INFO]: From_pErfo left the game
```

**Comment by From-pErfo** [comment]
@CristianoRino 
试试这个，如果我们遇到的是相同的问题，那它可以解决
https://github.com/From-pErfo/FastLogin/releases/tag/tcpshield_update

安装后还需修改一个配置 `useProxyAgnosticResolver: true`

**Comment by CristianoRino** [comment]
> @CristianoRino 试试这个，如果我们遇到的是相同的问题，那它可以解决 https://github.com/From-pErfo/FastLogin/releases/tag/tcpshield_update
> 
> 安装后还需修改一个配置 `useProxyAgnosticResolver: true`

感激不尽 救了大命了233 有效果了
我试了frp也试了云服务器都这毛病 就唯独本地啥事没有 换上这个就好了
我一开始觉得dns被污染了 后面调成一样的dns还是这个样
人都傻掉了

**Comment by CristianoRino** [comment]
> @CristianoRino 试试这个，如果我们遇到的是相同的问题，那它可以解决 https://github.com/From-pErfo/FastLogin/releases/tag/tcpshield_update
> 
> 安装后还需修改一个配置`useProxyAgnosticResolver: true`

不过我好像遇到了另一个问题，用frp的服务器的Fastlogin失效了而云服务器的恢复使用了

**Comment by From-pErfo** [comment]
> 不过我好像遇到了另一个问题，用frp的服务器的Fastlogin失效了而云服务器的恢复使用了

我始终使用frp和外网IP，它们正常工作。如果你愿意给我FastLogin和server.properties的配置，我会尝试重现一下这个问题 )

**Comment by games647** [comment]
Merging with #806
