### ISSUE TITLE
Error when loading fastlogin on bungee

### ISSUE THREAD

**Issue by ezVelar** [games647/FastLogin#829]
### What happened?

Hi, i have this problem when i trying to load fastlogin on my flamecord with java 8

### Server log

[17:20:57] [main/ERROR]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[17:20:57] [main/INFO] [fastlogin.hikari.HikariDataSource]: FastLogin - Starting...
[17:20:57] [main/WARN] [fastlogin.hikari.util.DriverDataSource]: Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[17:20:57] [main/INFO] [fastlogin.hikari.HikariDataSource]: FastLogin - Start completed.
[17:20:57] [main/WARN]: Exception encountered when loading plugin: FastLogin
java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property
	at com.github.games647.fastlogin.bungee.listener.ConnectListener.<init>(ConnectListener.java:96) ~[?:?]
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:104) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e48995:unknown]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e48995:unknown]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e48995:unknown]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e48995:unknown]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.LoginResult$Property
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e48995:unknown]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9e48995:unknown]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	... 6 more

### Plugin version

1.11-SNAPSHOT-812cf21

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version

**Comment by ezVelar** [comment]
This error is shown in spigot 1.8.8 with java 8 and the latest version of fastlogin, the same error is also given on flamecord java 8

### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 

**[00:56:28] [Server thread/ERROR]: Could not load 'plugins/FastLoginBukkit (4).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/games647/fastlogin/bukkit/FastLoginBukkit has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-741a1bd]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.UnsupportedClassVersionError: com/github/games647/fastlogin/bukkit/FastLoginBukkit has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_312]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_312]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_312]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_312]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_312]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_312]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Spigot-21fe707-741a1bd]
	... 6 more**

**Comment by games647** [comment]
This means you have an outdated Java version. FastLogin requires Java 17.

**Comment by ezVelar** [comment]
Yes ?, and how do I do with 1.8.8 that starts but fails to enter with java 17?
