### ISSUE TITLE
Backport to ASM 4 - Cauldron/Thermos

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#84]
FastLogin didn't started, because it requieres ASM 5 (which is not provided by my server software, and if I update it break 1.7.10-version plugins like Citizens), could you make a fix, or backport?

Here is the log: http://hastebin.com/qezikipiya.pas

Please help me, without FastLogin the players started losing their inventories D:

**Comment by games647** [comment]
It is provided by your server software...

Just the SpecialSource library used in Thermos still uses ASM4 specifications. It can be fixed by updating SpecialSource. 

https://github.com/CyberdyneCC/Thermos/issues/498

**Comment by games647** [comment]
Next time use better titles...

**Comment by Eufranio** [comment]
As i said, updating SpecialSource would break 1.7.10-designed plugins like Citizens (One of my servers is a RPG-based, remove NPCs would end the game :/) 
And sorry by the title, I'm really desperate

**Comment by games647** [comment]
But ASM5 is provided in Thermos.  Are you sure updating would break citizens. I don't think Citizens rely on it.

**Comment by games647** [comment]
And I think the author already updated it: https://github.com/CyberdyneCC/Thermos/commit/71531cf7038e1d03f8f4f6a15a96cbca57f45153

**Comment by Eufranio** [comment]
Yes, it broke, and broke Prism for Cauldron too... Thermos provide ASM4, a person updated it but it breaks plugins using the old one k

(And i personally think FastLogin is way more updated than Citizens :P)

**Comment by games647** [comment]
This is issue isn't really FastLogin related. It happens to all plugins which are developed with 1.8 Java.

**Comment by games647** [comment]
Could you send me the citizens error with the new version? I'm interested.

**Comment by Eufranio** [comment]
```
[17:50:38] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins/citizens.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/specialsource/JarMapping
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: net/md_5/specialsource/JarMapping
	at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:285) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:159) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.58]
	... 11 more
```

**Comment by games647** [comment]
Is that the full error?

**Comment by Eufranio** [comment]
Prism also gives a error with ASM5

```
[18:58:39 WARN]: org.apache.commons.lang.UnhandledException: Plugin Prism v2.0.3-Cauldron-MC1.7-SNAPSHOT-${env.BUILD_NUMBER} generated an exception while executing task 4380
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1433)
        at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:246)
        at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:36)
        at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:358)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```
Yes, these are the full errors, after this Citizens doesn't work, and Prism fail sometimes when inserting stuff in the database

**Comment by Eufranio** [comment]
Please, what's the build that uses ASM4? I need it kinda now...

**Comment by KaiKikuchi** [comment]
@Eufranio be sure to follow [this procedure](https://github.com/CyberdyneCC/Thermos/issues/498#issuecomment-247083549) exactly, especially renaming the special source jar name. I tried without renaming the file and I get the same NoClassDefFoundError.

AFAIK, the new SpecialSource is compatible with ASM4 too.

Also the prism error seems unrelated to SpecialSource and ASM. It looks like a MySQL database error. I guess the plugin is trying to use a null value for a database update. It should be around this: https://github.com/AgentME/Prism/blob/master/src/main/java/me/botsko/prism/actionlibs/RecordingTask.java#L208-L231

**Comment by Eufranio** [comment]
Thank you @KaiKikuchi , and I'm sorry for lose your time, @games647 , I didn't rename the jar and got that errors.
About Prism, it's really unrelated to ASM4, it happens always, but just today i activated Prism debug in the config... They aren't supporting bukkit anymore, and I don't have a dev to fix, I can only cry for now
