### ISSUE TITLE
"Invalid signature for profile public key" since latest update (Build 1099, 11/7)

### ISSUE THREAD

**Issue by MyWorldNetwork** [games647/FastLogin#843]
### What happened?

 [Mon 08:22:29 INFO  FastLogin] Handling player Sentinel618
  [Mon 08:22:29 INFO  FastLogin] Requesting premium login for registered player: Sentinel618
  [Mon 08:22:30 INFO  FastLogin] Enabling onlinemode encryption for UNKNOWN[/##.###.###.##:#####]
  [Mon 08:22:30 INFO  FastLogin] Profile Sentinel618 has a verified premium account
 
- [Mon 08:22:30 ERROR Minecraft/SignatureValidator] Failed to verify Services signature
java.security.SignatureException: Signature length not correct: got 128 but was expecting 512
    at java.base/sun.security.rsa.RSASignature.engineVerify(RSASignature.java:213)
    at java.base/java.security.Signature$Delegate.engineVerify(Signature.java:1435)
    at java.base/java.security.Signature.verify(Signature.java:789)
    at net.minecraft.util.SignatureValidator.verifySignature(SignatureValidator.java:26)
    at net.minecraft.util.SignatureValidator.lambda$from$3(SignatureValidator.java:47)
    at net.minecraft.util.SignatureValidator.validate(SignatureValidator.java:19)
    at net.minecraft.world.entity.player.ProfilePublicKey$Data.validateSignature(ProfilePublicKey.java:60)
    at net.minecraft.world.entity.player.ProfilePublicKey.createValidated(ProfilePublicKey.java:32)
    at net.minecraft.server.network.ServerLoginPacketListenerImpl.validatePublicKey(ServerLoginPacketListenerImpl.java:251)
    at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleHello(ServerLoginPacketListenerImpl.java:302)
    at net.minecraft.network.protocol.login.ServerboundHelloPacket.handle(ServerboundHelloPacket.java:23)
    at net.minecraft.network.protocol.login.ServerboundHelloPacket.name(ServerboundHelloPacket.java:10)
    at net.minecraft.network.Connection.genericsFtw(Connection.java:314)
    at net.minecraft.network.Connection.channelRead0(Connection.java:298)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$receiveClientPacket$1(NettyChannelInjector.java:311)
    at io.netty.util.concurrent.AbstractEv
  [Mon 08:22:30 INFO  Server/LoginListener] Disconnecting /##.###.###.##:#####: Invalid signature for profile public key.
Try restarting your game.
  [Mon 08:22:30 INFO  Server/LoginListener] /##.###.###.##:##### lost connection: Invalid signature for profile public key.
Try restarting your game.

### What did you expect?

To be able to automatically login using premium account, as I could on 1.18.2

### Plugin list

Command disabled but no suggestion that any other plugin is to blame

### Plugin version

1099

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post your startup log and what server software you use.

**Comment by MyWorldNetwork** [comment]
Struggling to get startup log but will post as soon as ftp client allows me to connect.
Server is running Purpur 1.19. Unsure which version as the server is set to retrieve the most recent release automatically.

**Comment by games647** [comment]
Found it anyway. We didn't forward the correct signature data.
