### ISSUE TITLE
Error on join with Geyser & Floodgate

### ISSUE THREAD

**Issue by ExtremorGP** [games647/FastLogin#854]
### What happened?

I get this error when I try to join.
`[FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
com.comphenix.protocol.reflect.FieldAccessException: No field with type com.mojang.authlib.GameProfile exists in class PacketLoginInStart.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib-577.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib-577.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ManualNameChange.onPacketReceiving(ManualNameChange.java:72) ~[FastLoginBukkit-1114.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:642) ~[ProtocolLib-577.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596) ~[ProtocolLib-577.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) ~[ProtocolLib-577.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) ~[ProtocolLib-577.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) ~[ProtocolLib-577.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-72]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-72]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### What did you expect?

Joining without any errors like on 1.18.2.

### Steps to reproduce

Run server with FastLogin, Geyser and Floodgate and join the server.

### Plugin list

AuthMe, FastLogin, floodgate, Geyser-Spigot, ProtocolLib

### Configuration file

https://www.toptal.com/developers/hastebin/xetuyegaha.yaml

### Server log

https://www.toptal.com/developers/hastebin/irimarokab.yaml

### Plugin version

1.12-SNAPSHOT-8df5b11

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post the plugin version, not the server version.

**Comment by ExtremorGP** [comment]
It's the latest build, #1114. Sorry, it's what I got after executing /version FastLogin.
