### ISSUE TITLE
Fastlogin doesn´t work

### ISSUE THREAD

**Issue by alandeluna** [games647/FastLogin#863]
### What happened?

When a premium player wants to join, appear this:

[19:29:37 WARN]: [FastLogin] Error occurred on thread pool
 java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.accessors.FieldAccessor com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessorOrNull(java.lang.Class, java.lang.String, java.lang.Class)'
 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-96]
 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.1.jar:git-Paper-96]
 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.1.jar:?]
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
 Caused by: java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.accessors.FieldAccessor com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessorOrNull(java.lang.Class, java.lang.String, java.lang.Class)'
 	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.getNetworkManager(VerifyResponseTask.java:207) ~[FastLoginBukkit.jar:?]
 	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:233) ~[FastLoginBukkit.jar:?]
 	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:131) ~[FastLoginBukkit.jar:?]
 	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:108) ~[FastLoginBukkit.jar:?]
 	at com.github.games647.fastlogin.core.AsyncScheduler.process(AsyncScheduler.java:70) ~[FastLoginBukkit.jar:?]
 	at com.github.games647.fastlogin.core.AsyncScheduler.lambda$runAsync$0(AsyncScheduler.java:61) ~[FastLoginBukkit.jar:?]
 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
 	... 6 more

### Plugin list

AdvancedPortals, AuthMe, BetterTeams, CrossplatForms, DeathMessages, DecentHolograms, Essentials, FastLogin, floodgate, Geyser-Spigot, GeyserHub, GriefPrevention, GriefPreventionFlags, GSit, HoloMobHealth, LPC, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Oneblock, PlaceholderAPI, PlayerEmotesPro, ProtocolLib, SimpleTpa*, SkinsRestorer, Skoice, StaffPlus, TAB, UltraBar, ViaBackwards, ViaVersion, WorldEdit

### Plugin version

FastLogin version 1.12-SNAPSHOT-ed45fad

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by alandeluna** [comment]
I updated protocolib, problem solved
