### ISSUE TITLE
Property date_string_format does not exist on target class org.sqlite.SQLiteDataSource

### ISSUE THREAD

**Issue by jbmagination** [games647/FastLogin#870]
### What happened?

Starting with [build 1132](https://ci.codemc.io/job/Games647/job/FastLogin/1132/), attempting to start a server with FastLogin crashes:
```
[06:27:58 ERROR]: [fastlogin.hikari.util.PropertyElf] Property date_string_format does not exist on target class org.sqlite.SQLiteDataSource
[06:27:58 ERROR]: Error occurred while enabling FastLogin v1.12-SNAPSHOT-6beaf19 (Is it up to date?)
java.lang.RuntimeException: Property date_string_format does not exist on target class org.sqlite.SQLiteDataSource
	at fastlogin.hikari.util.PropertyElf.setProperty(PropertyElf.java:135) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59) ~[FastLoginBukkit.jar:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at java.util.Properties.forEach(Properties.java:1422) ~[?:?]
	at fastlogin.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:328) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[FastLoginBukkit.jar:?]
	at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:80) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.storage.SQLiteStorage.<init>(SQLiteStorage.java:46) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:239) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:112) ~[FastLoginBukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-97]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-97]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:27:58 INFO]: [FastLogin] Disabling FastLogin v1.12-SNAPSHOT-6beaf19
[06:27:58 INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
```
Builds [1131](https://ci.codemc.io/job/Games647/job/FastLogin/1131/) and below work as expected.

### What did you expect?

* The plugin starts and functions

### Steps to reproduce

* Start a server with FastLogin build 1132 or higher
* The plugin will crash

### Plugin version

1.12-SNAPSHOT-6beaf19

### Platform

Spigot (more accurately - Paper `git-Paper-97`)

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Thanks, you can use 1131 for now. There are not many changes. I'll need to check how to set the properties correctly, because this value clearly exists:

https://github.com/xerial/sqlite-jdbc/blob/14d59032fb5dc691e48877ecde783719b7657fba/src/main/java/org/sqlite/SQLiteConfig.java#L322

**Comment by Smart123s** [comment]
Now I get this:

```
[18:23:18 INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-091b558
[18:23:18 WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.
[18:23:18 INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Starting...
[18:23:18 ERROR]: [fastlogin.hikari.util.PropertyElf] Failed to set property config on target class org.sqlite.SQLiteDataSource
java.lang.IllegalArgumentException: argument type mismatch
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at fastlogin.hikari.util.PropertyElf.setProperty(PropertyElf.java:162) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59) ~[FastLoginBukkit.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at java.util.Properties.forEach(Properties.java:1461) ~[?:?]
        at fastlogin.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:328) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:80) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.core.storage.SQLiteStorage.<init>(SQLiteStorage.java:48) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:239) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:112) ~[FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-61]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:23:18 ERROR]: Error occurred while enabling FastLogin v1.12-SNAPSHOT-091b558 (Is it up to date?)
java.lang.RuntimeException: java.lang.IllegalArgumentException: argument type mismatch
        at fastlogin.hikari.util.PropertyElf.setProperty(PropertyElf.java:168) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59) ~[FastLoginBukkit.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at java.util.Properties.forEach(Properties.java:1461) ~[?:?]
        at fastlogin.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:328) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[FastLoginBukkit.jar:?]
        at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:80) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.core.storage.SQLiteStorage.<init>(SQLiteStorage.java:48) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:239) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:112) ~[FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-61]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at fastlogin.hikari.util.PropertyElf.setProperty(PropertyElf.java:162) ~[FastLoginBukkit.jar:?]
        ... 23 more
[18:23:18 INFO]: [FastLogin] Disabling FastLogin v1.12-SNAPSHOT-091b558
[18:23:19 INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
```

I don't think that it matters, but It's a local build, so it's not downloaded from the CI. Commit 091b558, no modifications.

**Comment by Smart123s** [comment]
It's working now.
