### ISSUE TITLE
NoSuchMethodError: AuthType with Geyser feature extension

### ISSUE THREAD

**Issue by apatuka** [games647/FastLogin#871]
### What happened?

 Exception encountered when loading plugin: FastLogin
java.lang.NoSuchMethodError: 'org.geysermc.geyser.session.auth.AuthType org.geysermc.geyser.configuration.GeyserConfiguration$IRemoteConfiguration.getAuthType()'
        at com.github.games647.fastlogin.core.hooks.bedrock.GeyserService.<init>(GeyserService.java:47) ~[?:?]
        at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:98) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:1590d2b:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:1590d2b:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:1590d2b:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:1590d2b:unknown]

### What did you expect?

/premium must work

### Steps to reproduce

Install lastest geyser, floodgate and fastlogin plugin on Proxy.

### Server log

java.lang.NoSuchMethodError: 'org.geysermc.geyser.session.auth.AuthType org.geysermc.geyser.configuration.GeyserConfiguration$IRemoteConfiguration.getAuthType()'
        at com.github.games647.fastlogin.core.hooks.bedrock.GeyserService.<init>(GeyserService.java:47) ~[?:?]
        at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:98) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:1590d2b:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:1590d2b:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:1590d2b:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:1590d2b:unknown]

### Plugin version

lastest release

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment]
Could you please provide the exact version of Geyser and FastLogin you are using? Have you tried updating Geyser? The AuthType class was moved to another package in https://github.com/GeyserMC/Geyser/commit/2c663e0ee5824e88c571ec679e68d1eab59a72ec.

**Comment by apatuka** [comment]
Hello thanks for the reply, 

I'm using this branch:

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/feature%252Fextensions/

It's updated to the lastest version, for now i ended compiling the fastlogin jar without Geyser and floodgate hooks.

**Comment by Smart123s** [comment]
The class was indeed moved in the [feature/extensions](https://github.com/GeyserMC/Geyser/tree/feature/extensions) branch.

Old: [org.geysermc.geyser.session.auth.AuthType](https://github.com/GeyserMC/Geyser/blob/f74713c0edca0f94eb90c26c7dfd177ff8623381/core/src/main/java/org/geysermc/geyser/session/auth/AuthType.java)
New: [org.geysermc.geyser.api.network.AuthType](https://github.com/GeyserMC/Geyser/blob/67e3bf1f8dd864fa68c0cd672212145e03a030ba/api/geyser/src/main/java/org/geysermc/geyser/api/network/AuthType.java)

**Comment by YellowZaki** [comment]
The Geyser extension branch has just been merged into master.

**Comment by Smart123s** [comment]
It was, but they didn't publish it on their maven repo yet: https://repo.opencollab.dev/ui/builds/GeyserMC%20::%20Geyser%20::%20master/1189/1663606651595/published

**Comment by Smart123s** [comment]
Artifacts have been pushed (https://github.com/GeyserMC/Geyser/commit/8beae31cee80e94e773c37c15a2956034f1d3e69), I'll open a PR this afternoon.

**Comment by MartijnMuijsers** [comment]
(Geyser build 1188 still works in the meantime)
