### ISSUE TITLE
java.lang.NoSuchMethodError: org.sqlite.SQLiteConfig.setDateStringFormat(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by adayy12** [games647/FastLogin#877]
### What happened?

[17:37:55] [Server thread/INFO]: [FastLogin] Loading FastLogin v1.12-SNAPSHOT-ed9e295
[17:38:34] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-ed9e295
[17:38:34] [Server thread/WARN]: [FastLogin] Cannot check for Velocity support in Paper: com.destroystokyo.paper.PaperConfig
[17:38:34] [Server thread/WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.
[17:38:34] [Server thread/ERROR]: Error occurred while enabling FastLogin v1.12-SNAPSHOT-ed9e295 (Is it up to date?)
java.lang.NoSuchMethodError: org.sqlite.SQLiteConfig.setDateStringFormat(Ljava/lang/String;)V
	at com.github.games647.fastlogin.core.storage.SQLiteStorage.setParams(SQLiteStorage.java:64) ~[?:?]
	at com.github.games647.fastlogin.core.storage.SQLiteStorage.<init>(SQLiteStorage.java:49) ~[?:?]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:234) ~[?:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:111) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[17:38:34] [Server thread/INFO]: [FastLogin] Disabling FastLogin v1.12-SNAPSHOT-ed9e295
[17:38:34] [Server thread/INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.

### Steps to reproduce

Im using paper-1.8.8.jar and Java 8

i dont know what happen plz help me, if i put older version plugin can load but cant verify my premium account..

i download your 1h last build :C 

### Plugin version

FastLogin version 1.12-SNAPSHOT-ed9e295

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by adayy12** [comment]
i miss say im using this auth plugin (lastest version): https://www.spigotmc.org/resources/authmereloaded.6269/
