### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchFieldException: playerInjectionHandler

### ISSUE THREAD

**Issue by adayy12** [games647/FastLogin#878]
### What happened?

[18:27:50] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-6fe7eb2
[18:27:50] [Server thread/WARN]: [FastLogin] Cannot check for Velocity support in Paper: com.destroystokyo.paper.PaperConfig
[18:27:50] [Server thread/WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.
[18:27:50] [Server thread/INFO]: FastLogin - Starting...
[18:27:50] [Server thread/INFO]: FastLogin - Driver does not support get/set network timeout for connections. (org.sqlite.Conn.getNetworkTimeout()I)
[18:27:50] [Server thread/INFO]: FastLogin - Start completed.
[18:27:50] [Server thread/ERROR]: Error occurred while enabling FastLogin v1.12-SNAPSHOT-6fe7eb2 (Is it up to date?)
java.lang.RuntimeException: java.lang.NoSuchFieldException: playerInjectionHandler
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.getHandler(ProtocolLibListener.java:280) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.<init>(ProtocolLibListener.java:96) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.register(ProtocolLibListener.java:103) ~[?:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchFieldException: playerInjectionHandler
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_212]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.getHandler(ProtocolLibListener.java:274) ~[?:?]

### Plugin version

last build

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Use build `#1131` until this fixed. This related to the recently merged changes.

**Comment by Smart123s** [comment]
Does it also break if Floodgate is not installed?

**Comment by adayy12** [comment]
new problem

**Comment by games647** [comment]
Closing in favor of #881
