### ISSUE TITLE
java.lang.ClassNotFoundException: sqlite

### ISSUE THREAD

**Issue by adayy12** [games647/FastLogin#879]
### What happened?

bug :C , thanks for support me, you are a good person jeje

### What did you expect?

im sorry for al problems im having i put the version you say me ..
but have new bug and i dont use geyser.

[12:55:46] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-62d7320
[12:55:47] [Server thread/WARN]: [FastLogin] Cannot check for Velocity support in Paper: com.destroystokyo.paper.PaperConfig
[12:55:47] [Server thread/WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.
[12:55:47] [Server thread/WARN]: [FastLogin] This driver sqlite is not supported on this platform
[12:55:47] [Server thread/WARN]: [FastLogin] Please choose either MySQL (Spigot, BungeeCord), SQLite (Spigot, Sponge) or MariaDB (Sponge, Velocity)
java.lang.ClassNotFoundException: sqlite
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_212]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.checkDriver(FastLoginCore.java:273) [FastLoginBukkit%20(8).jar:?]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:228) [FastLoginBukkit%20(8).jar:?]
	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:112) [FastLoginBukkit%20(8).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[12:55:47] [Server thread/INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.

### Plugin version

build #1131

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
You need the old driver version in the configuration file. This isn't need if you had the old config file.

https://github.com/games647/FastLogin/blob/6beaf194ce93ef0ae21f7e71286717f15ab54c18/core/src/main/resources/config.yml#L288

**Comment by adayy12** [comment]
yes you repair my mistake thank you so much

**Comment by games647** [comment]
You can fix it yourself. Just change that value in the config file.
