### ISSUE TITLE
jeje new problem

### ISSUE THREAD

**Issue by adayy12** [games647/FastLogin#880]
### What happened?

when in put /premium is on the plugin and register me on premium, but if i leave and enter say me put my password on authme, and if i enter on a cracked launcher i can enter and say me put the passwd..

### What did you expect?

[INFO] [FastLogin] No on-going login session for player: CraftPlayer{name=AdayES} with ID 

[INFO] [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received

[INFO] (▸) AdayES salió de nuestro servidor!

[INFO] [FastLogin] New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@1884a6dc

[ERROR] [FastLogin] Unhandled exception occured in onAsyncPacket() for FastLogin

java.lang.NoSuchMethodError: com.comphenix.protocol.wrappers.BukkitConverters.getWrappedPublicKeyDataConverter()Lcom/comphenix/protocol/reflect/EquivalentConverter;

at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onLoginStart(ProtocolLibListener.java:210) ~[FastLoginBukkit%20(8).jar:?]

at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:129) ~[FastLoginBukkit%20(8).jar:?]

at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:642) [ProtocolLib.jar:4.8.0]

at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596) [ProtocolLib.jar:4.8.0]

at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) [ProtocolLib.jar:4.8.0]

at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) [ProtocolLib.jar:4.8.0]

at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) [ProtocolLib.jar:4.8.0]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-PaperSpigot-"4c7641d19"]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-PaperSpigot-"4c7641d19"]

at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23) [patched.jar:git-PaperSpigot-"4c7641d19"]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

[INFO] UUID of player AdayES is 08ff3acf-d6f7-33bd-9070-cd5c146e2ee5

[INFO] AdayES[/] logged in with entity id 579 at ([Warps]-15.774245766966338, 82.0, -44.303868526430854)

[INFO] (▸) AdayES se unió al servidor!

[INFO] [FastLogin] No on-going login session for player: CraftPlayer{name=AdayES} with ID 

[INFO] [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received

### Configuration file

https://gist.github.com/adayy12/c00b0aab1b4662724341586ee22c233b

### Plugin version

build #1131

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Yeah, this is all related, because your Minecraft version is so old. The changes in `1091` should be fine, because that's the first we dumped the ProtocolLib dependency. Remember to reset the database, because it could saved the broken login as cracked.

**Comment by games647** [comment]
Closing this in favor of a combined ticket

**Comment by adayy12** [comment]
[14:03:13] [Server thread/ERROR]: Could not load 'plugins/FastLoginBukkit (10).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/games647/fastlogin/bukkit/FastLoginBukkit has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.UnsupportedClassVersionError: com/github/games647/fastlogin/bukkit/FastLoginBukkit has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_212]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_212]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_212]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	... 6 more

**Comment by adayy12** [comment]
i put your build #1091
