### ISSUE TITLE
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary when disabling

### ISSUE THREAD

**Issue by NathanFAIN** [games647/FastLogin#885]
### What happened?

When the server stops, the FastLogin plugin is disabled with an error.
It seems that ProtocolLib is disabled before FastLogin.

### What did you expect?

Disable Fastlogin without error

### Steps to reproduce

Start your server with :
![image](https://user-images.githubusercontent.com/47045209/184448718-429e6638-d9a1-4a9a-8a9f-42c616d8eba0.png)
![image](https://user-images.githubusercontent.com/47045209/184448748-def3a2e5-fd9e-46d6-bf5d-22021c6e89ab.png)
![image](https://user-images.githubusercontent.com/47045209/184448785-7cbb4358-1964-4cdb-a7b4-7df3bef3451d.png)

And stop your server.

### Plugin list

FastLogin 1.12-SNAPSHOT-feb4639, ProtocolLib 4.8.0, AuthMe 5.6.0-SNAPSHOT-b2568

### Server log

[23:28:54] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.8.0
[23:28:54] [Server thread/WARN]: [AuthMe] ProtocolLib has been disabled, unhooking packet adapters!
[23:28:54] [Server thread/INFO]: [PluginQuery] Disabling PluginQuery v1.0.36
[23:28:54] [Server thread/INFO]: [LPX] Disabling LPX v3.1.3
[23:28:54] [Server thread/INFO]: [AuthMe] Disabling AuthMe v5.6.0-SNAPSHOT-b2568
[23:28:54] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[23:28:54] [Server thread/ERROR]: [AuthMe] [STDERR] [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Shutdown initiated...
[23:28:54] [Server thread/WARN]: Nag author(s): '[sgdc3, ljacqu, games647, Hex3l, krusic22]' of 'AuthMe' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[23:28:54] [Server thread/ERROR]: [AuthMe] [STDERR] [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Shutdown completed.
[23:28:54] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-SNAPSHOT-b2568 disabled!
[23:28:54] [Server thread/INFO]: [TAB] Disabling TAB v3.1.0
[23:28:54] [Server thread/INFO]: [TAB] Disabled in 1ms
[23:28:54] [Server thread/INFO]: [spark] Disabling spark v1.9.25
[23:28:54] [Server thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.11.2
[23:28:54] [Server thread/INFO]: [DecentHolograms] Disabling DecentHolograms v2.5.3
[23:28:54] [Server thread/INFO]: [FastLogin] Disabling FastLogin v1.12-SNAPSHOT-feb4639
[23:28:54] [Server thread/INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
[23:28:54] [Server thread/ERROR]: Error occurred while disabling FastLogin v1.12-SNAPSHOT-feb4639 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onDisable(FastLoginBukkit.java:191) ~[FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[minecraft_server.jar:git-Cat-"890d379"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[minecraft_server.jar:git-Cat-"890d379"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[minecraft_server.jar:git-Cat-"890d379"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514) ~[minecraft_server.jar:git-Cat-"890d379"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:484) ~[minecraft_server.jar:git-Cat-"890d379"]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1053) ~[minecraft_server.jar:git-Cat-"890d379"]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:817) ~[minecraft_server.jar:git-Cat-"890d379"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1332) ~[minecraft_server.jar:git-Cat-"890d379"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[minecraft_server.jar:git-Cat-"890d379"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[minecraft_server.jar:git-Cat-"890d379"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[minecraft_server.jar:git-Cat-"890d379"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more

### Plugin version

1.12-SNAPSHOT-feb4639

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by NathanFAIN** [comment]
@games647 do you have any idea where the problem comes from?
