### ISSUE TITLE
FastLogin Build #1091 crashing when using ProtocolLib v5.0.0-SNAPSHOT-b600

### ISSUE THREAD

**Issue by alejaandroperez** [games647/FastLogin#904]
### What happened?

Users using /premium are stucked when rejoining the game in the encryptation step. Minecraft version 1.18

### What did you expect?

Player autologin

### Steps to reproduce

User /premium and then rejoin the game

### Plugin list

Authme, Protocolib, FastLogin

### Configuration file

https://hastebin.com/amuguwagap.yaml

### Server log

[10:53:29] [Protocol Worker #1 - FastLogin - [recv: ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], send: ]/INFO]: [FastLogin] New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@47b1594f
[10:53:29] [Craft Scheduler Thread - 3/INFO]: [FastLogin] Handling player imAlejandro04
[10:53:29] [Craft Scheduler Thread - 3/INFO]: [FastLogin] Requesting premium login for registered player: imAlejandro04
[10:53:29] [Protocol Worker #1 - FastLogin - [recv: ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], send: ]/INFO]: [FastLogin] New packet ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@47b1594f
[10:53:30] [Craft Scheduler Thread - 3/INFO]: [FastLogin] Enabling onlinemode encryption for /the-ip-of-the-player
[10:53:30] [Craft Scheduler Thread - 3/INFO]: [FastLogin] Profile imAlejandro04 has a verified premium account
[10:53:30] [Craft Scheduler Thread - 3/WARN]: [FastLogin] Error occurred on thread pool
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unable to construct new instance using public net.minecraft.network.protocol.login.PacketLoginInStart(net.minecraft.network.PacketDataSerializer)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) [spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Unable to construct new instance using public net.minecraft.network.protocol.login.PacketLoginInStart(net.minecraft.network.PacketDataSerializer)
	at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:21) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$0(StructureCache.java:73) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:85) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:95) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.receiveFakeStartPacket(VerifyResponseTask.java:273) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.encryptConnection(VerifyResponseTask.java:180) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:148) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:108) ~[?:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.process(AsyncScheduler.java:70) ~[?:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.lambda$runAsync$0(AsyncScheduler.java:61) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 5 more
Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.2.38.jar:?]
	at net.minecraft.network.protocol.login.PacketLoginInStart.<init>(SourceFile:16) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:19) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$0(StructureCache.java:73) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:85) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:95) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.receiveFakeStartPacket(VerifyResponseTask.java:273) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.encryptConnection(VerifyResponseTask.java:180) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:148) ~[?:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:108) ~[?:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.process(AsyncScheduler.java:70) ~[?:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.lambda$runAsync$0(AsyncScheduler.java:61) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 5 more

### Plugin version

Build #1091

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
ProtocolLib 5.0 is not compatible below Minecraft 1.19

**Comment by alejaandroperez** [comment]
> ProtocolLib 5.0 is not compatible below Minecraft 1.19

I also tried using v4.8.0 but the plugin responds with: "[FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received" and it doesn't autologin players. Sorry if it's a dumb question but how can I fix it?

**Comment by games647** [comment]
Please add that log entry. It means it found no session for that player. So it missed the login process. If you use BungeeCord or Velocity, you should follow the setup guide referenced on the main page.

**Comment by alejaandroperez** [comment]
[Server] Server thread/INFO [FastLogin] No on-going login session for player: CraftPlayer{name=imAlejandro04} with ID 
[Server] Server thread/INFO [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received

I'm just using Spigot. Not Velocity or BungeeCord

**Comment by alejaandroperez** [comment]
24.08 12:50:34 [Server] INFO [12:50:34] [Protocol Worker #1 - FastLogin - [recv: ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], send: ]/INFO]: [FastLogin] New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@72df496
24.08 12:50:34 [Server] INFO [12:50:34] [Protocol Worker #1 - FastLogin - [recv: ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], send: ]/ERROR]: [FastLogin] Unhandled exception occured in onAsyncPacket() for FastLogin
24.08 12:50:34 [Server] INFO java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.EquivalentConverter com.comphenix.protocol.wrappers.BukkitConverters.getWrappedPublicKeyDataConverter()'
24.08 12:50:34 [Server] INFO at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onLoginStart(ProtocolLibListener.java:225) ~[FastLoginBukkit.jar:?]
24.08 12:50:34 [Server] INFO at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:149) ~[FastLoginBukkit.jar:?]
24.08 12:50:34 [Server] INFO at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:642) [ProtocolLib.jar:4.8.0]
24.08 12:50:34 [Server] INFO at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596) [ProtocolLib.jar:4.8.0]
24.08 12:50:34 [Server] INFO at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) [ProtocolLib.jar:4.8.0]
24.08 12:50:34 [Server] INFO at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) [ProtocolLib.jar:4.8.0]
24.08 12:50:34 [Server] INFO at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) [ProtocolLib.jar:4.8.0]
24.08 12:50:34 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) [spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
24.08 12:50:34 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
24.08 12:50:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
24.08 12:50:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
24.08 12:50:34 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
24.08 12:50:34 [Server] User Authenticator #5/INFO UUID of player imAlejandro04 is 4503066e-1d03-39b3-82cf-946388b84e39

**Comment by games647** [comment]
Now you are using a different FastLogin version. Please keep using 1091 for 1.18.
