### ISSUE TITLE
problem with velocity

### ISSUE THREAD

**Issue by Brutalalex** [games647/FastLogin#912]
hi, i have problem with velocity fastlogin.
it dont load.
This will happen:
13:27:01[ERROR] Couldn't pass ProxyInitializeEvent to fastlogin
java.lang.NoClassDefFoundError: org/sqlite/SQLiteConfig
at com.github.games647.fastlogin.core.storage.SQLiteStorage.setParams(SQLiteStorage.java:64) ~[?:?]
at com.github.games647.fastlogin.core.storage.SQLiteStorage.<init>(SQLiteStorage.java:49) ~[?:?]
at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:234) ~[?:?]
at com.github.games647.fastlogin.velocity.FastLoginVelocity.onProxyInitialization(FastLoginVelocity.java:96) ~[?:?]
at com.github.games647.fastlogin.velocity.Lmbda$7.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: org.sqlite.SQLiteConfig
at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:84) ~[server.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:61) ~[server.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
... 11 more

thx for help.

**Comment by games647** [comment]
Please use bug report template and fill out all the necessary details.
