### ISSUE TITLE
FastLogin won't start with latest version of Geyser

### ISSUE THREAD

**Issue by deiphiz** [games647/FastLogin#922]
### What happened?

Running FastLogin build #1159 and any GeyserMC Spigot build above #1189 causes FastLogin to run into a `NoSuchMethodError` error and the plugin will refuse to start. With GeyserMC disabled, FastLogin will still start as normal.

This error in particular seems to be caused by Geyser renaming their `session.auth.AuthType` class into `api.network.AuthType`. The change looks to be in part of their big API changes indicated here: https://github.com/GeyserMC/Geyser/pull/3267.

For reference, this is the Jenkins link for the Geyser build that started the issue: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1189/

### What did you expect?

The plugin should start smoothly along with GeyserMC upon server startup

### Steps to reproduce

Start server with FastLogin, ProtocolLib, and any GeyserMC build above #1189

### Plugin list

AuthMe, FastLogin, floodgate, Geyser-Spigot, ProtocolLib

### Configuration file

https://gist.github.com/deiphiz/7318f24a14c369333804a6a153daa88e

### Server log

```
[21:43:36 ERROR]: Error occurred while enabling FastLogin v1.12-SNAPSHOT-7425df8 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.geysermc.geyser.session.auth.AuthType org.geysermc.geyser.configuration.GeyserConfiguration$IRemoteConfiguration.getAuthType()'
        at com.github.games647.fastlogin.core.hooks.bedrock.GeyserService.<init>(GeyserService.java:47) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.initializeFloodgate(FastLoginBukkit.java:155) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:101) ~[FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1774]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:43:36 INFO]: [FastLogin] Disabling FastLogin v1.12-SNAPSHOT-7425df8
[21:43:36 INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
```

### Plugin version

1.12-SNAPSHOT-7425df8

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment]
Duplicate of https://github.com/games647/FastLogin/issues/871

**Comment by TheDiego845** [comment]
![image](https://user-images.githubusercontent.com/69425536/192339359-b927c812-74a0-44a5-bd03-6f77acd8eaaa.png)

**Comment by Smart123s** [comment]
> ![image](https://user-images.githubusercontent.com/69425536/192339359-b927c812-74a0-44a5-bd03-6f77acd8eaaa.png)

Did you update Geyser?

**Comment by TheDiego845** [comment]
Yes now https://media.discordapp.net/attachments/1024006804352553080/1024009138365280316/unknown.png

**Comment by Smart123s** [comment]
Which ProtocolLib version do you have? Seems like it's 4.x And what MC version are you on? Also https://github.com/games647/FastLogin/issues/881 might be useful.

**Comment by TheDiego845** [comment]
1.17.1 Paper and 4.8.0

**Comment by TheDiego845** [comment]
![image](https://user-images.githubusercontent.com/69425536/192346236-e8fae190-4897-4c20-8cac-0c75718533dd.png)

**Comment by TheDiego845** [comment]
Same problem with build 1079

**Comment by Smart123s** [comment]
> Same problem with build 1079

FastLogin build 1079 is only compatible with [Geyser build 1188](https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1188/) (and older), ProtocolLib 4.8.0 and MC version 1.18.2 or older.

**Comment by TheDiego845** [comment]
So no more than 1.19.30 people will be able to enter my bedrock server?

**Comment by infinite1945** [comment]
![unknown](https://user-images.githubusercontent.com/114440531/192366836-d5fc9200-89ee-4bc4-b73d-071d99b773b7.png)

**Comment by Smart123s** [comment]
I've backported the changes from https://github.com/games647/FastLogin/pull/923 on top of 41890679ed9c4d78664608ee5e115efb97d25371 (build 1079).

Could you try the result? [FastLoginBukkit-31bc57c.zip](https://github.com/games647/FastLogin/files/9649284/FastLoginBukkit-31bc57c.zip) (source: https://github.com/Smart123s/FastLogin/commit/31bc57c8f2f217b1ec3a156c616614ff6eeb6b87)

**Comment by TheDiego845** [comment]
Ok i am going to test it

**Comment by TheDiego845** [comment]
WORKS PERFECT. THANKS YOU

**Comment by infinite1945** [comment]
It's working now , thanks for your help @Smart123s  i hope you the best ; )

**Comment by spartamc** [comment]
@Smart123s Im using Minecraft 1.19 and don't work, any solution? Im using ProtocolLib version 4.8.0 and Last of Geyser

**Comment by Smart123s** [comment]
@spartamc for MC 1.19 you need to use ProtocolLib 5.0.

**Comment by spartamc** [comment]
@Smart123s If I have now noticed that when using version 4.8.0 it only gives errors, I am with version 5.0 but it does not work either. And I have downloaded the zip that you have passed your

**Comment by Smart123s** [comment]
@spartamc the zip is for ProtocolLib 4.8 which is needed for MC version 1.18 or earlier. With MC 1.19 you can use ProtocolLib 5.0 with latest FastLogin and latest Geyser.

**Comment by spartamc** [comment]
@Smart123s I've tried but it hasn't worked for me. FastLogin's latest version is #1163 isn't it?

**Comment by Smart123s** [comment]
Yes it is. If could you double check if you have the appropriate versions of Geyser, ProtocolLib and FastLogin? If it still doesn't work, please open a new issue with server logs.

**Comment by spartamc** [comment]
@Smart123s im using:
ProtocolLib version 5.0.0
FastLogin #1163
And Geyser 
![image](https://user-images.githubusercontent.com/94750050/193464199-4ec0637a-63a8-4ddc-9fb1-387205f6fc3c.png)

**Comment by Smart123s** [comment]
@spartamc could you post server logs?

**Comment by spartamc** [comment]
@Smart123s I don't understand why it works now, I think it was because I used the zip for the FastLogin and I wasn't using the latest version when I was doing tests. Sorry for wasting your time and thank you very much.

**Comment by Smart123s** [comment]
@spartamc it's ok, glad you figured it out 🎉

**Comment by spartamc** [comment]
@Smart123s I have another question that is not related to this but it is normal that sometimes the plugin changes the UUID to some players?

**Comment by Smart123s** [comment]
@spartamc you can check premiumuuid in config.yml. also, does it happen for Java or Bedrock players?

**Comment by spartamc** [comment]
@Smart123s  That option I have disabled, it has only happened to me with java accounts, that of a friend and mine for now. I didn't take much thought out until I realized that when the UUID changes it loses the money.

**Comment by jondycz** [comment]
Same issue 1.19.3, latest geyser, fast login, protocollib

**Comment by Smart123s** [comment]
Couldn't reproduce the issue. Tested on

Client:
- Bedrock 1.19.51 (Windows 11)
- Java 1.19.3

Server
- https://github.com/PaperMC/Paper/commit/048ee5872d791df0a9aad856723958c8dc602e48
- https://github.com/GeyserMC/Geyser/commit/03390b99e8240dc96a12414a016812b5e34de4dd
- [games647/FastLogin@](https://github.com/games647/FastLogin/commit/cb5598f2f46923b887faf1b39263254d2c42a015)https://github.com/games647/FastLogin/commit/cb5598f2f46923b887faf1b39263254d2c42a015
- https://github.com/GeyserMC/Floodgate/commit/4f361120d1d6dfe878f725ee3e91505583e5b94e
- https://github.com/dmulloy2/ProtocolLib/commit/9d183e85d7cb6c076fcd9bc39192a3f2df7145ad
