### ISSUE TITLE
Channel must contain : separator

### ISSUE THREAD

**Issue by lynrayy** [games647/FastLogin#945]
### What happened?

Not working on spigot subserver
```
[18:13:54 INFO]: [FastLogin] Enabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432*
[18:13:54 ERROR]: Error occurred while enabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use FastLogin)
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:216) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:72) ~[FastLogin (1).jar:?]        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-290]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-290]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:13:54 INFO]: [FastLogin] Disabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432
```

### Plugin list

AuthMe-5.6.0-SNAPSHOT, latest ProtocolLib

### Configuration file

https://gist.github.com/lynrayy/d3e07657a2971c6a5fd3edf444988274

### Server log

https://gist.github.com/lynrayy/08e6e734059eb6c76be7e4a1679e9650

### Plugin version

[18:18:47 INFO]: FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432 [18:18:47 INFO]: Automatically logins premium (paid accounts) player on a offline mode server  [18:18:47 INFO]: Website: https://www.spigotmc.org/resources/fastlogin.14153/fastlogin.bukkit/ [18:18:47 INFO]: Authors: games647 and https://github.com/games647/FastLogin/graphs/contributors

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version
