### ISSUE TITLE
Spigot 1.11

### ISSUE THREAD

**Issue by cwchristerw** [games647/FastLogin#95]
Hi!

I just updated to Spigot 1.11.

HERE IS SOMETHING IF YOU EVER ADD SUPPORT FOR SPIGOT 1.11
When I login to server I get this error on console and it doesn't logmein automaticly but it's not big problem but also it doesn't show premium skins.

[02:57:42 ERROR]: [FastLogin] Failed to query profile
java.sql.SQLException: Error parsing time stamp
        at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:5 ~[spigot-1.11.jar:git-Spigot-f950f8e-2b7808f]
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProesultSet.java) ~[FastLogin.jar:?]
        at com.github.games647.fastlogin.core.AuthStorage.loadProfile(AuthStoe.java:129) [FastLogin.jar:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JManagement.java:21) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameChecsk.run(NameCheckTask.java:38) [FastLogin.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.a:71) [spigot-1.11.jar:git-Spigot-f950f8e-2b7808f]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftncTask.java:52) [spigot-1.11.jar:git-Spigot-f950f8e-2b7808f]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutjava:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecu.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.text.ParseException: Unparseable date: "2016-11-27 00:20:21" s not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{N+)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
        at org.sqlite.date.FastDateParser.parse(FastDateParser.java:299) ~[spt-1.11.jar:git-Spigot-f950f8e-2b7808f]
        at org.sqlite.date.FastDateFormat.parse(FastDateFormat.java:490) ~[spt-1.11.jar:git-Spigot-f950f8e-2b7808f]
        at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:5 ~[spigot-1.11.jar:git-Spigot-f950f8e-2b7808f]
        ... 9 more

Plugin version: 1.9

**Comment by games647** [comment]
Update to a dev-build. It's a bug in a newer version of SQLite http://ci.xephi.fr/job/FastLogin/

**Comment by RoboMWM** [comment]
How did you fix this/what commit? I'm having an issue with an older plugin also experiencing this.
