### ISSUE TITLE
[1.19.3] Error on player join, auto login not working

### ISSUE THREAD

**Issue by zapteryx** [games647/FastLogin#951]
### What happened?

Auto login does not work, and there's an error in the console whenever a player joins:
```
[18:14:00 ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
java.lang.IllegalArgumentException: handle (13ed2ba8-e5e0-474b-a3e9-78b26227447b) is not a class net.minecraft.world.entity.player.ProfilePublicKey$a, but class java.util.UUID
        at com.comphenix.protocol.wrappers.AbstractWrapper.setHandle(AbstractWrapper.java:31) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedProfilePublicKey$WrappedProfileKeyData.<init>(WrappedProfilePublicKey.java:118) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.Converters$3.getSpecific(Converters.java:95) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:42) ~[ProtocolLib.jar:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.comphenix.protocol.wrappers.Converters$5.getSpecific(Converters.java:164) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.Converters$5.getSpecific(Converters.java:155) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:274) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.readSafely(StructureModifier.java:248) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.optionRead(StructureModifier.java:262) ~[ProtocolLib.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onLoginStart(ProtocolLibListener.java:226) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:149) ~[FastLoginBukkit.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:625) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:579) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:48) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:223) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:292) ~[ProtocolLib.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-323]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Most of the time, I'll see this:
```
[18:14:02 INFO]: Solde[/192.168.1.1:54479] logged in with entity id 493 at ([world]-115.5, 64.0, 60.5)
[18:14:03 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=Solde} with ID 192.168.1.1:54479.
[18:14:03 INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received
```

### What did you expect?

Auto login should work.

### Steps to reproduce

1. Have autologin enabled in FastLogin
2. Use AuthMe, and try to log in to the server
3. Ensure that FastLogin is build 1176, ProtocolLib is version 5 build 607. Minecraft version is 1.19.3, running Paper build 323.

### Plugin list

AuthMe, FastLogin, LuckPerms, ProtocolLib, SkinsRestorer, Skoice

### Configuration file

https://gist.github.com/zapteryx/8a4349a5d90709e0cceaae34e2fff237

### Plugin version

1.12-SNAPSHOT-2989d9a (#1176)

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by zapteryx** [comment]
any acknowledgement on this issue? there seems to be no way at all to circumvent this issue

**Comment by Merded** [comment]
@games647
