### ISSUE TITLE
Error when using latest Velocity build (fresh installation)

### ISSUE THREAD

**Issue by Hyrius** [games647/FastLogin#976]
### What happened?

[Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to fastlogin
java.lang.NoClassDefFoundError: org/sqlite/SQLiteConfig
	at com.github.games647.fastlogin.core.storage.SQLiteStorage.setParams(SQLiteStorage.java:64) ~[?:?]
	at com.github.games647.fastlogin.core.storage.SQLiteStorage.<init>(SQLiteStorage.java:49) ~[?:?]
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:234) ~[?:?]
	at com.github.games647.fastlogin.velocity.FastLoginVelocity.onProxyInitialization(FastLoginVelocity.java:96) ~[?:?]
	at com.github.games647.fastlogin.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-220.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0-SNAPSHOT-220.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0-SNAPSHOT-220.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.sqlite.SQLiteConfig
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.2.0-SNAPSHOT-220.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.2.0-SNAPSHOT-220.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 11 more

### Steps to reproduce

Fresh Velocity #220 (latest build) with fresh FastLoginVelocity.jar #1190. 
Didn't change any config files, error shows up every time the server is started.

### Plugin version

#1190

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
As mentioned in the setup guide, BungeeCord and Velocity have no driver for SQLite. So you are required to use MySQL or MariaDB.
