### ISSUE TITLE
Impossible to use FastLogin

### ISSUE THREAD

**Issue by Benny-21** [games647/FastLogin#978]
### What happened?

Trying to do /premium with the last version of AuthMe on a Paper server in 1.19.3, the console report an error. I didn't modify the configuration file.

### Plugin list

AdvancedBan, AdvancedPortals, AuthMe, BossBarTimer, ChatColor2, ChatSentinel, Citizens, CitizensServerSelector, DeluxeHub, F3NP| erm, FastLogin*, GSit, HeadDatabase, LuckPerms, MyCommand, PlaceholderAPI, PlayerParticles, PlugManX (PlugMan), SkinsRestorer, StaffChat*, TAB, TagSomeone*, V| ault, VaultChatFormatter*, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard 

### Server log

[21:55:59 ERROR]: null                                                                                                                                        |
org.bukkit.command.CommandException: Cannot execute command 'premium' in plugin FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432 - plugin is disabl|
ed.                                                                                                                                                           |
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]                                            |
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]                                    |
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-381]                                |
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-381]                   |
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]                                                   |
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]                                                                           |
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]                                                                           |
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]                        |
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]               |
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]                                               |
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]                                                         |
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-381]                                                              |
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]                                                         |
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]                                        |
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-381]                                        |
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-381]                                                 |
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]                                                          |
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-381]                                 |
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-381]                                         |
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]                                                      |
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-381]                                |
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-381]                                        |
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-381]                                     |
        at java.lang.Thread.run(Thread.java:833) ~[?:?]                                                                                                       |

### Plugin version

FastLogin 1.10

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
If the plugin disabled itself, there has to be an earlier error message.
