### ISSUE TITLE
Freeze on sending request when /premium

### ISSUE THREAD

**Issue by akuachi** [games647/FastLogin#995]
### What happened?

When i do /premium it freeze on sending request

### What did you expect?

 the /premium behavior 

### Steps to reproduce

Just /premium

### Plugin list

[21:36:07 INFO]: Bukkit Plugins: (30): [21:36:07 INFO]:  - AdvancedPortals, ajParkour, AuthMe, BungeeGuard, BuycraftX, Citizens, CoreProtect, DeluxeHub, DiscordSRV, FastAsyncWorldEdit [21:36:07 INFO]:  FastLogin, GadgetsMenu, GrimAC, HubPvP, LaunchPads, LiteBans, LoneLibs, LPC, LuckPerms, NoteBlockAPI [21:36:07 INFO]:  PlaceholderAPI, ProtocolLib, *SkMusic, Skript, spark, TAB, Vault, ViaBackwards, ViaRewind, ViaVersion

### Server log

Proxy: https://pastebin.com/AWYXu8EP
Hub: https://pastebin.com/0z8cCsU8

### Plugin version

All the final snapshot 

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
You are not using the latest build on the proxy.

**Comment by akuachi** [comment]
I can't find the last build

**Comment by games647** [comment]
You are already using the latest version on the hub server. So you find the correct location. You only need to install the proxy version on BungeeCord too.

**Comment by akuachi** [comment]
20:47:13 [WARNING] Exception encountered when loading plugin: FastLogin
java.lang.NoClassDefFoundError: org/sqlite/SQLiteConfig
    at com.github.games647.fastlogin.core.storage.SQLiteStorage.setParams(SQLiteStorage.java:64)
    at com.github.games647.fastlogin.core.storage.SQLiteStorage.<init>(SQLiteStorage.java:49)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:234)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:89)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.sqlite.SQLiteConfig
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 8 more

**Comment by akuachi** [comment]
20:49:02 [WARNING] Exception encountered when loading plugin: FastLogin
fastlogin.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Access denied for user ''@'localhost' (using password: NO)
    at fastlogin.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
    at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
    at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:115)
    at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
    at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:80)
    at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:39)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:252)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:89)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.sql.SQLException: Access denied for user ''@'localhost' (using password: NO)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
    at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
    at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
    at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
    at fastlogin.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    at fastlogin.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
    at fastlogin.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
    at fastlogin.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
    at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
    ... 10 more

**Comment by akuachi** [comment]
Idk how to crate a database i use ubuntu and i've installed mysql,  can we talk on discord??? if yes akuachi#5732

**Comment by akuachi** [comment]
I've fixed the database but now this 
17:23:03 [SEVERE] FastLogin - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at fastlogin.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fastlogin.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fastlogin.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fastlogin.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:80)
	at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:39)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:252)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:89)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.protocol.a.authentication.Sha256PasswordPlugin.nextAuthenticationStep(Sha256PasswordPlugin.java:140)
	at com.mysql.cj.protocol.a.authentication.Sha256PasswordPlugin.nextAuthenticationStep(Sha256PasswordPlugin.java:59)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:447)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:212)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1433)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
	... 18 more
17:23:03 [WARNING] Exception encountered when loading plugin: FastLogin
fastlogin.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Public Key Retrieval is not allowed
	at fastlogin.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at fastlogin.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fastlogin.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.github.games647.fastlogin.core.storage.SQLStorage.<init>(SQLStorage.java:80)
	at com.github.games647.fastlogin.core.storage.MySQLStorage.<init>(MySQLStorage.java:39)
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:252)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:89)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at fastlogin.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fastlogin.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fastlogin.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fastlogin.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fastlogin.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 10 more
Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.protocol.a.authentication.Sha256PasswordPlugin.nextAuthenticationStep(Sha256PasswordPlugin.java:140)
	at com.mysql.cj.protocol.a.authentication.Sha256PasswordPlugin.nextAuthenticationStep(Sha256PasswordPlugin.java:59)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:447)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:212)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1433)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
	... 18 more

**Comment by games647** [comment]
Either change the MySQL/MariaDB setting or disable the key retrieval settings in the FastLogin configuration.
